trigger:
  branches:
    include:
      - development
      - uat
      - master
      - prod
      - main

variables:
- template: cicd/vars.yaml

jobs:
  - job:
    displayName: 'DEV_PB_CD'
    condition: eq(variables['Build.SourceBranchName'], 'development')
    steps:
      - checkout: self
        persistCredentials: true
        clean: true
        fetchDepth: 0

      - script: |
          echo "Running DEV cd pipeline....."
          git config --global user.email "azuredevops@drmartens.com"
          git config --global user.name "Azure Devops PBI"
          git diff --name-only HEAD~1 HEAD> changed_files.txt
          CHANGED_FILES=$(paste -sd " " changed_files.txt)
          echo $CHANGED_FILES
          echo "##vso[task.setvariable variable=changes;isOutput=true]$CHANGED_FILES"
          if [[ "$CHANGED_FILES" == *"pbi_tools/"* ]]; then
            PBI_CHANGES=true
          else
            PBI_CHANGES=false
          fi
          echo "##vso[task.setvariable variable=pbi_changes;isOutput=true]$PBI_CHANGES"
        displayName: 'Get Changed Files'
        name: getChangedFiles

      - template: cicd/az-pipeline-env.yaml
        parameters:
          cicd: cd
      
      - bash: |
          echo "Changed files: $(getChangedFiles.changes)"
          echo "PBI Changes: $(getChangedFiles.pbi_changes)"
        displayName: 'Changes Printed..'

      - template: cicd/az-pipeline-tag.yaml

      - template: cicd/az-pipeline-app-cd.yaml

      - template: cicd/az-pipeline-reports-cd.yaml
        parameters:
          env: dev


  - job:
    displayName: 'UAT_PB_CD'
    condition: eq(variables['Build.SourceBranchName'], 'uat')
    steps:
      - script: |
          echo "Running UAT cd pipeline...."

      - template: cicd/az-pipeline-env.yaml

      - template: cicd/az-pipeline-reports-cd.yaml
        parameters:
          env: uat

  - job:
    displayName: 'PROD_PB_CD'
    condition: in(variables['Build.SourceBranchName'], 'master', 'prod', 'main')
    steps:
      - script: |
          echo "Running PROD cd pipeline...."

      - template: cicd/az-pipeline-env.yaml

      - template: cicd/az-pipeline-reports-cd.yaml
        parameters:
          env: prod

