pr:
  branches:
    include:
      - development
      - uat
      - prod
  paths:
    include:
      - pbi_tools/*

variables:
  PYTHON_VERSION: '3.11'

jobs:
- job: PowerBIAppCI
  displayName: 'PBI App integration.'
  steps:

    - template: az-pipelines-env.yaml

    - script: |
        just check-ruff
      displayName: 'Run Ruff checks'

    - script: |
        just test-all
      env:
        API_PASSWORD: $(api_password)
        API_USERNAME: $(api_username)
        CLIENT_ID: $(client_id)
        CLIENT_SECRET: $(client_secret)
      displayName: 'Run Pyest Tests'