pr:
  branches:
    include:
      - development
      - uat
      - prod
      - main
      - master

variables:
  - template: cicd/vars.yaml

jobs:
  - job: PowerBIAppCI
    displayName: "PBI App integration."
    steps:
      - template: cicd/az-pipeline-env.yaml

      - script: |
          echo "Running PBI Application pipeline...."
          echo variables['Build.ChangedFiles']
          echo $(System.PullRequest.TargetBranch)
          echo $(System.PullRequest.targetBranchName)
          echo $(Build.SourceBranch)
          echo "Build.SourceBranchName:    $(Build.SourceBranchName)" 
          echo "Build.Reason:    $(Build.Reason)"
          echo "Changed Files in application variable:"
          echo variables['getChangedFiles.app_changes']
          echo "Changed Files in Power BI Reports variable:"
          echo variables['getChangedFiles.pbi_changes']
        displayName: debug

      - template: cicd/az-pipeline-app-ci.yaml

      - template: cicd/az-pipeline-reports-ci.yaml
