trigger:
  branches:
    include:
      - development
      - uat
      - master
      - prod
      - main
      
  paths:
    include:
      - powerbi/*

jobs:
- job: PowerBIAppIntegrationJob
  displayName: 'PBI App integration, will not run on tag PR.'
  steps:

    - template: az-pipelines-env.yaml
    
    - script: |
        echo "Checking number of rows set to zero"
        poetry run pbi check-num-rows-vars-zero
      displayName: 'Check number of rows set to zero'

    - script: |
        echo "Checking multi partitions are in place."
        poetry run pbi check-partitions
      displayName: 'Check multi partitions'
