trigger:
  branches:
    include:
      - prod
      - development
      - uat
  paths:
    include:
      - pbi_tools/*

variables:
  PYTHON_VERSION: '3.11'
  ARTIFACT_FEED: 'Windermere Discovery/windermere_artifactory'
  CI_USERNAME: "Power BI CI Pipeline"
  CI_EMAIL: powerbi_ci@drmartens.com

jobs:
- job: PowerBIAppIntegrationJob
  displayName: 'PBI App integration, will not run on tag PR.'
  steps:

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(PYTHON_VERSION)'

    - script: |
        pip install rust-just
        just install-poetry
      displayName: 'Install Python requirements with Poetry'

    - script: |
        just bump-push
      displayName: 'Bump Version, tag and merge.'

    - script: |
        poetry build
      displayName: 'Build Python Package with Poetry'

    - task: TwineAuthenticate@1
      inputs:
        artifactFeed: '$(ARTIFACT_FEED)'
      displayName: 'Twine Authenticate'

    - script: |
        python -m twine upload -r windermere_artifactory --config-file $(PYPIRC_PATH) dist/*
      displayName: 'Upload to feed'