trigger:
  branches:
    include:
      - development
      - uat
      - master
      - prod
      - main

variables:
  - template: cicd/vars.yaml

jobs:
  - job:
    displayName: "DEV_PB_CD"
    condition: eq(variables['Build.SourceBranchName'], 'development')
    steps:
      - checkout: self
        persistCredentials: true
        clean: true
        fetchDepth: 0

      - template: cicd/az-pipeline-env.yaml
        parameters:
          cicd: cd

      - bash: |
          echo "Changed files: $(getChangedFiles.changes)"
          echo "PBI Changes: $(getChangedFiles.pbi_changes)"
          echo "APP Changes: $(getChangedFiles.app_changes)"
        displayName: "Changes Printed.."

      - template: cicd/az-pipeline-tag.yaml

      - template: cicd/az-pipeline-app-cd.yaml

      - template: cicd/az-pipeline-reports-cd.yaml
        parameters:
          env: dev

  - job:
    displayName: "UAT_PB_CD"
    condition: eq(variables['Build.SourceBranchName'], 'uat')
    steps:
      - script: |
          echo "Running UAT cd pipeline...."

      - template: cicd/az-pipeline-env.yaml

      - template: cicd/az-pipeline-reports-cd.yaml
        parameters:
          env: uat

  - job:
    displayName: "PROD_PB_CD"
    condition: in(variables['Build.SourceBranchName'], 'master', 'prod', 'main')
    steps:
      - script: |
          echo "Running PROD cd pipeline...."

      - template: cicd/az-pipeline-env.yaml

      - template: cicd/az-pipeline-reports-cd.yaml
        parameters:
          env: prod
