trigger:
  branches:
    include:
      - development
      - uat
      - master
      - prod
      - main

stages:
  - stage: DEV_PBI_CD
    condition: eq(variables['Build.SourceBranchName'], 'development')
    jobs:

      - script: |
          echo "Running DEV cd pipeline...."

      - template: az-pipeline-env.yaml

      - template: az-pipeline-tag.yaml

      - template: az-pipeline-reports-cd.yaml
        parameters:
          env: dev



  - stage: UAT_PBI_CD
    condition: eq(variables['Build.SourceBranchName'], 'uat')
    jobs:
      - script: |
          echo "Running UAT cd pipeline...."

      - template: az-pipeline-env.yaml

      - template: az-pipeline-reports-cd.yaml
        parameters:
          env: uat

  - stage: PROD_PBI_CD
    condition: in(variables['Build.SourceBranchName'], 'master', 'prod', 'main')
    jobs:
      - script: |
          echo "Running PROD cd pipeline...."

      - template: az-pipeline-env.yaml

      - template: az-pipeline-reports-cd.yaml
        parameters:
          env: prod

      - template: az-pipeline-app-cd.yaml
        condition: changes in application powerbi directory...
