pr:
  branches:
    include:
      - development

trigger:
  branches:
    include:
      - refactor-major-cleanup

pool:
  vmImage: 'ubuntu-latest'

variables:
  PYTHON_VERSION: '3.11'
  ARTIFACT_FEED: 'Windermere Discovery/windermere_artifactory'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(PYTHON_VERSION)'

- script: |
    python -m pip install --upgrade pip
    pip install poetry
  displayName: 'Install Poetry'

- script: |
    poetry install --with dev
  displayName: 'Install Dependencies with Poetry'

- script: |
    poetry run pytest
  displayName: 'pytest'

- script: |
    poetry run check
  displayName: 'Run Ruff'

- script: |
    poetry build
  displayName: 'Build Python Package with Poetry'

- script: |
    python -m pip install twine
  displayName: 'Install twine dependencies'

- task: TwineAuthenticate@1
  inputs:
    artifactFeed: '$(ARTIFACT_FEED)'
  displayName: 'Twine Authenticate'

- script: |
    python -m twine upload -r windermere_artifactory --config-file $(PYPIRC_PATH) dist/*
  displayName: 'Upload to feed'