pr:
  branches:
    include:
      - development
      - uat
      - master
      - prod
  paths:
    include:
      - pbi_tools/*
      - azure-pipelines-app.yml

variables:
  PYTHON_VERSION: '3.10'
  ARTIFACT_FEED: 'Windermere Discovery/windermere_artifactory'
  CI_USERNAME: "Power BI CI Pipeline"
  CI_EMAIL: powerbi_ci@drmartens.com
  SOURCE_BRANCH_BUILD: $[ replace(variables['Build.SourceBranch'] ]
  SOURCE_BRANCH_BUILD_NAME: $[variables['Build.SourceBranchName']]
  SOURCE_BRANCH_BUILD_NAME_FQ: $[variables['Build.PullRequest.SourceBranchName']]
  SOURCE_BRANCH_SYSTEM: $[ variables['System.PullRequest.SourceBranch'] ]
  TARGET_BRANCH_SYSTEM: $[ variables['System.PullRequest.TargetBranchName'] ]
  TARGET_BRANCH_BUILD: $[ variables['Build.PullRequest.TargetBranchName'] ]
  TARGET_BRANCH_TEST: $(BUILD_PULLREQUEST_TARGETBRANCHNAME)
  TAG_PUSH: $[ startsWith(variables['Build.SourceBranch'], 'refs/tags/') ]
  REASON_BUILD: $[ variables['Build.Reason' ]

jobs:
  - job: DeployPBIReports
    displayName: 'PBI Appp integration, will not run on tag PR.'
    steps:
      - script: |
          echo $(PYTHON_VERSION)
          echo $(SOURCE_BRANCH_BUILD)
          echo $(SOURCE_BRANCH_BUILD_NAME)
          echo $(SOURCE_BRANCH_SYSTEM)
          echo $(TARGET_BRANCH_SYSTEM)
          echo $(TARGET_BRANCH_BUILD)
          echo $(TARGET_BRANCH_TEST)
          echo $(TAG_PUSH)
          echo $(REASON_BUILD)
          echo $(SOURCE_BRANCH_BUILD_NAME_FQ)
        displayName: 'Debuging....'
        
      - script: |
          echo "Deploying Power BI changes..."
          echo "set variables in expressions.tmdl"
          echo "commit amend back to repository"
          echo "USE POWER BI API TO SYNC TO WORKSPACE"
          just poetry-install
          poetry pbi sync-workspace-git --env $(ENV)
