pr:
  branches:
    include:
      - development
      - uat
      - master
      - prod
  paths:
    include:
      - powerbi/*
      - azure-pipelines-dbt.yml

variables:
  PYTHON_VERSION: '3.10'
  ARTIFACT_FEED: 'Windermere Discovery/windermere_artifactory'
  CI_USERNAME: "Power BI CI Pipeline"
  CI_EMAIL: powerbi_ci@drmartens.com
  SOURCE_BRANCH_BUILD: $[ replace(variables['Build.SourceBranch'] ]
  SOURCE_BRANCH_BUILD_NAME: $[variables['Build.SourceBranchName']]
  SOURCE_BRANCH_BUILD_NAME_FQ: $[variables['Build.PullRequest.SourceBranchName']]
  SOURCE_BRANCH_SYSTEM: $[ variables['System.PullRequest.SourceBranch'] ]
  TARGET_BRANCH_SYSTEM: $[ variables['System.PullRequest.TargetBranchName'] ]
  TARGET_BRANCH_BUILD: $[ variables['Build.PullRequest.TargetBranchName'] ]
  TARGET_BRANCH_TEST: $(BUILD_PULLREQUEST_TARGETBRANCHNAME)
  TAG_PUSH: $[ startsWith(variables['Build.SourceBranch'], 'refs/tags/') ]
  REASON_BUILD: $[ variables['Build.Reason' ]

stages:
  - stage: POWER_BI_APP
    jobs:
    - job: PowerBIAppIntegrationJob
      displayName: 'PBI Appp integration, will not run on tag PR.'
      steps:

        - script: |
            echo $(PYTHON_VERSION)
            echo $(SOURCE_BRANCH_BUILD)
            echo $(SOURCE_BRANCH_BUILD_NAME)
            echo $(SOURCE_BRANCH_SYSTEM)
            echo $(TARGET_BRANCH_SYSTEM)
            echo $(TARGET_BRANCH_BUILD)
            echo $(TARGET_BRANCH_TEST)
            echo $(TAG_PUSH)
            echo $(REASON_BUILD)
            echo $(SOURCE_BRANCH_BUILD_NAME_FQ)
          displayName: 'Debuging....'

        - task: UsePythonVersion@0
          inputs:
            versionSpec: '$(PYTHON_VERSION)'

        - script: |
            just poetry-install
          displayName: 'Install Python requirements with Poetry'

        - script: |
            just test-all
          displayName: 'Run Tests'

        - script: |
            just check-ruff
          displayName: 'Run Ruff'

        - script: |
            just bump
            echo "Fetching the latest Git tag..."
            GIT_TAG=$(git describe --abbrev=0)
            git push origin $GIT_TAG
            echo "##vso[task.setvariable variable=gitTag]$GIT_TAG"
          displayName: 'Bump Version, and tag version and merge.'
          condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/')

        - script: |
            git checkout $(gitTag)
            poetry build
          displayName: 'Build Python Package with Poetry'
          condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

        - task: TwineAuthenticate@1
          inputs:
            artifactFeed: '$(ARTIFACT_FEED)'
          displayName: 'Twine Authenticate'

        - script: |
            python -m twine upload -r windermere_artifactory --config-file $(PYPIRC_PATH) dist/*
          displayName: 'Upload to feed'
          condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

GIT_TAG=$(git describe --abbrev=0 || echo "no-tags-found")

    - job: PowerBIAppDeployment
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
      dependsOn: PowerBIAppIntegrationJob
      variables:
        latestGitTag: $[dependencies.PowerBIAppIntegrationJob.outputs['PowerBIAppIntegrationJob.gitTag']
      steps:
        - script: |
            poetry build
          displayName: 'Build Python Package with Poetry'

        - task: TwineAuthenticate@1
          inputs:
            artifactFeed: '$(ARTIFACT_FEED)'
          displayName: 'Twine Authenticate'

        - script: |
            python -m twine upload -r windermere_artifactory --config-file $(PYPIRC_PATH) dist/*
          displayName: 'Upload to feed'