trigger:
  branches:
    include:
      - development
      - uat
      - master
      - prod
      - main
pr:
  branches:
    include:
      - development
      - uat
      - master
      - prod
      - main

variables:
  - template: cicd/vars.yaml

stages:
  # --- CI Stage: Runs only on PRs ---
  - stage: Check
    displayName: "CI - Run Checks on PR"
    jobs:
      - job: DetectChanges
        displayName: "Detect Folder Changes"
        steps:
          # Set python environment...
          - template: cicd/az-pipeline-env.yaml

          - script: |
              just git-config $(TargetBranch)
            displayName: "Configure git to use service account"

          - script: |
              echo "Checking for PR changes..."
              changes=$(just files-changed $(TargetBranch))
              echo "The follow file changes where detected:\n $changes"
              APP_CHANGES="$(echo "$changes" | grep -q "Application" && echo "true" || echo "false")"
              PBI_CHANGES="$(echo "$changes" | grep -q "Report" && echo "true" || echo "false")"
              echo "##vso[task.setvariable variable=app_changes;isOutput=true]$APP_CHANGES"
              echo "##vso[task.setvariable variable=pbi_changes;isOutput=true]$PBI_CHANGES"
              echo "Application Changes: $APP_CHANGES"
              echo "Report Changes: $PBI_CHANGES"
            displayName: "Check File Changes"
            name: Changes

      - job: PythonChecks
        dependsOn: DetectChanges
        condition: eq(dependencies.DetectChanges.outputs['Changes.app_changes'], 'true')
        displayName: "Run Python Checks"
        steps:
          # Set python environment...
          - template: cicd/az-pipeline-env.yaml

          - script: |
              just cz-check $(TargetBranch)
            displayName: "Check new commits follow conventional commits."
            condition: eq(variables['Build.Reason'], 'PullRequest')

          - script: |
              just bump-dry
            displayName: "Test bump version"

          - script: |
              just check-ruff
            displayName: "Run Ruff checks"

          - script: |
              just test-all-cov
            env:
              API_PASSWORD: $(API_PASSWORD)
              API_USERNAME: $(API_USERNAME)
              CLIENT_ID: $(CLIENT_ID)
              CLIENT_SECRET: $(CLIENT_SECRET)
            displayName: "Run Pyest Tests"

          - template: cicd/az-pipeline-pub-tests.yaml

      - job: PowerBIChecks
        dependsOn: DetectChanges
        condition: eq(dependencies.DetectChanges.outputs['Changes.pbi_changes'], 'true')
        displayName: "Run Power BI Checks"
        steps:
          # Set python environment...
          - template: cicd/az-pipeline-env.yaml

          - script: |
              echo "checking number of rows set to zero"
              result=$(poetry run pbi check-num-rows-vars-zero)
              if [[ $result == warning* ]] ;
              then
                echo "##vso[task.logissue type=warning;]$result"
              else
                echo "$result" 
              fi
            displayName: "check number of rows set to zero"

          - script: |
              echo "checking multi partitions are in place."
              result=$(poetry run pbi check-partitions)
              if [[ $result == warning* ]] ;
              then
                echo "##vso[task.logissue type=warning;]$result"
              else
                echo "$result"
              fi
            displayName: "Check multi partitions"

  - stage: Release
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    displayName: "CD - Deploy After Merge"
    jobs:
      - job: DeployPBIApp
        displayName: "Release Power BI Python App"
        condition: and(eq(variables['Build.SourceBranchName'], 'development'), eq(stageDependencies.Check.DetectChanges.outputs['Changes.app_changes'], 'true'))
        steps:
          # Set python environment...
          - template: cicd/az-pipeline-env.yaml

          - script: |
              echo "Running commitizen to bump version and update release log."
              just bump-skip-ci
            displayName: "Bump version and push tags."

          - script: |
              poetry build
            displayName: "Build Python Package with Poetry"

          - task: TwineAuthenticate@1
            inputs:
              artifactFeed: "$(ARTIFACT_FEED)"
            displayName: "Twine Authenticate"

          - script: |
              poetry run python -m twine upload -r windermere_artifactory --config-file $(PYPIRC_PATH) dist/*
            displayName: "Upload to artifactory feed"

      - job: ReleasePowerBI
        displayName: "Release Power BI Reports"
        condition: eq(stageDependencies.Check.DetectChanges.outputs['Changes.pbi_changes'], 'true')
        steps:
          # Set python environment...
          - template: cicd/az-pipeline-env.yaml

          - script: |
              env=$(just get-env $(basename $(Build.SourceBranchName)))
              echo "Target Branch: $env"
              echo "##vso[task.setvariable variable=env]$env"
            displayName: "Determine Target Environment"

          - script: |
              poetry run pbi set-pipeline-variables $(env)
              git commit -v -a --no-edit --amend
              displayName: "Set Pipeline variables to env default"

          - script: |
              poetry run pbi sync-workspace-git --env $(env)
            displayName: "Sync with Power BI workspace"
            env:
              API_PASSWORD: $(API_PASSWORD)
              API_USERNAME: $(API_USERNAME)
              CLIENT_ID: $(CLIENT_ID)
              CLIENT_SECRET: $(CLIENT_SECRET)
