table 'Selling Status - Invoice'
	lineageTag: 59ba3970-e364-4daf-a436-36a63079a1c0

	column 'Selling Status'
		dataType: int64
		isHidden
		sourceProviderType: nvarchar(16777216)
		displayFolder: zz_Misc
		lineageTag: a99396e2-c89c-4693-8463-f4197df215c0
		summarizeBy: none
		sourceColumn: Selling Status

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Selling Status - Invoice'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 9bee9f50-6364-4573-8c75-69246c9deef8
		summarizeBy: none
		sourceColumn: Selling Status - Invoice
		sortByColumn: 'Selling Status Sort'

		annotation SummarizationSetBy = Automatic

	column 'Selling Status Sort'
		dataType: int64
		isHidden
		sourceProviderType: decimal(1, 0)
		displayFolder: zz_Misc
		lineageTag: e75d778b-3a2c-4eed-801e-4ccfb059baf8
		summarizeBy: none
		sourceColumn: Selling Status Sort

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'TBD vs Continuity/Carry Over - Invoice' =
			IF (
			    'Selling Status - Invoice'[Selling Status - Invoice]
			        IN { "Continuity", "Carry Over" },
			    "Continuity/Carry Over",
			    'Selling Status - Invoice'[Selling Status - Invoice]
			)
		lineageTag: 9ee5c99d-3fad-4212-9b55-5dc8cf3adc39
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Selling Status - Invoice' = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    TB_BFN_VW_D365DIMSELLINGSTATUS_INVOICE_View = BFN_PRESENTATION_Schema{[Name="TB_BFN_VW_D365DIMSELLINGSTATUS_INVOICE",Kind="View"]}[Data],
				    #"Removed Duplicates" = Table.Distinct(TB_BFN_VW_D365DIMSELLINGSTATUS_INVOICE_View, {"Selling Status"}),
				    #"Removed Blank Rows" = Table.SelectRows(#"Removed Duplicates", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
				in
				    #"Removed Blank Rows"

	annotation PBI_ResultType = Table

