table Region
	lineageTag: 7ae2fab6-2b75-4bfb-a0ac-fd31b0601e80

	column 'Company Name'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: f27cde82-fb5d-4ed1-ae20-a6f69fe5340f
		summarizeBy: none
		sourceColumn: Company Name

		annotation SummarizationSetBy = Automatic

	column 'Region ID'
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		displayFolder: zz_Misc
		lineageTag: f72c52c8-d8b1-4db4-9a91-293e1ce59daa
		summarizeBy: none
		sourceColumn: Region ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Company ID'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 41471a71-6abe-432c-b7a9-5226e7f656c0
		summarizeBy: none
		sourceColumn: Company ID

		annotation SummarizationSetBy = Automatic

	column Company_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(32)
		displayFolder: zz_Misc
		lineageTag: 7064b8d8-f3a4-4ca1-aec9-1983d9856784
		summarizeBy: none
		sourceColumn: Company_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: e788aa37-7aff-446b-b100-18eccb30c387
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Sub-Region
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: c00a8e93-6f05-4dec-a396-63d622d5ab76
		summarizeBy: none
		sourceColumn: Sub-Region

		annotation SummarizationSetBy = Automatic

	partition Region = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    TB_BFN_VW_D365DIMCOMPANY_View = BFN_PRESENTATION_Schema{[Name="TB_BFN_VW_D365DIMCOMPANY",Kind="View"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(TB_BFN_VW_D365DIMCOMPANY_View, each ([Company_Key] <> 0))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

