table 'Adjustments CoGS'
	isHidden
	lineageTag: 554a171c-fd6e-42ed-95d6-f00709233353

	column 'Amount at Constant Rate'
		dataType: decimal
		isHidden
		sourceProviderType: decimal(38, 2)
		displayFolder: zz_Values
		lineageTag: 55b4c584-df32-4a5f-85f3-6d4604065bd3
		summarizeBy: none
		sourceColumn: Amount at Constant Rate

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AccountingDate_Key
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: nvarchar(16777216)
		displayFolder: zz_Keys
		lineageTag: b4fe8634-656a-47bc-a4d1-e98bc8437ef7
		summarizeBy: none
		sourceColumn: AccountingDate_Key

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

	column Company_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(32)
		displayFolder: zz_Keys
		lineageTag: 1d15ba9a-a004-4997-8df0-22166a1b0ca9
		summarizeBy: none
		sourceColumn: Company_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Channel_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(32)
		displayFolder: zz_Keys
		lineageTag: 88bba7b9-6f37-4f00-bd7d-674ab8f5996c
		summarizeBy: none
		sourceColumn: Channel_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TransactionTypeDesc
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: 26466eea-578f-47eb-9761-0c20a0b78b48
		summarizeBy: none
		sourceColumn: TransactionTypeDesc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CHANNEL
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: 51122b1e-f051-4c86-95d6-8a1430f3b6a6
		summarizeBy: none
		sourceColumn: CHANNEL

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MAINACCOUNTID
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: a03bc71b-e890-4d8c-b83d-0f9273430b87
		summarizeBy: none
		sourceColumn: MAINACCOUNTID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column LEDGERNAME
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: d019877f-d161-49fb-b97e-1c7478b5f3b4
		summarizeBy: none
		sourceColumn: LEDGERNAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Adjustments CoGS-8c25a919-b028-4f6d-af28-0f1530557376' = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server, Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    BFN_VW_D365FACTASE_View = BFN_PRESENTATION_Schema{[Name="BFN_VW_D365FACTASE",Kind="View"]}[Data],
				    #"Filtered Rows1"   = Table.SelectRows(BFN_VW_D365FACTASE_View, each [TransactionTypeDesc] <> "Sales" and List.Contains({103,104},[CHANNEL]) and [MAINACCOUNTID] >= "50001" and [MAINACCOUNTID] <= "50059")
				in
				   #"Filtered Rows1"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

