table 'Date Slicer'
	lineageTag: ce782480-dce4-4765-8dea-a1399047d5a5

	column 'Date Slicer'
		dataType: string
		sourceProviderType: nvarchar(16)
		lineageTag: 71e28245-ac87-45b7-8d83-32adb9f6e5e0
		summarizeBy: none
		sourceColumn: Date Slicer
		sortByColumn: SortOrder

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isHidden
		formatString: General Date
		sourceProviderType: datetime2
		displayFolder: zz_Misc
		lineageTag: c43e9fd8-d6ce-4fb3-9803-85e4afd21264
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SortOrder
		dataType: string
		isHidden
		lineageTag: f892db1e-0fec-4905-87d4-031df8b5e307
		summarizeBy: none
		sourceColumn: SortOrder

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Date Slicer' = m
		mode: import
		source =
				let
					Source = Snowflake.Databases(Datasource_Server, Datasource_Warehouse),
					PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
					BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
					BFN_Datatable_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_DIMDATESLICER",Kind="View"]}[Data],
					#"Reordered Columns" = Table.ReorderColumns(BFN_Datatable_View,{"Date", "Date Slicer"}),
					#"Kept First Rows" = Table.FirstN(#"Reordered Columns",NumberOfRows),
					ParameterFilter = if NumberOfRows > 0 then #"Kept First Rows" else #"Reordered Columns"
				in
					ParameterFilter

	annotation PBI_ResultType = Table

