table 'Display Currency'
	lineageTag: e4bb3355-c19f-4c34-962f-af7f423306f7

	column 'Currency Code'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: a6e8754a-cc82-488e-923c-b0dd316e56f5
		summarizeBy: none
		sourceColumn: Currency Code

		annotation SummarizationSetBy = Automatic

	column 'Currency Name'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: f5d0bcac-74a4-4305-9a08-989f44a3d807
		summarizeBy: none
		sourceColumn: Currency Name

		annotation SummarizationSetBy = Automatic

	column 'Currency Symbol'
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: 8baaa7dc-6401-4d9c-940e-fe1868758e69
		summarizeBy: none
		sourceColumn: Currency Symbol

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column XRMultiplier =
			IF (
			    'Display Currency'[Currency Code] = "GBP",
			    1,
			    LOOKUPVALUE (
			        'Exchange Rates'[RATE],
			        'Exchange Rates'[FROMCURRENCY], "GBP",
			        'Exchange Rates'[RATETYPENAME], "BUDGET",
			        'Exchange Rates'[TOCURRENCY], 'Display Currency'[Currency Code]
			    )
			)
		isHidden
		lineageTag: a1424e17-fc82-4ad2-aedb-63719e3dabb0
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NAME
		dataType: string
		isHidden
		lineageTag: 874dadd4-3946-49f6-9554-727b4410e030
		summarizeBy: none
		sourceColumn: NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Display Currency' = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server, Datasource_Warehouse),
					#"Extra Currencies" = #table({"NAME", "Currency Code", "Currency Name", "Currency Symbol"}, {{ "Constant (GBP)", "GBP_CONS", "Constant (GBP)", "£"},{ "Closing (GBP)", "GBP_CLOS", "Closing (GBP)", "£"},{ "Transaction Currency", "TRANS", "Transaction Currency", ""}}),
					PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    BFN_Datatable_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365DIMCURRENCY",Kind="View"]}[Data],
					#"Filtered Rows" = Table.SelectRows(BFN_Datatable_View, each List.Contains({"Canadian Dollar", "Euro", "Hong Kong Dollar", "Pound Sterling", "Singapore Dollar", "US Dollar", "Won", "Yen"},[Currency Name])),
					#"Appended Query" = Table.Combine({#"Filtered Rows", #"Extra Currencies"})
				in
					#"Appended Query"

	annotation PBI_ResultType = Table

