table 'S&OP Forecast'
	lineageTag: b612c828-eb18-42bc-a63d-fa3c73194909

	measure 'S&OP Forecast Invoiced $' =
			
			
			VAR A = SELECTEDVALUE(Products[Product Major])
			var B = SELECTEDVALUE(Customer[Customer Region Channel])
			VAR USRATE = LOOKUPVALUE('Display Currency'[XRMultiplier],'Display Currency'[Currency Code],"USD")
			VAR CADRATE = LOOKUPVALUE('Display Currency'[XRMultiplier],'Display Currency'[Currency Code],"CAD")
			VAR US = DIVIDE( CALCULATE([S&OP Inv Value],FILTER('S&OP Forecast','S&OP Forecast'[Currency]="USD")) , USRATE) * [XR]
			VAR CAN = DIVIDE( CALCULATE([S&OP Inv Value],FILTER('S&OP Forecast','S&OP Forecast'[Currency]="CAD")) , CADRATE) * [XR]
			//ENTER CANADIAN FORECASTS IN USD
			
			return
			US+CAN
			//SWITCH(SELECTEDVALUE(Customer[Customer Region Channel]),"US Wholesale",US,"Canada",CAN,US+CAN)
		lineageTag: ccd29bd6-e0d0-4bcc-838e-7447d7dc921a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'S&OP Forecast Invoiced Units' =
			
			
			[S&OP Inv Units]
			//SWITCH(SELECTEDVALUE(Customer[Customer Region Channel]),"US Wholesale",US,"Canada",CAN,US+CAN)
		formatString: 0
		lineageTag: 495d81a8-ddf7-4553-a7c4-6a7791430530

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'S&OP Forecast Returned $' =
			-
			
			
			VAR A = SELECTEDVALUE(Products[Product Major])
			var B = SELECTEDVALUE(Customer[Customer Region Channel])
			VAR USRATE = LOOKUPVALUE('Display Currency'[XRMultiplier],'Display Currency'[Currency Code],"USD")
			VAR CADRATE = LOOKUPVALUE('Display Currency'[XRMultiplier],'Display Currency'[Currency Code],"CAD")
			VAR US = DIVIDE( CALCULATE([S&OP Ret Value],FILTER('S&OP Forecast','S&OP Forecast'[Currency]="USD")) , USRATE) * [XR]
			VAR CAN = DIVIDE( CALCULATE([S&OP RET Value],FILTER('S&OP Forecast','S&OP Forecast'[Currency]="CAD")) , CADRATE) * [XR]
			
			//ENTER CANADIAN FORECASTS IN CAD
			
			return
			US+CAN
			//SWITCH(SELECTEDVALUE(Customer[Customer Region Channel]),"US Wholesale",US,"Canada",CAN,US+CAN)
		formatString: 0
		lineageTag: 40aa442b-aa1e-4fa7-880f-c236c2930b32

	measure 'S&OP Forecast Returned Units' =
			
			
			- [S&OP Ret Units]
			//SWITCH(SELECTEDVALUE(Customer[Customer Region Channel]),"US Wholesale",US,"Canada",CAN,US+CAN)
		formatString: 0
		lineageTag: cb771f64-b226-4dee-a93c-d7af7c80cd75

	measure 'S&OP Inv Units' = SUM('S&OP Forecast'[Invoiced Units])
		formatString: 0
		lineageTag: a6e13a58-5441-4452-8e1b-cb9c03b4dad4

	measure 'S&OP Ret Units' = SUM('S&OP Forecast'[Returned Units])
		formatString: 0
		lineageTag: 27cf3d2f-1431-4f53-a7a9-81fb565c7a20

	measure 'S&OP Inv Value' = SUM('S&OP Forecast'[Invoiced Net Value])
		formatString: 0
		lineageTag: d3a55e9b-18c0-471b-81e4-f6bcb8baa6b1

	measure 'S&OP Ret Value' = SUM('S&OP Forecast'[Returned Net Value])
		formatString: 0
		lineageTag: 40112675-2006-47cb-839a-521ac50d3ed0

	measure 'IS S&OP LOADED?' = IF(CALCULATE([S&OP Inv Value],ALL(Customer),ALL(Products))>0,"Yes","No")
		lineageTag: aebf4847-7e93-4255-bd24-368158c7fcdf

	measure 'IS S&OP LOADED TEXT COLOR' = IF([IS S&OP LOADED?]="Yes","#FFFFFF00","#FFFFFF")
		lineageTag: 908e8876-d07f-423f-83f9-7da134939063

	measure 'IS S&OP LOADED TEXT' = "No S&OP Projection Loaded"
		lineageTag: 426bdea8-e2a1-4723-8bfc-2d746d837416

	measure 'IS S&OP LOADED BACKGROUND' = IF([IS S&OP LOADED?]="Yes","#FFFFFF00","000000")
		lineageTag: 5d94e499-d8aa-44ee-9c82-398708720f98

	column Company
		dataType: string
		lineageTag: 0a604bd0-27d5-472e-b82b-0ae991a9e8f4
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = Automatic

	column Currency
		dataType: string
		lineageTag: b886eea7-fda1-46e5-9439-575c18b02be2
		summarizeBy: none
		sourceColumn: Currency

		annotation SummarizationSetBy = Automatic

	column 'Invoiced Net Value'
		dataType: double
		lineageTag: 8b7f5b22-9d3f-4b4e-9de2-62199dc28281
		summarizeBy: sum
		sourceColumn: Invoiced Net Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Returned Net Value'
		dataType: int64
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 5091229d-4bf4-40e0-929e-90d68d8a9468
		summarizeBy: sum
		sourceColumn: Returned Net Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Invoiced Units'
		dataType: int64
		formatString: 0
		lineageTag: 9e044e43-50fb-4254-80d5-8427e0f6cc17
		summarizeBy: sum
		sourceColumn: Invoiced Units

		annotation SummarizationSetBy = Automatic

	column 'Returned Units'
		dataType: int64
		formatString: 0
		lineageTag: 3a3235b1-c407-4fcc-9ab9-50e2cd18f2b5
		summarizeBy: sum
		sourceColumn: Returned Units

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: string
		lineageTag: ae0c4035-7040-4528-91df-20810af561e3
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

	column 'Forecast Version'
		dataType: string
		lineageTag: 9a6ac1bf-71d1-4759-9045-59f9d5fd281c
		summarizeBy: none
		sourceColumn: Forecast Version

		annotation SummarizationSetBy = Automatic

	column 'Customer Acc #'
		dataType: string
		lineageTag: a216b0f7-961d-4571-b30b-74aa5a9c7e85
		summarizeBy: none
		sourceColumn: Customer Acc #

		annotation SummarizationSetBy = Automatic

	column 'Product Code'
		dataType: string
		lineageTag: 65688f89-3ac7-4897-ba2f-f54ae95861ca
		summarizeBy: none
		sourceColumn: Product Code

		annotation SummarizationSetBy = Automatic

	column 'Total Net Value'
		dataType: double
		lineageTag: 8224068f-f3ad-4f04-b003-059e48366d03
		summarizeBy: sum
		sourceColumn: Total Net Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Company Product Code'
		dataType: string
		lineageTag: ceaf6d2c-324c-4cc0-99c6-8deaa5a69199
		summarizeBy: none
		sourceColumn: Company Product Code

		annotation SummarizationSetBy = Automatic

	column 'Net Units'
		dataType: int64
		formatString: 0
		lineageTag: fe27a5a4-c158-46e3-b55d-2ef67bba663b
		summarizeBy: sum
		sourceColumn: Net Units

		annotation SummarizationSetBy = Automatic

	partition 'S&OP Forecast' = m
		mode: import
		source =
				let
				    Source = SharePoint.Files("https://drmartens0.sharepoint.com/sites/AmericasFPA", [ApiVersion = 15]),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Folder Path] = "https://drmartens0.sharepoint.com/sites/AmericasFPA/Shared Documents/Forecast Uploads/B2B Revenue/S&OP Forecast/")),
				    #"Wholesale LP csv_https://drmartens0 sharepoint com/sites/AmericasFPA/Shared Documents/Forecast Uploads/B2B Revenue/S&OP Forecast/" = #"Filtered Rows"{[Name="Wholesale LP.csv",#"Folder Path"="https://drmartens0.sharepoint.com/sites/AmericasFPA/Shared Documents/Forecast Uploads/B2B Revenue/S&OP Forecast/"]}[Content],
				    #"Imported CSV" = Csv.Document(#"Wholesale LP csv_https://drmartens0 sharepoint com/sites/AmericasFPA/Shared Documents/Forecast Uploads/B2B Revenue/S&OP Forecast/",[Delimiter=",", Columns=16, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Company", type text}, {"Date", type text}, {"Forecast Version", type text}, {"Currency", type text}, {"Customer Acc #", type text}, {"Product Code", type text}, {"Net Units", Int64.Type}, {"Invoiced Units", Int64.Type}, {"Returned Units", Int64.Type}, {"Total Net Value", type number}, {"Invoiced Net Value", type number}, {"Returned Net Value", Int64.Type}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"Company", type text}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type1", "Custom", each if [Product Code] is null then [Company] & "_10082004" else [Company] & "_" & [Product Code]),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom",{{"Custom", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type2",{{"Custom", "Comp_S&OP"}}),
				    #"Added Custom2" = Table.AddColumn(#"Changed Type", "ConvertedDate", each Date.FromText([Date], "en-GB")),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom2",{"Date"}),
				    #"Added Custom1" = Table.AddColumn(#"Removed Columns", "Date", each Date.ToText([ConvertedDate], "yyyyMMdd")),
				    #"Removed Columns1" = Table.RemoveColumns(#"Added Custom1",{"ConvertedDate"}),
				    #"Changed Type12" = Table.TransformColumnTypes(#"Removed Columns1",{{"Date", type text}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type12",{"Date", "Returned Net Value", "Invoiced Net Value", "Total Net Value", "Returned Units", "Invoiced Units", "Net Units", "Product Code", "Customer Acc #", "Currency", "Forecast Version", "Company"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Removed Other Columns", "Custom", each if [Product Code] = "" then [Product Code] & "_10082004" else if [Product Code] = null then [Product Code] & "_10082004" else if [Product Code] = "0" then [Product Code] & "_10082004" else [Company] & "_" & [Product Code]),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Conditional Column",{{"Custom", "Company Product Code"}})
				in
				    #"Renamed Columns1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

