table Availability
	isHidden
	lineageTag: ea8ea58e-bf4b-488e-8dc9-d3dcf9cd4c8c

	column Product_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(32)
		lineageTag: d5b261cb-9762-41a1-86e0-29a274fc8a85
		summarizeBy: none
		sourceColumn: Product_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Product_Class_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(32)
		lineageTag: 56a3ab72-6c31-408b-895d-ed5584620aec
		summarizeBy: none
		sourceColumn: Product_Class_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Size_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(32)
		lineageTag: 6704d1e8-eb9a-4516-8bab-00e0b6eec883
		summarizeBy: none
		sourceColumn: Size_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Warehouse_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(32)
		lineageTag: b1e8a3e0-e700-4055-8319-a2d113013992
		summarizeBy: none
		sourceColumn: Warehouse_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column QTY
		dataType: int64
		isHidden
		sourceProviderType: decimal(38, 0)
		lineageTag: f0069b3b-25dd-4ce5-999b-1c3139def69c
		summarizeBy: sum
		sourceColumn: QTY

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DATE
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: b5ae22f3-fa5d-41a2-9962-bf2f99952c6d
		summarizeBy: none
		sourceColumn: DATE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column SELLINGSTATUS
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 0)
		lineageTag: a110688a-d763-49a7-82dd-b05c72f85035
		summarizeBy: none
		sourceColumn: SELLINGSTATUS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AvailableOnHandUnits
		dataType: int64
		isHidden
		lineageTag: 7dcc3904-e308-4692-b3bc-16a9402e7fa8
		summarizeBy: sum
		sourceColumn: AvailableOnHandUnits

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MAXIMUMONHANDINVENTORYQUANTITY
		dataType: int64
		isHidden
		lineageTag: ee2f6ea0-a46b-49db-9648-45ad8b451000
		summarizeBy: sum
		sourceColumn: MAXIMUMONHANDINVENTORYQUANTITY

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AMOUNT
		dataType: double
		isHidden
		lineageTag: 5988feb9-9731-40e3-91ce-85744abfb7c2
		summarizeBy: sum
		sourceColumn: AMOUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NextDate = DATEADD ( Availability[DATE], 1, DAY )
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: 44101abd-b622-4abd-ade9-15d6387a42de
		summarizeBy: none
		isDataTypeInferred

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ItemCoverage
		dataType: int64
		lineageTag: 4a57e541-ef7a-4f2e-a086-cc44ac5c6d63
		summarizeBy: sum
		sourceColumn: ItemCoverage

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column WH_Channel_Custom
		dataType: string
		lineageTag: ed2ff9e8-31bf-4e12-8f87-4258fd706bf9
		summarizeBy: none
		sourceColumn: WH_Channel_Custom

		annotation SummarizationSetBy = Automatic

	partition 'CY2025 12' = m
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    OPS_BFN_VW_D365_FACT_AVAILABILITY_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365_FACT_AVAILABILITY_QUARTERS",Kind="View"]}[Data],				    
				    PartitionFilter = Table.SelectRows(OPS_BFN_VW_D365_FACT_AVAILABILITY_View, each [DATE] >= #date(2025, 12, 1) and [DATE] < #date(2026, 1, 1))
				in
				    PartitionFilter

	partition 'CY2025 11' = m
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    OPS_BFN_VW_D365_FACT_AVAILABILITY_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365_FACT_AVAILABILITY_QUARTERS",Kind="View"]}[Data],				    
				    PartitionFilter = Table.SelectRows(OPS_BFN_VW_D365_FACT_AVAILABILITY_View, each [DATE] >= #date(2025, 11, 1) and [DATE] < #date(2025, 12, 1))
				in
				    PartitionFilter
	

	partition 'CY2025 10' = m
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    OPS_BFN_VW_D365_FACT_AVAILABILITY_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365_FACT_AVAILABILITY_QUARTERS",Kind="View"]}[Data],				    
				    PartitionFilter = Table.SelectRows(OPS_BFN_VW_D365_FACT_AVAILABILITY_View, each [DATE] >= #date(2025, 10, 1) and [DATE] < #date(2025, 11, 1))
				in
				    PartitionFilter
	

	partition 'CY2025 09' = m
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    OPS_BFN_VW_D365_FACT_AVAILABILITY_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365_FACT_AVAILABILITY_QUARTERS",Kind="View"]}[Data],				    
				    PartitionFilter = Table.SelectRows(OPS_BFN_VW_D365_FACT_AVAILABILITY_View, each [DATE] >= #date(2025, 9, 1) and [DATE] < #date(2025, 10, 1))
				in
				    PartitionFilter		
	

	partition 'CY2025 08' = m
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    OPS_BFN_VW_D365_FACT_AVAILABILITY_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365_FACT_AVAILABILITY_QUARTERS",Kind="View"]}[Data],				    
				    PartitionFilter = Table.SelectRows(OPS_BFN_VW_D365_FACT_AVAILABILITY_View, each [DATE] >= #date(2025, 8, 1) and [DATE] < #date(2025, 9, 1))
				in
				    PartitionFilter	
	

	partition 'CY2025 07' = m
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    OPS_BFN_VW_D365_FACT_AVAILABILITY_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365_FACT_AVAILABILITY_QUARTERS",Kind="View"]}[Data],				    
				    PartitionFilter = Table.SelectRows(OPS_BFN_VW_D365_FACT_AVAILABILITY_View, each [DATE] >= #date(2025, 7, 1) and [DATE] < #date(2025, 8, 1))
				in
				    PartitionFilter	
	

	partition 'CY2025 06' = m
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    OPS_BFN_VW_D365_FACT_AVAILABILITY_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365_FACT_AVAILABILITY_QUARTERS",Kind="View"]}[Data],				    
				    PartitionFilter = Table.SelectRows(OPS_BFN_VW_D365_FACT_AVAILABILITY_View, each [DATE] >= #date(2025, 6, 1) and [DATE] < #date(2025, 7, 1))
				in
				    PartitionFilter	
	

	partition 'CY2025 05' = m
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    OPS_BFN_VW_D365_FACT_AVAILABILITY_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365_FACT_AVAILABILITY_QUARTERS",Kind="View"]}[Data],				    
				    PartitionFilter = Table.SelectRows(OPS_BFN_VW_D365_FACT_AVAILABILITY_View, each [DATE] >= #date(2025, 5, 1) and [DATE] < #date(2025, 6, 1))
				in
				    PartitionFilter	
	

	partition 'CY2025 04' = m
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    OPS_BFN_VW_D365_FACT_AVAILABILITY_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365_FACT_AVAILABILITY_QUARTERS",Kind="View"]}[Data],				    
				    PartitionFilter = Table.SelectRows(OPS_BFN_VW_D365_FACT_AVAILABILITY_View, each [DATE] >= #date(2025, 4, 1) and [DATE] < #date(2025, 5, 1))
				in
				    PartitionFilter	
	

	partition 'CY2025 03' = m
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    OPS_BFN_VW_D365_FACT_AVAILABILITY_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365_FACT_AVAILABILITY_QUARTERS",Kind="View"]}[Data],				    
				    PartitionFilter = Table.SelectRows(OPS_BFN_VW_D365_FACT_AVAILABILITY_View, each [DATE] >= #date(2025, 3, 1) and [DATE] < #date(2025, 4, 1))
				in
				    PartitionFilter		
	

	partition 'CY2025 02' = m
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    OPS_BFN_VW_D365_FACT_AVAILABILITY_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365_FACT_AVAILABILITY_QUARTERS",Kind="View"]}[Data],				    
				    PartitionFilter = Table.SelectRows(OPS_BFN_VW_D365_FACT_AVAILABILITY_View, each [DATE] >= #date(2025, 2, 1) and [DATE] < #date(2025, 3, 1))
				in
				    PartitionFilter	

	partition 'CY2025 01' = m
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    OPS_BFN_VW_D365_FACT_AVAILABILITY_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365_FACT_AVAILABILITY_QUARTERS",Kind="View"]}[Data],				    
				    PartitionFilter = Table.SelectRows(OPS_BFN_VW_D365_FACT_AVAILABILITY_View, each [DATE] >= #date(2025, 1, 1) and [DATE] < #date(2025, 2, 1))
				in
				    PartitionFilter	
	

	partition 'CY2024 12' = m
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    OPS_BFN_VW_D365_FACT_AVAILABILITY_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365_FACT_AVAILABILITY_QUARTERS",Kind="View"]}[Data],				    
				    PartitionFilter = Table.SelectRows(OPS_BFN_VW_D365_FACT_AVAILABILITY_View, each [DATE] >= #date(2024, 12, 1) and [DATE] < #date(2025, 1, 1))
				in
				    PartitionFilter	
	

	partition 'CY2024 11' = m
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    OPS_BFN_VW_D365_FACT_AVAILABILITY_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365_FACT_AVAILABILITY_QUARTERS",Kind="View"]}[Data],				    
				    PartitionFilter = Table.SelectRows(OPS_BFN_VW_D365_FACT_AVAILABILITY_View, each [DATE] >= #date(2024, 11, 1) and [DATE] < #date(2024, 12, 1))
				in
				    PartitionFilter	
	

	partition 'CY2024 10' = m
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    OPS_BFN_VW_D365_FACT_AVAILABILITY_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365_FACT_AVAILABILITY_QUARTERS",Kind="View"]}[Data],				    
				    PartitionFilter = Table.SelectRows(OPS_BFN_VW_D365_FACT_AVAILABILITY_View, each [DATE] >= #date(2024, 10, 1) and [DATE] < #date(2024, 11, 1))
				in
				    PartitionFilter	
	

	partition 'CY2024 09' = m
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    OPS_BFN_VW_D365_FACT_AVAILABILITY_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365_FACT_AVAILABILITY_QUARTERS",Kind="View"]}[Data],				    
				    PartitionFilter = Table.SelectRows(OPS_BFN_VW_D365_FACT_AVAILABILITY_View, each [DATE] >= #date(2024, 9, 1) and [DATE] < #date(2024, 10, 1))
				in
				    PartitionFilter

	partition 'CY2024 08' = m
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    OPS_BFN_VW_D365_FACT_AVAILABILITY_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365_FACT_AVAILABILITY_QUARTERS",Kind="View"]}[Data],				    
				    PartitionFilter = Table.SelectRows(OPS_BFN_VW_D365_FACT_AVAILABILITY_View, each [DATE] >= #date(2024, 8, 1) and [DATE] < #date(2024, 9, 1))
				in
				    PartitionFilter

	partition 'CY2024 07' = m
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    OPS_BFN_VW_D365_FACT_AVAILABILITY_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365_FACT_AVAILABILITY_QUARTERS",Kind="View"]}[Data],					
				    PartitionFilter = Table.SelectRows(OPS_BFN_VW_D365_FACT_AVAILABILITY_View, each [DATE] >= #date(2024, 7, 1) and [DATE] < #date(2024, 8, 1))
				in
				    PartitionFilter

	partition 'CY2024 Q2' = m
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    OPS_BFN_VW_D365_FACT_AVAILABILITY_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365_FACT_AVAILABILITY_QUARTERS",Kind="View"]}[Data],				    
				    PartitionFilter = Table.SelectRows(OPS_BFN_VW_D365_FACT_AVAILABILITY_View, each [DATE] >= #date(2024, 4, 1) and [DATE] < #date(2024, 07, 1))
				in
				    PartitionFilter

	partition 'CY2024 Q1' = m
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    OPS_BFN_VW_D365_FACT_AVAILABILITY_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365_FACT_AVAILABILITY_QUARTERS",Kind="View"]}[Data],				    
				    PartitionFilter = Table.SelectRows(OPS_BFN_VW_D365_FACT_AVAILABILITY_View, each [DATE] >= #date(2024, 1, 1) and [DATE] < #date(2024, 04, 1)),
					#"Filtered Rows" = Table.SelectRows(PartitionFilter, each not List.Contains({"Rewair"},[#"WH_Channel_Custom"]))
				in
				    #"Filtered Rows"
	

	partition 'CY2023 Q4' = m
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    OPS_BFN_VW_D365_FACT_AVAILABILITY_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365_FACT_AVAILABILITY_QUARTERS",Kind="View"]}[Data],				    
				    PartitionFilter = Table.SelectRows(OPS_BFN_VW_D365_FACT_AVAILABILITY_View, each [DATE] >= #date(2023, 10, 1) and [DATE] < #date(2024, 1, 1)),
					#"Filtered Rows" = Table.SelectRows(PartitionFilter, each not List.Contains({"Rewair"},[#"WH_Channel_Custom"]))
				in
				    #"Filtered Rows"

	partition 'CY2023 Q3' = m
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
					OPS_BFN_VW_D365_FACT_AVAILABILITY_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365_FACT_AVAILABILITY_QUARTERS",Kind="View"]}[Data],	
				    PartitionFilter = Table.SelectRows(OPS_BFN_VW_D365_FACT_AVAILABILITY_View, each [DATE] >= #date(2023, 7, 1) and [DATE] < #date(2023, 10, 1)),
					#"Filtered Rows" = Table.SelectRows(PartitionFilter, each not List.Contains({"Rewair"},[#"WH_Channel_Custom"]))
				in
				    #"Filtered Rows"

	partition 'CY2023 Q2' = m
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
					OPS_BFN_VW_D365_FACT_AVAILABILITY_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365_FACT_AVAILABILITY_QUARTERS",Kind="View"]}[Data],	
				    PartitionFilter = Table.SelectRows(OPS_BFN_VW_D365_FACT_AVAILABILITY_View, each [DATE] >= #date(2023, 4, 1) and [DATE] < #date(2023, 07, 1)),
					#"Filtered Rows" = Table.SelectRows(PartitionFilter, each not List.Contains({"Rewair"},[#"WH_Channel_Custom"]))
				in
				    #"Filtered Rows"

	partition 'CY2023 Q1' = m
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    OPS_BFN_VW_D365_FACT_AVAILABILITY_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365_FACT_AVAILABILITY_QUARTERS",Kind="View"]}[Data],				    
				    PartitionFilter = Table.SelectRows(OPS_BFN_VW_D365_FACT_AVAILABILITY_View, each [DATE] >= #date(2023, 1, 1) and [DATE] < #date(2023, 04, 1)),
					#"Filtered Rows" = Table.SelectRows(PartitionFilter, each not List.Contains({"Rewair"},[#"WH_Channel_Custom"]))
				in
				    #"Filtered Rows"
	

	partition 'CY2022 Q4' = m
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    OPS_BFN_VW_D365_FACT_AVAILABILITY_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365_FACT_AVAILABILITY_QUARTERS",Kind="View"]}[Data],				    
				    PartitionFilter = Table.SelectRows(OPS_BFN_VW_D365_FACT_AVAILABILITY_View, each [DATE] >= #date(2022, 10, 1) and [DATE] < #date(2023, 1, 1)),
					#"Filtered Rows" = Table.SelectRows(PartitionFilter, each not List.Contains({"Rewair"},[#"WH_Channel_Custom"]))
				in
				    #"Filtered Rows"

	partition 'CY2022 Q3' = m
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    OPS_BFN_VW_D365_FACT_AVAILABILITY_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365_FACT_AVAILABILITY_QUARTERS",Kind="View"]}[Data],				    
				    PartitionFilter = Table.SelectRows(OPS_BFN_VW_D365_FACT_AVAILABILITY_View, each [DATE] >= #date(2022, 7, 1) and [DATE] < #date(2022, 10, 1)),
					#"Filtered Rows" = Table.SelectRows(PartitionFilter, each not List.Contains({"Rewair"},[#"WH_Channel_Custom"]))
				in
				    #"Filtered Rows"

	partition 'CY2022 Q2' = m
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    OPS_BFN_VW_D365_FACT_AVAILABILITY_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365_FACT_AVAILABILITY_QUARTERS",Kind="View"]}[Data],				    
				    PartitionFilter = Table.SelectRows(OPS_BFN_VW_D365_FACT_AVAILABILITY_View, each [DATE] >= #date(2022, 4, 1) and [DATE] < #date(2022, 07, 1)),
					#"Filtered Rows" = Table.SelectRows(PartitionFilter, each not List.Contains({"Rewair"},[#"WH_Channel_Custom"]))
				in
				    #"Filtered Rows"

	partition 'CY2022 Q1' = m
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    OPS_BFN_VW_D365_FACT_AVAILABILITY_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365_FACT_AVAILABILITY_QUARTERS",Kind="View"]}[Data],				    
				    PartitionFilter = Table.SelectRows(OPS_BFN_VW_D365_FACT_AVAILABILITY_View, each [DATE] >= #date(2022, 1, 1) and [DATE] < #date(2022, 04, 1)),
					#"Filtered Rows" = Table.SelectRows(PartitionFilter, each not List.Contains({"Rewair"},[#"WH_Channel_Custom"]))
				in
				    #"Filtered Rows"

	partition 'CY2021 Q4' = m
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    OPS_BFN_VW_D365_FACT_AVAILABILITY_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365_FACT_AVAILABILITY_QUARTERS",Kind="View"]}[Data],				    
				    PartitionFilter = Table.SelectRows(OPS_BFN_VW_D365_FACT_AVAILABILITY_View, each [DATE] >= #date(2021, 10, 1) and [DATE] < #date(2022, 1, 1)),
					#"Filtered Rows" = Table.SelectRows(PartitionFilter, each not List.Contains({"Rewair"},[#"WH_Channel_Custom"]))
				in
				    #"Filtered Rows"

	partition 'CY2021 Q3' = m
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    OPS_BFN_VW_D365_FACT_AVAILABILITY_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365_FACT_AVAILABILITY_QUARTERS",Kind="View"]}[Data],				    
				    PartitionFilter = Table.SelectRows(OPS_BFN_VW_D365_FACT_AVAILABILITY_View, each [DATE] >= #date(2021, 7, 1) and [DATE] < #date(2021, 10, 1)),
					#"Filtered Rows" = Table.SelectRows(PartitionFilter, each not List.Contains({"Rewair"},[#"WH_Channel_Custom"]))
				in
				    #"Filtered Rows"


	changedProperty = IsHidden

	annotation PBI_ResultType = Table

