table Products
	lineageTag: 881320d1-8b10-458e-8da9-bfffaac311f9

	column Product_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(32)
		displayFolder: zz_Misc
		lineageTag: 981d5d4a-ba33-4846-ae11-33d9e4cae0b8
		summarizeBy: none
		sourceColumn: Product_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Current Product Class Sort'
		dataType: double
		isHidden
		sourceProviderType: decimal(2, 0)
		displayFolder: zz_Misc
		lineageTag: ff8b0b6f-7172-4fb7-8dae-7609a5f0a23a
		summarizeBy: none
		sourceColumn: Current Product Class Sort

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Current Selling Status Sort'
		dataType: double
		isHidden
		sourceProviderType: decimal(1, 0)
		displayFolder: zz_Misc
		lineageTag: 2f00b82c-cf61-4eb2-9de3-ee88a1ab1660
		summarizeBy: none
		sourceColumn: Current Selling Status Sort

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ProductSegment
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		displayFolder: zz_Misc
		lineageTag: f1b14a6e-b7f1-4bb3-aaf7-8ffd98e12673
		summarizeBy: none
		sourceColumn: ProductSegment

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Current Selling Price'
		dataType: double
		formatString: " #,##0.00"
		sourceProviderType: decimal(32, 6)
		displayFolder: 1. Prices
		lineageTag: a9227dde-3b03-46ec-aa60-35ec65402b95
		summarizeBy: none
		sourceColumn: Current Selling Price

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Current Selling Price Currency'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: 1. Prices
		lineageTag: 4a9ebb71-32e4-43f1-9fc8-f05e51de4875
		summarizeBy: none
		sourceColumn: Current Selling Price Currency

		annotation SummarizationSetBy = Automatic

	column 'Full Selling Price'
		dataType: double
		formatString: #,##0.00
		sourceProviderType: decimal(32, 6)
		displayFolder: 1. Prices
		lineageTag: d4fca1a3-b4ac-4994-8056-2723acecd47d
		summarizeBy: none
		sourceColumn: Full Selling Price

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Full Selling Price Currency'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: 1. Prices
		lineageTag: 2c229d0e-bb82-41bc-8340-8686bc9ff37f
		summarizeBy: none
		sourceColumn: Full Selling Price Currency

		annotation SummarizationSetBy = Automatic

	column 'Discounted Price Product?'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		displayFolder: 1. Prices
		lineageTag: a105ce82-c8d2-4a15-8fa5-2b5f12feb07e
		summarizeBy: none
		sourceColumn: Discounted Price Product?

		annotation SummarizationSetBy = Automatic

	column 'IPS D2C Class'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: Merchandising
		lineageTag: 7c2824d1-f8b5-4f3a-b4af-5680c0115d6a
		summarizeBy: none
		sourceColumn: IPS D2C Class

		annotation SummarizationSetBy = Automatic

	column 'Product Code'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 30239442-af3f-4e87-a85e-83c2730b75ff
		summarizeBy: none
		sourceColumn: Product Code

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 60b4ca87-d2af-4d50-8c19-e6e10f050552
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column Last
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 09a1e48d-f549-4193-823e-16055fe5e820
		summarizeBy: none
		sourceColumn: Last

		annotation SummarizationSetBy = Automatic

	column Sole
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 9ba864b3-40d4-4ff9-a9f5-9a4a3706e1d5
		summarizeBy: none
		sourceColumn: Sole

		annotation SummarizationSetBy = Automatic

	column 'Sourcing Category'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 00ff8ec2-2e1b-4c71-9797-a2af2b0332ba
		summarizeBy: none
		sourceColumn: Sourcing Category

		annotation SummarizationSetBy = Automatic

	column 'Product Type'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: c7663aaf-b983-4db8-a0d7-27eb42773104
		summarizeBy: none
		sourceColumn: Product Type

		annotation SummarizationSetBy = Automatic

	column 'Style Colour Material'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: d023e22b-29b2-4d9e-a258-81bfa62770b3
		summarizeBy: none
		sourceColumn: Style Colour Material

		annotation SummarizationSetBy = Automatic

	column 'Product General'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: dd660177-8533-4f43-8f42-3ab98bb1e2ae
		summarizeBy: none
		sourceColumn: Product General

		annotation SummarizationSetBy = Automatic

	column 'Product Collection'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 4f260c55-42e2-4b8b-820e-e1b39e9f1d14
		summarizeBy: none
		sourceColumn: Product Collection

		annotation SummarizationSetBy = Automatic

	column 'Product Sub-Type'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: eabf3b10-4f92-4012-8057-6a8683955357
		summarizeBy: none
		sourceColumn: Product Sub-Type

		annotation SummarizationSetBy = Automatic

	column 'Product Category'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 193b8c06-60bf-4eda-ac33-c646e1041c1f
		summarizeBy: none
		sourceColumn: Product Category

		annotation SummarizationSetBy = Automatic

	column Colour
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 1b96243a-c137-44ac-be6b-94d58f80d572
		summarizeBy: none
		sourceColumn: Colour

		annotation SummarizationSetBy = Automatic

	column Material
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 0f9ebd24-3019-4714-9897-f2ea7046c42d
		summarizeBy: none
		sourceColumn: Material

		annotation SummarizationSetBy = Automatic

	column 'Short Code'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 0fbbec59-c630-4ada-9bbc-3e4fbd9e0335
		summarizeBy: none
		sourceColumn: Short Code

		annotation SummarizationSetBy = Automatic

	column 'Launch To Retail'
		dataType: dateTime
		formatString: Short Date
		sourceProviderType: datetime2
		lineageTag: 4eea5945-0100-4423-81a4-06feb79ddc21
		summarizeBy: none
		sourceColumn: Launch To Retail

		annotation SummarizationSetBy = Automatic

	column 'Launch Season'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 78f48b00-a3ec-4012-9c7c-08db49f04c8c
		summarizeBy: none
		sourceColumn: Launch Season

		annotation SummarizationSetBy = Automatic

	column 'Product URL Icon'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: d6396059-f8c0-4422-941a-cbeb36f4b39e
		summarizeBy: none
		sourceColumn: Product URL Icon

		annotation SummarizationSetBy = Automatic

	column 'Product URL Image'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: f69c6be3-730d-4eb1-a2aa-ff130c38714f
		summarizeBy: none
		sourceColumn: Product URL Image

		annotation SummarizationSetBy = Automatic

	column 'Style Name'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: a9000be3-0fb1-4370-b56d-c8d24aded36e
		summarizeBy: none
		sourceColumn: Style Name

		annotation SummarizationSetBy = Automatic

	column 'Current Selling Status'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: ac47b498-21af-4744-9d52-a8cceb2d49c2
		summarizeBy: none
		sourceColumn: Current Selling Status

		annotation SummarizationSetBy = Automatic

	column 'Product Major'
		dataType: string
		sourceProviderType: nvarchar(12)
		lineageTag: 93bd7197-cb27-4aed-b68c-09348b1d5c04
		summarizeBy: none
		sourceColumn: Product Major

		annotation SummarizationSetBy = Automatic

	column Collaboration
		dataType: double
		sourceProviderType: decimal(1, 0)
		lineageTag: c882640a-dc2a-4be7-9291-b1f5167ef903
		summarizeBy: none
		sourceColumn: Collaboration

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'D2C Product Definition'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 9dfbac0c-f538-41fd-854d-47bf7af84e90
		summarizeBy: none
		sourceColumn: D2C Product Definition

		annotation SummarizationSetBy = Automatic

	column 'Current Product Class'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 88367852-515a-42e0-bccf-ae75996a08a1
		summarizeBy: none
		sourceColumn: Current Product Class

		annotation SummarizationSetBy = Automatic

	column 'Default Vendor Name'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 79af5e1c-28b2-441d-b900-9debe8dd2d49
		summarizeBy: none
		sourceColumn: Default Vendor Name

		annotation SummarizationSetBy = Automatic

	column 'Default Vendor Country'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 050079e6-9eb1-4195-87cb-2b2051ab9539
		summarizeBy: none
		sourceColumn: Default Vendor Country

		annotation SummarizationSetBy = Automatic

	column 'Tariff Code'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 1fffc8fc-cda2-4602-b69a-410c4c26490e
		summarizeBy: none
		sourceColumn: Tariff Code

		annotation SummarizationSetBy = Automatic

	column 'Product Age Group'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: bff6260f-38b6-44dd-93fe-c538c06e52bc
		summarizeBy: none
		sourceColumn: Product Age Group

		annotation SummarizationSetBy = Automatic

	column 'Last PO Purchase Price'
		dataType: double
		sourceProviderType: decimal(37, 6)
		lineageTag: 36e78300-dc80-41ea-8b62-1dffbbc15a50
		summarizeBy: sum
		sourceColumn: Last PO Purchase Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Last PO Purchase Price (GBP)'
		dataType: double
		sourceProviderType: decimal(38, 2)
		lineageTag: 3d0ee3ac-781b-4a4c-a593-7228638d5c14
		summarizeBy: sum
		sourceColumn: Last PO Purchase Price (GBP)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Last PO Purchase Date'
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 1a988d3f-ae86-4e0d-9bdd-33fed7d00f99
		summarizeBy: none
		sourceColumn: Last PO Purchase Date

		annotation SummarizationSetBy = Automatic

	column 'Last PO Currency'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 1960385e-3f71-4a82-94fe-64a8a447b2af
		summarizeBy: none
		sourceColumn: Last PO Currency

		annotation SummarizationSetBy = Automatic

	column 'Company ID'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: ffac333e-48cd-4d10-81b9-fd27905ba550
		summarizeBy: none
		sourceColumn: Company ID

		annotation SummarizationSetBy = Automatic

	column 'Product Segment Category'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 545c447b-61ad-47a5-a586-1cdd2a3b8a5b
		summarizeBy: none
		sourceColumn: Product Segment Category

		annotation SummarizationSetBy = Automatic

	column 'Leather Code'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 1bdba15e-0f6f-44c7-9e8c-34df153ca791
		summarizeBy: none
		sourceColumn: Leather Code

		annotation SummarizationSetBy = Automatic

	column 'Latest Season'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: caf8c834-1723-4053-85c2-73424fce674b
		summarizeBy: none
		sourceColumn: Latest Season

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 428e88c3-271f-40e0-8bd6-2bd5bb0040f1
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Welted?
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 47ce19ac-9f13-4344-a6c4-9e430e0b56fa
		summarizeBy: none
		sourceColumn: Welted?

		annotation SummarizationSetBy = Automatic

	column 'Finance Category'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 6c636eec-7ec4-4869-8a6a-00792cd4895f
		summarizeBy: none
		sourceColumn: Finance Category

		annotation SummarizationSetBy = Automatic

	column 'Finance Sub Category'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 07d44633-7f1c-4726-9813-0d1c0e6df8f3
		summarizeBy: none
		sourceColumn: Finance Sub Category

		annotation SummarizationSetBy = Automatic

	column 'Item Model Group'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: f742a107-f4ef-4893-8a37-7c84ef0d7d66
		summarizeBy: none
		sourceColumn: Item Model Group

		annotation SummarizationSetBy = Automatic

	column 'Current Product Class Code'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 72f45f77-b1cc-4c74-b831-252a04bfde16
		summarizeBy: none
		sourceColumn: Current Product Class Code

		annotation SummarizationSetBy = Automatic

	column 'VAT Application'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 97c45574-533d-483d-8cab-c8b5984f6e27
		summarizeBy: none
		sourceColumn: VAT Application

		annotation SummarizationSetBy = Automatic

	column 'D2C Product Story'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: bff0132c-4321-451c-b0f5-8ee646ef3a7e
		summarizeBy: none
		sourceColumn: D2C Product Story

		annotation SummarizationSetBy = Automatic

	column 'eCom Product Category'
		dataType: string
		sourceProviderType: nvarchar(15)
		lineageTag: db8f9f08-7866-496d-a2ae-8971a900423b
		summarizeBy: none
		sourceColumn: eCom Product Category

		annotation SummarizationSetBy = Automatic

	column 'Product Search'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: ca144a4f-941b-4cf6-b8fd-6858d9cc1c94
		summarizeBy: none
		sourceColumn: Product Search

		annotation SummarizationSetBy = Automatic

	column 'Product Business Units'
		dataType: string
		sourceProviderType: nvarchar(22)
		lineageTag: 82433431-e503-4016-bed6-e3b66aaa2068
		summarizeBy: none
		sourceColumn: Product Business Units

		annotation SummarizationSetBy = Automatic

	column 'TBD vs Continuity/Carry Over'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 55758893-62b3-4e58-96d5-0b5d712d9b01
		summarizeBy: none
		sourceColumn: TBD vs Continuity/Carry Over

		annotation SummarizationSetBy = Automatic

	column Active/Obsolete
		dataType: string
		sourceProviderType: nvarchar(8)
		lineageTag: 63f456e2-20a5-4b88-9591-2123d5348108
		summarizeBy: none
		sourceColumn: Active/Obsolete

		annotation SummarizationSetBy = Automatic

	column 'Launch Month'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: ef4b6f1c-6b61-4945-a61d-e0fba309bb26
		summarizeBy: none
		sourceColumn: Launch Month

		annotation SummarizationSetBy = Automatic

	column 'Construction Desc'
		dataType: string
		lineageTag: cbf354a3-b7b7-440f-bea4-dd7d529a6b20
		summarizeBy: none
		sourceColumn: Construction Desc

		annotation SummarizationSetBy = Automatic

	partition Products = m
		mode: import
		source =
				let
					Source = Snowflake.Databases(Datasource_Server, Datasource_Warehouse),
					PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
					BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
					BFN_Datatable_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_DIMPRODUCT",Kind="View"]}[Data],
					#"Filtered Rows" = Table.SelectRows(BFN_Datatable_View, each ([Product_Key] <> 0)),
					#"Kept First Rows" = Table.FirstN(#"Filtered Rows",NumberOfRows),
					ParameterFilter = if NumberOfRows > 0 then #"Kept First Rows" else #"Filtered Rows"
				in
					ParameterFilter

	annotation PBI_ResultType = Table

