table 'Sales Order Type'
	isHidden
	lineageTag: cb527b67-9fcc-4df9-a1ae-86e112e63370

	column DESCRIPTION
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: a3644465-8b40-4110-9ef3-e01c2652d274
		summarizeBy: none
		sourceColumn: DESCRIPTION

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ORDERTYPEID
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: 43854a72-be23-45a2-9243-9041905c846f
		summarizeBy: none
		sourceColumn: ORDERTYPEID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Sales Order Type' = m
		mode: import
		source = ```
				let
					Source = Snowflake.Databases(Datasource_Server, Datasource_Warehouse),
					PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
					BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
					BFN_Datatable_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365DIMSALESORDERTYPE",Kind="View"]}[Data],
					#"Filtered Rows" = Table.SelectRows(BFN_Datatable_View, each [ORDERTYPEID] <> null and [ORDERTYPEID] <> ""),
					#"Kept First Rows" = Table.FirstN(#"Filtered Rows" ,NumberOfRows),
					ParameterFilter = if NumberOfRows > 0 then #"Kept First Rows" else #"Filtered Rows" 
				in
					ParameterFilter
				```

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

