table Warehouse
	lineageTag: e36f5888-5437-4c8e-b209-de4651587000

	column Warehouse_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: 49658cb0-5e12-4db6-8367-f8c82ecdff6b
		summarizeBy: none
		sourceColumn: Warehouse_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Is Retail Warehouse?'
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 5)
		lineageTag: 00378335-1e46-4be7-b20d-17a0a8412e5e
		summarizeBy: none
		sourceColumn: Is Retail Warehouse?

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FinancialChannel
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: c8958694-fbb2-4dba-bd49-2fa4851a57c2
		summarizeBy: none
		sourceColumn: FinancialChannel

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Warehouse Address Region ID'
		dataType: string
		lineageTag: cc853d2a-99c9-43ee-af70-8d9edde57c4d
		summarizeBy: none
		sourceColumn: Warehouse Address Region ID

		annotation SummarizationSetBy = Automatic

	column Company
		dataType: string
		lineageTag: df5f617c-9f78-4f4f-ae8c-ac0f7282dea7
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = Automatic

	column 'Warehouse Name'
		dataType: string
		lineageTag: 9e7e4fbb-ef87-4a0e-85de-246fb9c349a3
		summarizeBy: none
		sourceColumn: Warehouse Name

		annotation SummarizationSetBy = Automatic

	column 'Warehouse ID'
		dataType: string
		lineageTag: bd80f57c-a760-403b-b4be-e99bbd842180
		summarizeBy: none
		sourceColumn: Warehouse ID

		annotation SummarizationSetBy = Automatic

	column 'Warehouse Group'
		dataType: string
		lineageTag: 3388f2c0-7928-4add-b9ee-8ebe1bd4ae41
		summarizeBy: none
		sourceColumn: Warehouse Group

		annotation SummarizationSetBy = Automatic

	column 'Warehouse Sub-Group'
		dataType: string
		lineageTag: b91becac-4f40-4f27-be80-80a08fc0eb87
		summarizeBy: none
		sourceColumn: Warehouse Sub-Group

		annotation SummarizationSetBy = Automatic

	column 'Warehouse Channel'
		dataType: string
		lineageTag: 2ab73285-aabf-43ca-91b6-9c95e1d1679d
		summarizeBy: none
		sourceColumn: Warehouse Channel

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Warehouse Region'
		dataType: string
		lineageTag: 3b4788ff-f9bd-4bc9-988d-d316da598b1c
		summarizeBy: none
		sourceColumn: Warehouse Region

		annotation SummarizationSetBy = Automatic

	column 'Warehouse Sub-Region'
		dataType: string
		lineageTag: 859f5849-969b-4b30-9eaf-94e60d05435c
		summarizeBy: none
		sourceColumn: Warehouse Sub-Region

		annotation SummarizationSetBy = Automatic

	partition Warehouse = m
		mode: import
		source =
				let
					Source = Snowflake.Databases(Datasource_Server, Datasource_Warehouse),
					PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
					BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
					BFN_Datatable_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365DIMWAREHOUSE",Kind="View"]}[Data],
					#"Kept First Rows" = Table.FirstN(BFN_Datatable_View,NumberOfRows),
					ParameterFilter = if NumberOfRows > 0 then #"Kept First Rows" else BFN_Datatable_View,
				    #"Renamed Columns" = Table.RenameColumns(ParameterFilter,{{"WAREHOUSEID", "Warehouse ID"}, {"WAREHOUSENAME", "Warehouse Name"}, {"CompanyRegion", "Warehouse Region"}, {"WH_Group", "Warehouse Group"}, {"WH_Sub-Group", "Warehouse Sub-Group"}, {"WH_Channel", "Warehouse Channel"}, {"WarehouseSubRegion", "Warehouse Sub-Region"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"Parent Store ID", "Site ID"})
				in
					#"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

