table 'Allocation Details'
	lineageTag: 21846bb7-a96c-4bf8-8761-cb1594819092

	column ALLOCATIONQTY
		dataType: int64
		isHidden
		sourceProviderType: decimal(38, 0)
		lineageTag: f1bdf359-bdc3-44c2-8cd9-ea17e3d05919
		summarizeBy: sum
		sourceColumn: ALLOCATIONQTY

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column INVENTTRANSID
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: a987085e-f028-4700-ac93-8dab77ca48bd
		summarizeBy: none
		sourceColumn: INVENTTRANSID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Date_Key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d2ed8dff-e8f9-4726-84a4-93d70bcd0a7b
		summarizeBy: none
		sourceColumn: Date_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Allocation Date'
		dataType: dateTime
		formatString: Short Date
		sourceProviderType: date
		lineageTag: b21c88a3-05fc-44af-a5f2-3e44eda7474b
		summarizeBy: none
		sourceColumn: Allocation Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Allocation Type'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: d65699ba-4edc-43df-90a8-763a6286a3f0
		summarizeBy: none
		sourceColumn: Allocation Type

		annotation SummarizationSetBy = Automatic

	partition 'Allocation Details' = m
		mode: import
		source =
				let
					Source = Snowflake.Databases(Datasource_Server, Datasource_Warehouse),
					PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
					BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
					BFN_Datatable_View = BFN_PRESENTATION_Schema{[Name="OPS_BFN_VW_D365DMRFSBIMRESVALLOCATIONDETAILS",Kind="View"]}[Data],
					#"Kept First Rows" = Table.FirstN(BFN_Datatable_View,NumberOfRows),
					ParameterFilter = if NumberOfRows > 0 then #"Kept First Rows" else BFN_Datatable_View,
				    #"Changed Type" = Table.TransformColumnTypes(ParameterFilter,{{"Date_Key", Int64.Type}})
				in
					#"Changed Type"

	annotation PBI_ResultType = Table

