table 'Retail Store'
	lineageTag: e9d19dbe-4bdb-4207-8287-b511a7baccc3

	column STOREID
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: f023525f-065f-470b-8cbb-b2423d992990
		summarizeBy: none
		sourceColumn: STOREID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Store Name'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: a1cc3526-52e8-4f80-85e5-6661c0b2b636
		summarizeBy: none
		sourceColumn: Store Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Location ID'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 2c5287bf-6432-467f-aef3-a0877378da1b
		summarizeBy: none
		sourceColumn: Location ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Overall Store Grade'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 64f398b6-561e-490b-b38c-a289901aad34
		summarizeBy: none
		sourceColumn: Overall Store Grade

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Regional Channel'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 2965bc4c-d69c-420d-b2fe-19d4525ad5cf
		summarizeBy: none
		sourceColumn: Regional Channel

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Store Location'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 8c2cbab4-e272-421c-9c61-79b0b766e726
		summarizeBy: none
		sourceColumn: Store Location

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Store Status'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 6deb1c9c-d803-4ee1-8518-9f67181f1997
		summarizeBy: none
		sourceColumn: Store Status

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: a0a1b968-8a67-445c-8dae-a4974dad3493
		summarizeBy: none
		sourceColumn: City

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 89d4e42a-4797-49f9-887a-e9878870d372
		summarizeBy: none
		sourceColumn: Country

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 1f1db8e2-eb84-46e4-9fb3-0f8e528021d8
		summarizeBy: none
		sourceColumn: Area

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Opening Date'
		dataType: dateTime
		formatString: Short Date
		sourceProviderType: date
		lineageTag: b0108b8e-f2ba-4567-ac33-8050c95bb27b
		summarizeBy: none
		sourceColumn: Opening Date

		changedProperty = IsHidden

		changedProperty = FormatString

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Closing Date'
		dataType: dateTime
		formatString: Short Date
		sourceProviderType: date
		lineageTag: c5df05c6-4184-45b8-90ab-4b435d3e7bad
		summarizeBy: none
		sourceColumn: Closing Date

		changedProperty = IsHidden

		changedProperty = DataType

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

	column 'Gross Sq ft'
		dataType: decimal
		formatString: #,0
		sourceProviderType: double
		lineageTag: 9cae6d41-e15d-41e6-8d68-152f9ed4d4ee
		summarizeBy: none
		sourceColumn: Gross Sq ft

		changedProperty = IsHidden

		changedProperty = DataType

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Gross Sqm'
		dataType: int64
		formatString: #,0
		sourceProviderType: double
		lineageTag: a779b2fb-a8c1-47cb-91ad-2e9f2512483c
		summarizeBy: none
		sourceColumn: Gross Sqm

		changedProperty = IsHidden

		changedProperty = FormatString

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Linear Ft'
		dataType: double
		formatString: 0
		sourceProviderType: double
		lineageTag: c16aa9eb-f5da-4e9a-bc17-3a143281dd9b
		summarizeBy: none
		sourceColumn: Linear Ft

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

	column Latitude
		dataType: double
		formatString: 0
		sourceProviderType: double
		lineageTag: 0ec15332-66e1-4752-ac81-7433ffe99c82
		summarizeBy: none
		sourceColumn: Latitude

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

	column Longtitude
		dataType: double
		formatString: 0
		sourceProviderType: double
		lineageTag: b13838b2-7332-4715-9c08-8b63dc9a6dba
		summarizeBy: none
		sourceColumn: Longtitude

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

	column 'Footwear SKU Capacity'
		dataType: double
		sourceProviderType: decimal(38, 0)
		lineageTag: 780c3b0e-24a1-4442-b382-34d901aef003
		summarizeBy: none
		sourceColumn: Footwear SKU Capacity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Price Profile'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 4622a864-b967-4143-836c-a014aef54032
		summarizeBy: none
		sourceColumn: Price Profile

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Regional Manager'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: b7921622-3273-40ca-a857-4f9e8ec739f2
		summarizeBy: none
		sourceColumn: Regional Manager

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Tourist Level'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 54383865-1d68-454d-b2d6-347908649228
		summarizeBy: none
		sourceColumn: Tourist Level

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Store Image'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 84aa0ec0-527e-4817-bf21-c3e05a4aff9f
		summarizeBy: none
		sourceColumn: Store Image

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CostCentre_Key
		dataType: string
		isHidden
		sourceProviderType: decimal(38, 0)
		lineageTag: 8ace27d1-e065-45ab-96b9-b8ee99adfe97
		summarizeBy: none
		sourceColumn: CostCentre_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Retail Store-645ba6a9-6f1f-420c-a1e8-e49195dbfade' = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    VW_BFN_D365DIMRETAILSTORE_View = BFN_PRESENTATION_Schema{[Name="VW_BFN_D365DIMRETAILSTORE",Kind="View"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(VW_BFN_D365DIMRETAILSTORE_View, each [CostCentre_Key] <> null and [CostCentre_Key] <> "")
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

