table 'Display Currency'
	lineageTag: 72005c83-5846-4dc1-b1bf-c8616e15eb34

	column 'Currency Code'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 321f5c60-5312-45b9-8691-4c35596e9d66
		summarizeBy: none
		sourceColumn: Currency Code

		annotation SummarizationSetBy = Automatic

	column 'Currency Name'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 51ea5a52-f671-4384-bf03-44ef62375d93
		summarizeBy: none
		sourceColumn: Currency Name

		annotation SummarizationSetBy = Automatic

	column 'Currency Symbol'
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: e01ae424-9711-4a08-a35b-b3f3a7532d89
		summarizeBy: none
		sourceColumn: Currency Symbol

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column XRMultiplier =
			IF (
						    'Display Currency'[Currency Code] = "GBP",
						    1,
						    LOOKUPVALUE (
						        'Exchange Rates'[RATE],
						        'Exchange Rates'[FROMCURRENCY], "GBP",
						        'Exchange Rates'[RATETYPENAME], "BUDGET",
						        'Exchange Rates'[TOCURRENCY], 'Display Currency'[Currency Code]
						    )
						)
		isHidden
		lineageTag: 680a2015-a16d-4c2d-a380-3891affebad9
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NAME
		dataType: string
		isHidden
		lineageTag: 645674da-fa5e-42c5-b007-cb95cc353f30
		summarizeBy: none
		sourceColumn: NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Display Currency' = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server, Datasource_Warehouse),
					#"Extra Currencies" = #table({"NAME", "Currency Code", "Currency Name", "Currency Symbol"}, {{ "Constant (GBP)", "GBP_CONS", "Constant (GBP)", "£"},{ "Closing (GBP)", "GBP_CLOS", "Closing (GBP)", "£"},{ "Transaction Currency", "TRANS", "Transaction Currency", ""}}),
					PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    BFN_Datatable_View = BFN_PRESENTATION_Schema{[Name="SRC_BFN_VW_D365DIMCURRENCY",Kind="View"]}[Data],
					#"Filtered Rows" = Table.SelectRows(BFN_Datatable_View, each List.Contains({"Canadian Dollar", "Euro", "Hong Kong Dollar", "Pound Sterling", "Singapore Dollar", "US Dollar", "Won", "Yen"},[Currency Name])),
					#"Appended Query" = Table.Combine({#"Filtered Rows", #"Extra Currencies"})
				in
					#"Appended Query"

	annotation PBI_ResultType = Table

