table 'Pack One Carton Dimensions'
	lineageTag: b317e347-8407-404e-b9ff-5f29b5083a21

	column 'Sscc Number'
		dataType: string
		lineageTag: da89cf63-a018-4025-9c32-2f46be6a076b
		summarizeBy: none
		sourceColumn: Sscc Number

		annotation SummarizationSetBy = Automatic

	column 'Order Number'
		dataType: string
		lineageTag: f011c597-2ecc-43fc-81f4-008d725e2b7d
		summarizeBy: none
		sourceColumn: Order Number

		annotation SummarizationSetBy = Automatic

	column 'Pack Number'
		dataType: int64
		lineageTag: c6e6a0b4-e69d-4ccc-887a-3a2169644418
		summarizeBy: sum
		sourceColumn: Pack Number

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Id'
		dataType: double
		lineageTag: a2fccd10-e288-428d-944c-d1b0ebd3c893
		summarizeBy: count
		sourceColumn: Item Id

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PPMProduct_Key
		dataType: string
		isHidden
		lineageTag: 03a0eb70-449e-4b4b-a9b4-4e752ce993cc
		summarizeBy: none
		sourceColumn: PPMProduct_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Size_Key
		dataType: string
		isHidden
		lineageTag: 64b97aef-1234-4c07-abca-7dd64fce4732
		summarizeBy: none
		sourceColumn: Size_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Pack Item Seq'
		dataType: double
		lineageTag: ce07f28a-8f67-4efd-93ec-6454acf42561
		summarizeBy: sum
		sourceColumn: Pack Item Seq

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Gross Weight'
		dataType: double
		lineageTag: e36dc162-ff60-4fd9-a8d9-d8f8cf463744
		summarizeBy: sum
		sourceColumn: Gross Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Net Weight'
		dataType: double
		lineageTag: f573ac03-4687-4504-85d5-7a56b34eefef
		summarizeBy: sum
		sourceColumn: Net Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Net Net Weight'
		dataType: double
		lineageTag: aed03a08-1786-457d-952d-9bee3caa8568
		summarizeBy: sum
		sourceColumn: Net Net Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Weight Unit'
		dataType: string
		lineageTag: 1443f06e-18c0-430f-9ea8-a6fcfa62c9ab
		summarizeBy: none
		sourceColumn: Weight Unit

		annotation SummarizationSetBy = Automatic

	column Length
		dataType: double
		lineageTag: f0538bb2-b65a-42ea-88e9-6c20c2994fcd
		summarizeBy: sum
		sourceColumn: Length

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Height
		dataType: double
		lineageTag: ee53f817-f6a9-4374-9fcd-3704729f95e7
		summarizeBy: sum
		sourceColumn: Height

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Width
		dataType: double
		lineageTag: 0f2bb2db-cb8d-4faa-b488-4e39b4b1b101
		summarizeBy: sum
		sourceColumn: Width

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LwhUnit
		dataType: string
		lineageTag: 8f73ec7b-050b-42e3-8175-83d2c2d20a57
		summarizeBy: none
		sourceColumn: LwhUnit

		annotation SummarizationSetBy = Automatic

	column PackedQty
		dataType: int64
		formatString: #,0
		lineageTag: f3c719c4-a106-4892-9833-ca8888e2f0c1
		summarizeBy: sum
		sourceColumn: PackedQty

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Packed Date Key'
		dataType: int64
		isHidden
		lineageTag: 1fa98ac4-ab3a-485d-ad8f-d00b3c3d9d1e
		summarizeBy: none
		sourceColumn: Packed Date Key

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Pack One Carton Dimensions' = m
		mode: import
		source =
				let
					Source = Snowflake.Databases(Datasource_Server, Datasource_Warehouse),
					PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
					BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
					BFN_Datatable_View = BFN_PRESENTATION_Schema{[Name="SRC_BFN_VW_PPMPACKONECARTONDIMENSIONS",Kind="View"]}[Data],
					#"Kept First Rows" = Table.FirstN(BFN_Datatable_View,NumberOfRows),
					ParameterFilter = if NumberOfRows > 0 then #"Kept First Rows" else BFN_Datatable_View,
				    #"Renamed Columns" = Table.RenameColumns(ParameterFilter,{{"PackedDateKey", "Packed Date Key"}})
				in
					#"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

