table 'Adjustments CoGS'
	isHidden
	lineageTag: 8ae11191-1f7f-4819-bfb5-a9048123a9e0

	column 'Amount at Constant Rate'
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 2)
		displayFolder: zz_Values
		lineageTag: 866bc307-0e71-4edc-8b49-366b6e3a9a0d
		summarizeBy: none
		sourceColumn: Amount at Constant Rate

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AccountingDate_Key
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: nvarchar(16777216)
		displayFolder: zz_Keys
		lineageTag: bea821b5-6f52-4447-bdc1-d0c0d52be399
		summarizeBy: none
		sourceColumn: AccountingDate_Key

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Company_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(32)
		displayFolder: zz_Keys
		lineageTag: 4ef12e82-e830-4c8d-aeae-4092d2b4f43b
		summarizeBy: none
		sourceColumn: Company_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Channel_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(32)
		displayFolder: zz_Keys
		lineageTag: 3d98891f-9ed9-45a4-bc72-433a09d467e8
		summarizeBy: none
		sourceColumn: Channel_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Adjustments CoGS-f315aa51-e2d7-455c-92f8-40439c06de00' = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    D2C_BFN_VW_D365FACTASE_ADJUSTMENT_COGS_View = BFN_PRESENTATION_Schema{[Name="D2C_BFN_VW_D365FACTASE_ADJUSTMENT_COGS",Kind="View"]}[Data],
				    #"Filtered Rows1"   = Table.SelectRows(D2C_BFN_VW_D365FACTASE_ADJUSTMENT_COGS_View, each [TransactionTypeDesc] <> "Sales" and List.Contains({101,102},[CHANNEL]) and [MAINACCOUNTID] >= "50001" and [MAINACCOUNTID] <= "50059"),
				    #"Selected Columns" = Table.SelectColumns(#"Filtered Rows1",{"AccountingDate_Key", "Channel_Key", "Company_Key", "Amount at Constant Rate"}),
				    #"Kept First Rows" = Table.FirstN(#"Selected Columns",NumberOfRows),
				    ParameterFilter = if NumberOfRows > 0 then #"Kept First Rows" else #"Selected Columns"
				in
				    ParameterFilter

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

