table 'GA Demand FC'
	isHidden
	lineageTag: ce68c573-6c70-4189-ac54-b09943456c38

	column Date
		dataType: dateTime
		isHidden
		formatString: Short Date
		sourceProviderType: datetime2
		lineageTag: 1f6c2e84-36fa-4b99-a67f-2f7114bc68bf
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Forecast Version'
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: 30a4ac2b-25b6-4cdd-9ceb-ed39efaf26c7
		summarizeBy: none
		sourceColumn: Forecast Version

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Website
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: cf1026a0-2ac9-43f8-bb6d-fe3acd360af6
		summarizeBy: none
		sourceColumn: Website

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Device
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: a9862a51-400f-4dfe-9f4d-67d03afba440
		summarizeBy: none
		sourceColumn: Device

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Sessions
		dataType: double
		isHidden
		sourceProviderType: double
		lineageTag: ac777441-a552-4231-8189-5e504b47755a
		summarizeBy: none
		sourceColumn: Sessions

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'GA Transactions'
		dataType: double
		isHidden
		sourceProviderType: double
		lineageTag: a8cb0622-87b0-4cb5-860b-39f0cf14da28
		summarizeBy: none
		sourceColumn: GA Transactions

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'GA Value'
		dataType: double
		isHidden
		sourceProviderType: double
		lineageTag: 98d6e1f9-512f-4444-939c-5ba9a201773b
		summarizeBy: none
		sourceColumn: GA Value

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'GA Units'
		dataType: double
		isHidden
		sourceProviderType: double
		lineageTag: 35cfd92e-bc27-4a61-b0b0-a8dd7df337fd
		summarizeBy: none
		sourceColumn: GA Units

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Company Region'
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: 2c2fa9c6-ba95-40ee-bfce-fa041c4e8a54
		summarizeBy: none
		sourceColumn: Company Region

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Currency
		dataType: string
		lineageTag: a9fd8f2c-3f4c-43dd-90de-6e2bbb2efcf3
		summarizeBy: none
		sourceColumn: Currency

		annotation SummarizationSetBy = Automatic

	column DeviceJoin
		dataType: string
		lineageTag: c404b00a-ebab-4cb0-9df4-c64ed8c5ef55
		summarizeBy: none
		sourceColumn: DeviceJoin

		annotation SummarizationSetBy = Automatic

	partition 'GA Demand FC-a5549c1f-5e61-4273-b91a-8c07ed8804aa' = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    D2C_BFN_VW_AZURE_GA_DEMAND_View = BFN_PRESENTATION_Schema{[Name="D2C_BFN_VW_AZURE_GA_DEMAND",Kind="View"]}[Data],
				    #"Replaced Value" = Table.ReplaceValue(D2C_BFN_VW_AZURE_GA_DEMAND_View,"B2C","DM",Replacer.ReplaceText,{"Website"}),
				    #"Added Custom" = Table.AddColumn(#"Replaced Value", "DeviceJoin", each if [Device] = null then "" else [Device])
				
				in
				    #"Added Custom"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

