table 'Exchange Rates'
	lineageTag: fb3d8683-8825-4b7c-8017-0d50f7249299

	column FROMCURRENCY
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: b0b9f777-4cd0-4519-9777-7c6b3eb68bfd
		summarizeBy: none
		sourceColumn: FROMCURRENCY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TOCURRENCY
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: ad0bd068-fb6c-4db4-b491-574927942e6e
		summarizeBy: none
		sourceColumn: TOCURRENCY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RATETYPENAME
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: 79045e43-220a-4fe8-934f-3336e68eaa2d
		summarizeBy: none
		sourceColumn: RATETYPENAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RATE
		dataType: double
		sourceProviderType: decimal(16, 6)
		lineageTag: 33751486-1b0a-41cf-a09e-4ac0111fdde3
		summarizeBy: sum
		sourceColumn: RATE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DATE
		dataType: dateTime
		isHidden
		formatString: Short Date
		sourceProviderType: date
		lineageTag: 1cc845dc-64ff-49d2-8cc4-1ed612d17084
		summarizeBy: none
		sourceColumn: DATE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column START_DATE
		dataType: dateTime
		isHidden
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 7574042f-fcc2-4069-afdd-a4bf83584ab3
		summarizeBy: none
		sourceColumn: START_DATE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column END_DATE
		dataType: dateTime
		isHidden
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 6c0c5cb4-f817-41a5-a56d-f33c1fda7010
		summarizeBy: none
		sourceColumn: END_DATE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Exchange Rates' = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server, Datasource_Warehouse),
					PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    BFN_Datatable_View = BFN_PRESENTATION_Schema{[Name="SRC_BFN_VW_D365FACTCURRENCYEXCHANGERATE2",Kind="View"]}[Data],
					#"Changed Type"   = Table.TransformColumnTypes(BFN_Datatable_View,{{"DATE", type date}}),
					#"Filtered Rows"  = Table.SelectRows(#"Changed Type", each [RATETYPENAME] = "BUDGET"),
					#"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each [DATE] = DateTime.Date(DateTime.LocalNow()))
				in
					#"Filtered Rows1"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

