table Warehouse
	lineageTag: 8e60e9ea-14c8-4a20-ace2-2c83f0c5c496

	column Warehouse_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: 57015bf5-37bb-4419-a278-aba56c99fd61
		summarizeBy: none
		sourceColumn: Warehouse_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Warehouse Name'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 1abef4ff-574c-43b2-8116-e57fc1a629f5
		summarizeBy: none
		sourceColumn: Warehouse Name

		annotation SummarizationSetBy = Automatic

	column 'Site ID'
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: b0663bb1-2c5b-4d8e-99a2-3bcdba26bd86
		summarizeBy: none
		sourceColumn: Site ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Warehouse ID'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 0319ebe1-1c35-4638-b7ad-5c8e6c0b98e7
		summarizeBy: none
		sourceColumn: Warehouse ID

		annotation SummarizationSetBy = Automatic

	column 'Parent Store ID'
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: da63407a-b248-48de-a613-818ec6e562f7
		summarizeBy: none
		sourceColumn: Parent Store ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Is Retail Warehouse?'
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 5)
		lineageTag: 5080ccd7-ec00-43b6-9761-e18e781ebe4d
		summarizeBy: none
		sourceColumn: Is Retail Warehouse?

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Warehouse Group'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: bf6d9c3f-3fd1-4055-835b-cf9f07566890
		summarizeBy: none
		sourceColumn: Warehouse Group

		annotation SummarizationSetBy = Automatic

	column 'Warehouse Sub-Group'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 0b7de5ac-950b-42c4-8620-a3263c849761
		summarizeBy: none
		sourceColumn: Warehouse Sub-Group

		annotation SummarizationSetBy = Automatic

	column 'Warehouse Channel'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 3caeb3da-a9b6-4d22-bd3e-88af276ac39c
		summarizeBy: none
		sourceColumn: Warehouse Channel

		annotation SummarizationSetBy = Automatic

	column 'Warehouse Region'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: c278b42c-1ab7-4748-bfe0-7ffd97ed6a8b
		summarizeBy: none
		sourceColumn: Warehouse Region

		annotation SummarizationSetBy = Automatic

	column 'Warehouse Sub-Region'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: dcba5e39-9515-4a83-9e86-1c38376ad234
		summarizeBy: none
		sourceColumn: Warehouse Sub-Region

		annotation SummarizationSetBy = Automatic

	column FinancialChannel
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: 1c30680a-c786-45e0-8885-6cefbedba5d1
		summarizeBy: none
		sourceColumn: FinancialChannel

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Warehouse Country'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 589f34d2-93a1-40be-9b53-a59481289db0
		summarizeBy: none
		sourceColumn: Warehouse Country

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Company
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: 01908c48-707e-4cbb-8d34-c429726692d2
		summarizeBy: none
		sourceColumn: Company

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Warehouse = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server, Datasource_Warehouse),
					PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    BFN_Datatable_View = BFN_PRESENTATION_Schema{[Name="SRC_BFN_VW_D365DIMWAREHOUSE",Kind="View"]}[Data],
					#"Kept First Rows" = Table.FirstN(BFN_Datatable_View,NumberOfRows),
					ParameterFilter = if NumberOfRows > 0 then #"Kept First Rows" else BFN_Datatable_View,
				    #"Renamed Columns" = Table.RenameColumns(ParameterFilter,{{"Warehouse Address Region ID", "Warehouse Country"}})
				in
					#"Renamed Columns"

	annotation PBI_ResultType = Table

