tables: list = [
    "Channel",
    "Regions",
    "Pick",
    "Hours Worked",
    "Order Taker",
    "Seasonal Product Forecast",
    "Store Activity FC",
    "Forecast",
    "Bridge InventTransID",
    "BridgeSalesOrderNumber",
    "Order Type",
    "Deductions",
    "Hold Code Trans",
    "SmartRes",
    "Retail Demographics",
    "Sales Packing Slip",
    "Financial Channel",
    "Region",
    "Display Currency",
    "Customer",
    "Product Class",
    "Account Details",
    "Sales Order Type",
    "Selling Status - Invoice",
    "Size",
    "Warehouse",
    "Adjustments CoGS",
    "Adjustments Sales",
    "Exchange Rates",
    "Purchase Orders",
    "Products",
    "Selling Status - Order Entry",
    "Time",
    "Date",
    "Date Slicer",
    "Product Forecast",
    "Seasons",
    "Footfall",
    "Website",
    "Product Weights",
    "Seasonal Product Info",
    "Customer Sell Out EMEA",
    "Customer Sell Out US",
    "Forecast Version",
    "Seasons (Product Report)",
    "Bridge Product",
    "Metrics",
    "Model Refresh Time",
    "Net Transactions",
    "Refit Slicer",
]

partition_tables: dict = {
    "Orders": ["FY2021", "FY2022", "FY2023", "FY2024"],
}

non_partition_tables: list = [t for t in tables if t not in partition_tables.keys()]

non_partition_tables_dict: dict = {table: [] for table in non_partition_tables}
