table 'Accounts Receivable'
	lineageTag: 608a5a3b-37e5-44b7-84ee-d900e200d0ad

	column AMOUNT_CONS_GBP
		dataType: decimal
		isHidden
		formatString: " #,##0.00"
		sourceProviderType: decimal(38, 2)
		displayFolder: zz_Values
		lineageTag: 2febe2ec-7025-4e51-8173-4d7b96bbc63c
		summarizeBy: none
		sourceColumn: AMOUNT_CONS_GBP

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column SETTLEAMOUNT_CONS_GBP
		dataType: decimal
		isHidden
		formatString: " #,##0.00"
		sourceProviderType: decimal(38, 2)
		displayFolder: zz_Values
		lineageTag: 10ff4bd5-e233-41d7-98f9-00553a79ce1c
		summarizeBy: none
		sourceColumn: SETTLEAMOUNT_CONS_GBP

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column Voucher
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 1ff6bbaf-8fcc-418e-9678-8355c373f03e
		summarizeBy: none
		sourceColumn: Voucher

		annotation SummarizationSetBy = Automatic

	column 'Transaction Date'
		dataType: dateTime
		formatString: Short Date
		sourceProviderType: datetime2
		lineageTag: ba4c90c0-3218-4402-bd9f-789e0d3e9720
		summarizeBy: none
		sourceColumn: Transaction Date

		annotation SummarizationSetBy = Automatic

	column 'Due Date'
		dataType: dateTime
		formatString: Short Date
		sourceProviderType: date
		lineageTag: d2ee9bba-5616-4489-9be1-cc178be88292
		summarizeBy: none
		sourceColumn: Due Date

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: f1d7dcc2-3c1c-4c6f-9211-80315498e490
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column Currency
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: c779652a-89c2-491d-a324-ee5ebfd74e09
		summarizeBy: none
		sourceColumn: Currency

		annotation SummarizationSetBy = Automatic

	column 'Invoice Number'
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		displayFolder: zz_Misc
		lineageTag: 28351573-0dd4-4eb8-b14e-327a29b78e13
		summarizeBy: none
		sourceColumn: Invoice Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Company_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(32)
		displayFolder: zz_Keys
		lineageTag: 98c3b40b-0a7d-48e1-b478-c90c1543fec6
		summarizeBy: none
		sourceColumn: Company_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Customer_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(32)
		displayFolder: zz_Keys
		lineageTag: b56adba3-b9d2-478a-81a2-1387f0c26a33
		summarizeBy: none
		sourceColumn: Customer_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Transaction Type'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 719479ef-528b-4cbc-97d7-8f074fbf2f92
		summarizeBy: none
		sourceColumn: Transaction Type

		annotation SummarizationSetBy = Automatic

	column TransDate_Key
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: nvarchar(16777216)
		displayFolder: zz_Keys
		lineageTag: 0d7d2c43-e195-4917-aa96-24bf6232bcba
		summarizeBy: none
		sourceColumn: TransDate_Key

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column DueDate_Key
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: nvarchar(16777216)
		displayFolder: zz_Keys
		lineageTag: 611afe90-f4fd-48f3-852f-4b3c5d9d2be3
		summarizeBy: none
		sourceColumn: DueDate_Key

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

	column 'Dispute Follow-up Date'
		dataType: dateTime
		formatString: Short Date
		sourceProviderType: date
		displayFolder: 1. Disputes
		lineageTag: ddf55908-e453-4563-a38e-c442592e0a97
		summarizeBy: none
		sourceColumn: Dispute Follow-up Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Dispute Note'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: 1. Disputes
		lineageTag: 74c04ae9-8bcc-4ffb-913b-56ce3b3b37b0
		summarizeBy: none
		sourceColumn: Dispute Note

		annotation SummarizationSetBy = Automatic

	column 'Dispute Reason'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: 1. Disputes
		lineageTag: 399de39a-b5a1-473c-8036-3d1457bf7f6b
		summarizeBy: none
		sourceColumn: Dispute Reason

		annotation SummarizationSetBy = Automatic

	column 'Cost Centre'
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		displayFolder: zz_Misc
		lineageTag: bc3633c2-0ab9-4c80-b797-b13f8dbb22ad
		summarizeBy: none
		sourceColumn: Cost Centre

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DISP_AMOUNT_CONS_GBP
		dataType: decimal
		isHidden
		formatString: " #,##0.00"
		sourceProviderType: decimal(38, 12)
		displayFolder: zz_Values
		lineageTag: e46f9524-ef29-4beb-bdbc-63eb70cb3cdb
		summarizeBy: none
		sourceColumn: DISP_AMOUNT_CONS_GBP

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column ClosedDate_Key
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: nvarchar(16777216)
		displayFolder: zz_Keys
		lineageTag: 13a3d8aa-5ab6-4f82-b2d2-5a0123fd1f22
		summarizeBy: none
		sourceColumn: ClosedDate_Key

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

	column 'Invoice Closed Date'
		dataType: dateTime
		formatString: Short Date
		sourceProviderType: date
		lineageTag: f0311f80-c2fb-4d4c-bf6c-81618781052f
		summarizeBy: none
		sourceColumn: Invoice Closed Date

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Days To Pay'
		dataType: int64
		isHidden
		sourceProviderType: decimal(9, 0)
		displayFolder: zz_Misc
		lineageTag: ed8c9120-a7d5-46be-9204-c70e86a2eb67
		summarizeBy: sum
		sourceColumn: Days To Pay

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Write-Off Reason'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 1f985d47-8fc4-454e-9617-2497ec8d3387
		summarizeBy: none
		sourceColumn: Write-Off Reason

		annotation SummarizationSetBy = Automatic

	column AMOUNT_TRANS
		dataType: decimal
		isHidden
		formatString: " #,##0.00"
		sourceProviderType: decimal(16, 2)
		displayFolder: zz_Values
		lineageTag: e3f94a63-edb7-421b-9c75-4c5d4066fb4d
		summarizeBy: none
		sourceColumn: AMOUNT_TRANS

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Expected Payment Date' =
			
			VAR accadp = MIN ( RELATED ( Customer[Current Customer ADP] ), 120 )
			VAR v_adp =MAX ( accadp, 0 )
			VAR termsplus5 =
			        IFERROR(VALUE (
			            IFERROR (
			                LEFT (
			                    RELATED ( Customer[Payment Terms] ),
			                    ( SEARCH ( "D", RELATED ( Customer[Payment Terms] ),, 0 ) - 2 )
			                ),
			                0
			            )
			        ), 0) + 5
			VAR expdate = 'Accounts Receivable'[Transaction Date] + IF ( v_adp = BLANK (), termsplus5, v_adp )
			    RETURN
			        IF (
			            'Accounts Receivable'[Transaction Type] = "Sales"
			                && 'Accounts Receivable'[Open/Closed?] = "Open",
			            IF ( expdate <= TODAY () && expdate >= TODAY () - 20, TODAY (), expdate ),
			            BLANK ()
			        )
		formatString: Short Date
		lineageTag: 5761f717-e929-44da-aa32-1f0ce5c67706
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Open/Closed? =
			IF (
			                  'Accounts Receivable'[Invoice Closed Date] > DATE ( 2000, 01, 01 ),
			                  "Closed",
			                  "Open"
			              )
		lineageTag: 427bac39-40e4-4965-bd1c-e540ee255d2d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column '15 Day Ageing Buckets' = ```
			SWITCH(
			    TRUE(),
			    'Accounts Receivable'[Days Delinquent]<0, " Current",
			    AND('Accounts Receivable'[Days Delinquent]>=0, 'Accounts Receivable'[Days Delinquent]<=15), "0-15 Days",
			    AND('Accounts Receivable'[Days Delinquent]>15, 'Accounts Receivable'[Days Delinquent]<=30), "16-30 Days",
			    AND('Accounts Receivable'[Days Delinquent]>30, 'Accounts Receivable'[Days Delinquent]<=60), "31-60 Days",
			    AND('Accounts Receivable'[Days Delinquent]>60, 'Accounts Receivable'[Days Delinquent]<=90), "61-90 Days",    
			    'Accounts Receivable'[Days Delinquent]>90, "90+ Days"
			)
			```
		lineageTag: 1b2951a7-5c33-41f5-bbab-cf85857ae44d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Payment Amount (Transaction)' =
			VAR payment =
			    CALCULATE (
			        [Invoice Value (Transaction)],
			        'Accounts Receivable'[Transaction Type] = "Payment"
			    )
			VAR cancelledpayment =
			    CALCULATE (
			        [Invoice Value (Transaction)],
			        CONTAINSSTRING ( 'Accounts Receivable'[Voucher], "ARCL" )
			    )
			RETURN
			    payment - cancelledpayment
		formatString: #,0.00
		lineageTag: 95315821-d3e3-4adb-97e2-d3b4e7f039fb
		summarizeBy: none

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Invoice Acct Expected Payment Date' =
			VAR invaccadp =
			    MIN ( RELATED ( Customer[Invoice Acct Current ADP] ), 120 )
			VAR v_adp =
			    MAX ( invaccadp, 0 )
			VAR termsplus5 =
			    IFERROR(VALUE (
			        IFERROR (
			            LEFT (
			                RELATED ( Customer[Invoice Acct Payment Terms] ),
			                ( SEARCH ( "D", RELATED ( Customer[Invoice Acct Payment Terms] ),, 0 ) - 2 )
			            ),
			            0
			        )
			    ), 0) + 5
			VAR expdate =
			    'Accounts Receivable'[Transaction Date]
			        + IF ( v_adp = BLANK (), termsplus5, v_adp )
			RETURN
			    IF (
			        'Accounts Receivable'[Transaction Type] = "Sales"
			            && 'Accounts Receivable'[Open/Closed?] = "Open",
			        IF ( expdate <= TODAY () && expdate >= TODAY () - 20, TODAY (), expdate ),
			        BLANK ()
			    )
		formatString: Short Date
		lineageTag: f83aed9a-3590-4c7b-ae73-4040d942ec93
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Days Delinquent' = IF(('Accounts Receivable'[Invoice Closed Date]=DATE(1900,01,01))=TRUE(), ( TODAY()-'Accounts Receivable'[Due Date]), ( 'Accounts Receivable'[Days To Pay] - IFERROR(value( IFERROR( left( RELATED(Customer[Payment Terms]), (search("D", RELATED(Customer[Payment Terms]),, 0)-2) ) ,0) ),0 ) ))
		dataType: int64
		isHidden
		displayFolder: zz_Misc
		lineageTag: 65d3a50e-4223-481f-9280-bc27da59d1be
		summarizeBy: sum

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column InvValue*DaysToPay =
			VAR inv_xr = ( 'Accounts Receivable'[AMOUNT_CONS_GBP] * [XR] ) * 'Accounts Receivable'[Days To Pay]
			RETURN
			    IF ( inv_xr = 0, BLANK (), inv_xr )
		dataType: decimal
		isHidden
		formatString: #,##0.00
		displayFolder: zz_Misc
		lineageTag: 24d554ac-bec4-4a10-a08b-b75c88993be5
		summarizeBy: none

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column InvValue*DaysDelinquent =
			VAR inv_dd = ( 'Accounts Receivable'[AMOUNT_CONS_GBP] * [XR] ) * 'Accounts Receivable'[Days Delinquent]
			RETURN
			    IF ( inv_dd = 0, BLANK (), inv_dd )
		dataType: decimal
		isHidden
		formatString: " #,##0.00"
		displayFolder: zz_Misc
		lineageTag: 4414fd98-5bee-4ff2-a0db-002f9cb40cda
		summarizeBy: none

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column CUSTOMERGROUPID
		dataType: string
		isHidden
		lineageTag: 4eb83a7e-9d80-48f8-9945-2cbd8b5ed93b
		summarizeBy: none
		sourceColumn: CUSTOMERGROUPID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Accounts Receivable-28daedac-48b9-49a0-8e33-6b601282b702' = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server, Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    BFN_VW_D365_FACT_CUST_TRANS_View = BFN_PRESENTATION_Schema{[Name="BFN_VW_D365_FACT_CUST_TRANS",Kind="View"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(BFN_VW_D365_FACT_CUST_TRANS_View, each not List.Contains({"ECOMM", "EMPLOY", "INTERCO", "RETAIL"},[CUSTOMERGROUPID]))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

