table Pick
	lineageTag: 8f55b18f-d993-4dca-94d2-f18af6f17e4f

	column HandlingStatusDesc
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: ec3ac2ad-697c-48eb-8a5a-913cf6a2d1f2
		summarizeBy: none
		sourceColumn: HandlingStatusDesc

		annotation SummarizationSetBy = Automatic

	column INVENTTRANSID
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 1978f451-74fb-4216-bd89-9fe1a337537d
		summarizeBy: none
		sourceColumn: INVENTTRANSID

		annotation SummarizationSetBy = Automatic

	column 'Pick Qty'
		dataType: int64
		formatString: " #,##0"
		sourceProviderType: decimal(38, 0)
		lineageTag: 8c0907c6-518a-4613-a85f-a00c373b08d6
		summarizeBy: none
		sourceColumn: Pick Qty

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column ACTIVATIONDATETIME
		dataType: dateTime
		formatString: Short Date
		sourceProviderType: datetime2
		lineageTag: e817820e-ed02-46ce-bcc7-0b0ea809bb06
		summarizeBy: none
		sourceColumn: ACTIVATIONDATETIME

		annotation SummarizationSetBy = Automatic

	column INVENTLOCATIONID_WMS
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: ea97e7d3-a072-46db-842a-9903057839eb
		summarizeBy: none
		sourceColumn: INVENTLOCATIONID_WMS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Pick-5e1134e3-7075-470d-9c7b-c152397c6113 = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server, Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    BFN_FACT_D365PICKING_LIST_View = BFN_PRESENTATION_Schema{[Name="BFN_FACT_D365PICKING_LIST",Kind="View"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(BFN_FACT_D365PICKING_LIST_View, each List.Contains({"UKB2B01", "FRB2B01", "NLB2B01", "NLB2B02", "NLB2BFR", "NLB2B03", "UKB2B03", "USB2B01", "CAB2B01", "UKB2BRG01", "UKB2BRG02", "USB2B02", "USB2BLA01", "USB2BLA02", "CAB2BBC01", "CAB2BBC02", "JPB2B01", "UKB2BNH01", "UKNH-FRZ", "UKB2BNH03", "UKD2CNH01", "UKRETNH01", "UKRETNH02", "UKRETNH03", "UKNH-REWORK","USB2BNJ01","USB2BNJ02","CAB2BON01","CAB2BON02"}, [INVENTLOCATIONID_WMS]))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

