table 'Exchange Rates'
	lineageTag: 46196011-4b3b-485f-a931-93b58ffa8186

	column FROMCURRENCY
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: e1f68c95-86df-4504-aa6c-b9521400d6e6
		summarizeBy: none
		sourceColumn: FROMCURRENCY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TOCURRENCY
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: b75a303b-aeaa-4e91-8967-0c4c45bb74b6
		summarizeBy: none
		sourceColumn: TOCURRENCY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RATETYPENAME
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: 1cd31185-6ab4-4e0f-943e-d179a6523c78
		summarizeBy: none
		sourceColumn: RATETYPENAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RATE
		dataType: double
		isHidden
		formatString: " #,##0.00"
		sourceProviderType: decimal(16, 6)
		lineageTag: e5e4de83-c415-405b-bfe0-0404d15fb9db
		summarizeBy: none
		sourceColumn: RATE

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column DATE
		dataType: dateTime
		isHidden
		formatString: Long Date
		sourceProviderType: date
		lineageTag: 1ea7fadb-7b79-4d76-b194-17f4f1bd558a
		summarizeBy: none
		sourceColumn: DATE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'Exchange Rates-4d1e1060-a18d-4fd6-a591-c899b6a78ff3' = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server, Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    BFN_VW_D365FACTCURRENCYEXCHANGERATE2_View = BFN_PRESENTATION_Schema{[Name="BFN_VW_D365FACTCURRENCYEXCHANGERATE2",Kind="View"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(BFN_VW_D365FACTCURRENCYEXCHANGERATE2_View, each [DATE] = DateTime.Date(DateTime.LocalNow())),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each ([RATETYPENAME] = "BUDGET"))
				in
				    #"Filtered Rows1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

