table 'On Hand Stock'
	isHidden
	lineageTag: 6901534f-b9dd-47af-8bd9-22070a4acc37

	column Product_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(32)
		displayFolder: zz_Keys
		lineageTag: 075c6372-61d5-4009-a18e-c574615c72b7
		summarizeBy: none
		sourceColumn: Product_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Size_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(32)
		displayFolder: zz_Keys
		lineageTag: 3c918993-55fc-4d25-b458-c1fc95afda32
		summarizeBy: none
		sourceColumn: Size_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Company_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(32)
		displayFolder: zz_Keys
		lineageTag: efedb6f9-2873-494f-9722-55b3e25b57a8
		summarizeBy: none
		sourceColumn: Company_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AVAILABLEONHANDQUANTITY
		dataType: double
		isHidden
		formatString: " #,##0"
		sourceProviderType: decimal(38, 6)
		displayFolder: zz_Values
		lineageTag: 11fec5f7-220f-4f5d-9709-bb455f3e168d
		summarizeBy: none
		sourceColumn: AVAILABLEONHANDQUANTITY

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column SELLINGSTATUS
		dataType: int64
		isHidden
		sourceProviderType: decimal(38, 5)
		displayFolder: zz_Misc
		lineageTag: 6aa3cd5a-0289-4ac9-87c0-a57c502ac53a
		summarizeBy: none
		sourceColumn: SELLINGSTATUS

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'SnapShot Date'
		dataType: dateTime
		isHidden
		formatString: Short Date
		sourceProviderType: date
		displayFolder: zz_Misc
		lineageTag: 188bf2a6-c4e5-4c14-a6ef-19c1cd8377b4
		summarizeBy: none
		sourceColumn: SnapShot Date

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Warehouse_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(32)
		displayFolder: zz_Keys
		lineageTag: 7c22757e-4bc7-4b1d-ba36-0f0e5c24c685
		summarizeBy: none
		sourceColumn: Warehouse_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column WAREHOUSEID
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: ebcb4064-421e-4019-b5a3-8e20d9d6077d
		summarizeBy: none
		sourceColumn: WAREHOUSEID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'On Hand Stock-53241a73-3c5e-455c-bd89-bd240bcac410' = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server, Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    BFN_VW_D365_FACT_INVENTORY_ON_HAND_VALUE_COVERAGE_CURRENTMONTH_View = BFN_PRESENTATION_Schema{[Name="BFN_VW_D365_FACT_INVENTORY_ON_HAND_VALUE_COVERAGE_CURRENTMONTH",Kind="View"]}[Data],
				    FilterToday = DateTime.Date(DateTime.LocalNow()),
				    #"Filtered Rows" = Table.SelectRows(BFN_VW_D365_FACT_INVENTORY_ON_HAND_VALUE_COVERAGE_CURRENTMONTH_View, each List.Contains({"FRB2B01", "UKB2B01", "NLB2B01", "NLB2B02", "NLB2BFR", "NLB2B03", "UKB2B03", "USB2B01", "CAB2B01", "UKB2BRG01", "UKB2BRG02", "HKB2B01", "CAB2BBC01", "CAB2BBC02", "JPB2B01", "UKB2BNH01", "UKNH-FRZ", "UKB2BNH03", "UKD2CNH01", "UKRETNH01", "UKRETNH02", "UKRETNH03", "UKNH-REWORK"},[WAREHOUSEID]) and [SnapShot Date]=FilterToday)
				in
				    #"Filtered Rows"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

