table Region
	lineageTag: b51cf4f4-f35f-4d36-89fb-d93d5a53b7ef

	column 'Company ShortName'
		dataType: string
		lineageTag: 43304336-44d7-4c96-93be-e6f8f2218a44
		summarizeBy: none
		sourceColumn: Company ShortName

		annotation SummarizationSetBy = Automatic

	column 'Region ID'
		dataType: string
		isHidden
		displayFolder: zz_Misc
		lineageTag: dbbfa4b5-114e-42af-bb65-124c3d8d97cf
		summarizeBy: none
		sourceColumn: Region ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Company ID'
		dataType: string
		lineageTag: a21165b9-b5e1-43ac-ac74-6593bfdd114b
		summarizeBy: none
		sourceColumn: Company ID

		annotation SummarizationSetBy = Automatic

	column Company_Key
		dataType: string
		isHidden
		displayFolder: zz_Keys
		lineageTag: ecc0772b-d6b9-4f75-ba6b-da53368d616b
		summarizeBy: none
		sourceColumn: Company_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 69c634c4-a317-4d0e-8e4b-44ceff3b6097
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Sub-Region
		dataType: string
		lineageTag: c52ea5e2-5ced-43ab-b0a1-ef710729c444
		summarizeBy: none
		sourceColumn: Sub-Region

		annotation SummarizationSetBy = Automatic

	partition Region-097ee000-63f9-4490-9c61-eae5e24b956d = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server, Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    BFN_VW_D365DIMCOMPANY_View = BFN_PRESENTATION_Schema{[Name="BFN_VW_D365DIMCOMPANY",Kind="View"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(BFN_VW_D365DIMCOMPANY_View, each [Company_Key] <> "0")
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

