table 'Seasonal Product Forecast'
	lineageTag: 9c8e429b-989e-4c4e-a7f7-82762ec54e59

	column Date_key
		dataType: string
		isHidden
		displayFolder: zz_Keys
		lineageTag: 7ed0631f-376f-4184-847b-b06631a51d4a
		summarizeBy: none
		sourceColumn: Date_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Product_Key
		dataType: string
		isHidden
		displayFolder: zz_Keys
		lineageTag: 06335d8e-57f1-4cc1-975f-4a9fa8bd33f6
		summarizeBy: none
		sourceColumn: Product_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Customer_Key
		dataType: string
		isHidden
		displayFolder: zz_Keys
		lineageTag: f7f17065-725b-4b19-bfc8-4fe3816ccbcc
		summarizeBy: none
		sourceColumn: Customer_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Forecast Quantity'
		dataType: int64
		displayFolder: zz_Values
		lineageTag: 5e529a49-ffae-43ab-b6bc-c63010c5820b
		summarizeBy: sum
		sourceColumn: Forecast Quantity

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Order_Type
		dataType: string
		isHidden
		displayFolder: zz_Keys
		lineageTag: 33b1dec6-79a7-41c5-814d-acc17110927c
		summarizeBy: none
		sourceColumn: Order_Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Seasonal Product Forecast-9252f3db-c8fb-416f-86f1-6893f4160c82' = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server, Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    BFN_VW_AZURE_PRODUCT_SEASONAL_View = BFN_PRESENTATION_Schema{[Name="BFN_VW_AZURE_PRODUCT_SEASONAL",Kind="View"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(BFN_VW_AZURE_PRODUCT_SEASONAL_View, each ([Order_Type] = "B2B" or [Order_Type] = "DD"))
				in
				    #"Filtered Rows"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

