table 'Selling Status - Order Entry'
	lineageTag: 1f24094a-7956-494a-9e8d-4486607326b0

	column SELLINGSTATUS
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: zz_Misc
		lineageTag: ff62984d-9b18-4252-bf96-fc3f8f263b55
		summarizeBy: none
		sourceColumn: SELLINGSTATUS

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

	column 'Selling Status - Order Entry'
		dataType: string
		lineageTag: 201b0134-0991-43ce-b6f4-da43b14a554f
		summarizeBy: none
		sourceColumn: Selling Status - Order Entry

		annotation SummarizationSetBy = Automatic

	column 'Selling Status Sort'
		dataType: int64
		isHidden
		displayFolder: zz_Misc
		lineageTag: 5111f635-8d1e-47c5-96fd-9529f3648f3d
		summarizeBy: none
		sourceColumn: Selling Status Sort

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'TBD vs Continuity/Carry Over - Order Entry' =
			IF (
			    'Selling Status - Order Entry'[Selling Status - Order Entry]
			        IN { "Continuity", "Carry Over" },
			    "Continuity/Carry Over",
			    'Selling Status - Order Entry'[Selling Status - Order Entry]
			)
		dataType: string
		lineageTag: 1f96e86a-a392-42f9-aea6-faa2bdaf4479
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	partition 'Selling Status - Order Entry-d6b39e0b-ff69-427f-8cb9-eea065e87f91' = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server, Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    BFN_VW_D365DIMPRODUCTSELLINGSTATUS_ORDER_ENTRY_View = BFN_PRESENTATION_Schema{[Name="BFN_VW_D365DIMPRODUCTSELLINGSTATUS_ORDER_ENTRY",Kind="View"]}[Data],
				    #"Removed Duplicates" = Table.Distinct(BFN_VW_D365DIMPRODUCTSELLINGSTATUS_ORDER_ENTRY_View, {"SELLINGSTATUS"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Duplicates", each ([SELLINGSTATUS] <> null))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

