table COMPANIES
	lineageTag: 8a0082ae-add1-4696-9334-9074e940ac4a

	column 'Company Name'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 5831b3f3-134e-4a8b-8f59-69b6f36c8bad
		summarizeBy: none
		sourceColumn: Company Name

		annotation SummarizationSetBy = Automatic

	column 'Company ID'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: dc9e2dae-cc78-4455-8e42-1b7d3bd09343
		summarizeBy: none
		sourceColumn: Company ID

		annotation SummarizationSetBy = Automatic

	column Company_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(32)
		displayFolder: zz_Misc
		lineageTag: 86b07cef-8844-4b31-a9ea-f47ece154215
		summarizeBy: none
		sourceColumn: Company_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: ddcdb5ad-4c8d-4a82-8f57-db3e5f3e0bd8
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Sub-Region
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: c8e27a59-bcd7-495a-abc5-2e3a73cd5d74
		summarizeBy: none
		sourceColumn: Sub-Region

		annotation SummarizationSetBy = Automatic

	column 'Company ShortName'
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: 9a676b71-99b6-4382-8ed0-82d70f8b4315
		summarizeBy: none
		sourceColumn: Company ShortName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Region ID'
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: 1d6aab53-e0b0-4091-b9f1-0f21e9e6579d
		summarizeBy: none
		sourceColumn: Region ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition COMPANIES-5869953e-718b-4542-89d8-fde670ec3de8 = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    PRODUCT_BFN_VW_D365DIMCOMPANY_View = BFN_PRESENTATION_Schema{[Name="PRODUCT_BFN_VW_D365DIMCOMPANY",Kind="View"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(PRODUCT_BFN_VW_D365DIMCOMPANY_View, each ([Company_Key] <> 0))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

