table 'Exchange Rates'
	isHidden
	lineageTag: 9d112999-66d7-4ba0-af84-ca94e3661214

	column RATE
		dataType: decimal
		isHidden
		sourceProviderType: decimal(16, 6)
		lineageTag: 06359465-2598-48de-82f5-72605659bb8f
		summarizeBy: none
		sourceColumn: RATE

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Transaction Currency'
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: e69e65a6-5f51-432b-a1c2-bd03a21f1f6d
		summarizeBy: none
		sourceColumn: Transaction Currency

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RATETYPENAME
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: f2e26418-aed4-430e-902f-415fa6ca86e2
		summarizeBy: none
		sourceColumn: RATETYPENAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Exchange Rates-f312b96a-bae0-484d-bf66-7b9220cf639c' = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    PRODUCT_BFN_VW_D365FACTCURRENCYEXCHANGERATE_View = BFN_PRESENTATION_Schema{[Name="PRODUCT_BFN_VW_D365FACTCURRENCYEXCHANGERATE",Kind="View"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(PRODUCT_BFN_VW_D365FACTCURRENCYEXCHANGERATE_View, each [RATETYPENAME] = "BUDGET")
				in
				    #"Filtered Rows"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

