table Orders
	isHidden
	lineageTag: d0a9dca5-281e-43ff-8f5b-8ba43a68e3e2

	column Product_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(32)
		displayFolder: zz_Keys
		lineageTag: 9c9c4a00-35d9-4ddc-a821-bb7d415ae005
		summarizeBy: none
		sourceColumn: Product_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Company_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(32)
		displayFolder: zz_Keys
		lineageTag: b90b91a0-1244-4108-b4a3-ac7dd4da0f8c
		summarizeBy: none
		sourceColumn: Company_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Channel ID'
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		displayFolder: zz_Keys
		lineageTag: 392abe09-91e2-477a-9af7-7530854bd5c4
		summarizeBy: none
		sourceColumn: Channel ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column isCarrierBag
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		displayFolder: zz_Misc
		lineageTag: 98db0d15-f613-4327-9501-436cca9faec9
		summarizeBy: none
		sourceColumn: isCarrierBag

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Transaction Type'
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		displayFolder: zz_Misc
		lineageTag: 343c1ae4-b40e-4888-99e4-7b2d7b2467d6
		summarizeBy: none
		sourceColumn: Transaction Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column INVOICEDQUANTITY_SIL
		dataType: int64
		isHidden
		formatString: #,##0
		sourceProviderType: decimal(38, 6)
		displayFolder: zz_Units
		lineageTag: af4f341f-4925-4795-9f18-4fe6c8c32cb0
		summarizeBy: none
		sourceColumn: INVOICEDQUANTITY_SIL

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column Date_Key
		dataType: int64
		isHidden
		sourceProviderType: nvarchar(16777216)
		displayFolder: zz_Keys
		lineageTag: 87aad8e8-a884-42d1-9020-012617a43c3d
		summarizeBy: none
		sourceColumn: Date_Key

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Transaction Status'
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		displayFolder: zz_Misc
		lineageTag: 346e4e14-4435-46d3-b7a4-02cc8dcf4bfa
		summarizeBy: none
		sourceColumn: Transaction Status

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CustomerPD_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(32)
		displayFolder: zz_Keys
		lineageTag: 7bb963b5-2de7-4744-9d7f-ab33eaee9e73
		summarizeBy: none
		sourceColumn: CustomerPD_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RETURNEDSALESQUANTITY_ROL_ZEROS
		dataType: int64
		isHidden
		formatString: #,##0
		sourceProviderType: decimal(38, 6)
		displayFolder: zz_Units
		lineageTag: 200d29dc-3fe6-47a8-b515-87a99e0d79fc
		summarizeBy: none
		sourceColumn: RETURNEDSALESQUANTITY_ROL_ZEROS

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column SALESORDERNUMBER_SOH
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		displayFolder: zz_Misc
		lineageTag: 97675054-07ca-4f9e-9eb1-b694df9ecb30
		summarizeBy: none
		sourceColumn: SALESORDERNUMBER_SOH

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column INVOICENUMBER_SIH
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		displayFolder: zz_Misc
		lineageTag: 1f3402cd-b27b-4ea4-85bd-9100a73edd08
		summarizeBy: none
		sourceColumn: INVOICENUMBER_SIH

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DELIVERYADDRESSCOUNTRYREGIONID_SOH
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		displayFolder: zz_Misc
		lineageTag: c7eb3aee-aa77-4b96-b57c-741bc5159894
		summarizeBy: none
		sourceColumn: DELIVERYADDRESSCOUNTRYREGIONID_SOH

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column HeaderDiscount_TRANS
		dataType: decimal
		isHidden
		formatString: #,##0.00
		sourceProviderType: decimal(38, 12)
		displayFolder: zz_Values
		lineageTag: d013dad9-9916-4dd0-a1fb-4a934c86b13f
		summarizeBy: none
		sourceColumn: HeaderDiscount_TRANS

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column LINEAMOUNT_SIL_TRANS
		dataType: decimal
		isHidden
		formatString: #,##0.00
		sourceProviderType: decimal(32, 6)
		displayFolder: zz_Values
		lineageTag: 529b699f-5a0a-4068-90c9-2d2045f48f97
		summarizeBy: none
		sourceColumn: LINEAMOUNT_SIL_TRANS

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column ChargeTotalExcTax_TRANS
		dataType: decimal
		isHidden
		formatString: #,##0.00
		sourceProviderType: decimal(38, 6)
		displayFolder: zz_Values
		lineageTag: bc116e25-d784-471b-8e7a-1e9534e613b3
		summarizeBy: none
		sourceColumn: ChargeTotalExcTax_TRANS

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Transaction Currency'
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		displayFolder: zz_Misc
		lineageTag: 9456c3e5-17ee-4794-a9fc-b27f9dca6413
		summarizeBy: none
		sourceColumn: Transaction Currency

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Size_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		displayFolder: zz_Keys
		lineageTag: 5386c314-76e6-4fa9-80ad-77ca2b828329
		summarizeBy: none
		sourceColumn: Size_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column COSTAMOUNTPOSTED_SILCS
		dataType: decimal
		isHidden
		formatString: #,##0.00
		sourceProviderType: decimal(31, 11)
		displayFolder: zz_Values
		lineageTag: 1b4892bb-8b52-4aeb-b644-b6b944846e51
		summarizeBy: none
		sourceColumn: COSTAMOUNTPOSTED_SILCS

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column RETURNEDSALESQUANTITY_ROL
		dataType: int64
		isHidden
		formatString: #,##0
		sourceProviderType: decimal(38, 6)
		displayFolder: zz_Units
		lineageTag: 0e447f8c-b13e-424b-898d-742a15d92cb1
		summarizeBy: none
		sourceColumn: RETURNEDSALESQUANTITY_ROL

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Country ID' =
			IF (
			    Orders[Channel ID] = "102",
			    Orders[DELIVERYADDRESSCOUNTRYREGIONID_SOH],
			    RELATED ( CUSTOMERS[FINANCIALCOUNTRY] )
			)
		dataType: string
		isHidden
		displayFolder: zz_Keys
		lineageTag: 3f93eb6d-de80-47a4-b104-46b702608212
		summarizeBy: none
		isDataTypeInferred

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Returned Units Col' =
			IF (
			    AND (
			        Orders[Transaction Type] = "Return",
			        Orders[Transaction Status] = "Invoiced"
			    ),
			    IF (
			        Orders[INVOICEDQUANTITY_SIL] <> 0,
			        ABS ( Orders[INVOICEDQUANTITY_SIL] ),
			        ABS ( Orders[RETURNEDSALESQUANTITY_ROL_ZEROS] )
			    ),
			    BLANK ()
			)
		dataType: int64
		isHidden
		formatString: #,##0
		displayFolder: zz_Units
		lineageTag: 16478adf-0d26-4012-8022-686abac55ea6
		summarizeBy: none

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Invoiced Units Col' =
			IF (
			    AND (
			        Orders[Transaction Type] IN { "Sale", "Charge" },
			        Orders[Transaction Status] = "Invoiced"
			    ),
			    Orders[INVOICEDQUANTITY_SIL],
			    BLANK ()
			)
		dataType: int64
		isHidden
		formatString: #,##0
		displayFolder: zz_Units
		lineageTag: 950f1e9e-bd01-4d91-ac45-8c9ab4007bbd
		summarizeBy: none
		isDataTypeInferred

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Invoiced Net Value Col Direct Cons GBP' =
			IF (
			    AND (
			        Orders[Transaction Type] IN { "Sale", "Charge" },
			        Orders[Transaction Status] = "Invoiced"
			    ),
			    DIVIDE (
			         ( Orders[LINEAMOUNT_SIL_TRANS] - Orders[HeaderDiscount_TRANS] ) + Orders[ChargeTotalExcTax_TRANS],
			        RELATED ( 'Exchange Rates'[RATE] )
			    ),
			    BLANK ()
			)
		dataType: decimal
		isHidden
		formatString: #,##0.00
		displayFolder: zz_Values
		lineageTag: caa897d6-8d86-4d51-b4c3-a1759409b54f
		summarizeBy: none

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Returned Net Value Col Direct Cons GBP' =
			IF (
			    AND (
			        Orders[Transaction Type] = "Return",
			        Orders[Transaction Status] = "Invoiced"
			    ),
			    DIVIDE (
			        ABS ( Orders[LINEAMOUNT_SIL_TRANS] + Orders[HeaderDiscount_TRANS] ),
			        RELATED ( 'Exchange Rates'[RATE] )
			    ),
			    BLANK ()
			)
		dataType: decimal
		isHidden
		formatString: #,##0.00
		displayFolder: zz_Values
		lineageTag: d81c27f2-10a2-4725-b9da-0a6e325e09b4
		summarizeBy: none

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Invoiced COGS Col' =
			IF (
			    AND (
			        OR (
			            ISBLANK ( Orders[RETURNEDSALESQUANTITY_ROL] ),
			            Orders[RETURNEDSALESQUANTITY_ROL] = 0
			        ),
			        Orders[INVOICEDQUANTITY_SIL] > 0
			    ),
			    ROUND ( 'Orders'[COSTAMOUNTPOSTED_SILCS], 2 ) * -1,
			    BLANK ()
			)
		dataType: decimal
		isHidden
		formatString: #,##0.00
		displayFolder: zz_Values
		lineageTag: 92d04509-9d37-4c24-beb2-b71633095e71
		summarizeBy: none
		isDataTypeInferred

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Returned COGS Col' =
			IF (
			    Orders[Transaction Type] = "Return",
			    'Orders'[COSTAMOUNTPOSTED_SILCS],
			    BLANK ()
			)
		dataType: decimal
		isHidden
		formatString: #,##0.00
		displayFolder: zz_Values
		lineageTag: 9866d030-19c3-4d64-8f16-ecf6e7d70d0f
		summarizeBy: none
		isDataTypeInferred

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column isHistorical
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 0)
		lineageTag: 629a19fc-fae9-47db-9d04-34318e8ab771
		summarizeBy: none
		sourceColumn: isHistorical

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Customer_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(32)
		lineageTag: 9c419c11-53bd-47a3-a516-499bafb16d4a
		summarizeBy: none
		sourceColumn: Customer_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Orders-eca4c89c-877b-43e3-b51d-6238046c4ad1 = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    PRODUCT_BFN_VW_D365_FACT_SALES_View = BFN_PRESENTATION_Schema{[Name="PRODUCT_BFN_VW_D365_FACT_SALES",Kind="View"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(PRODUCT_BFN_VW_D365_FACT_SALES_View,{"Date_Key", "Product_Key", "Company_Key", "Customer_Key", "CustomerPD_Key", "Size_Key", "RETURNEDSALESQUANTITY_ROL_ZEROS", "INVOICEDQUANTITY_SIL",  "Transaction Type", "Transaction Status", "Channel ID", "isCarrierBag", "HeaderDiscount_TRANS", "LINEAMOUNT_SIL_TRANS", "ChargeTotalExcTax_TRANS", "isHistorical", "DELIVERYADDRESSCOUNTRYREGIONID_SOH", "SALESORDERNUMBER_SOH", "INVOICENUMBER_SIH", "Transaction Currency", "COSTAMOUNTPOSTED_SILCS", "RETURNEDSALESQUANTITY_ROL"}),
				    #"Kept First Rows" = Table.FirstN(#"Removed Other Columns",NumberOfRows),
				    ParameterFilter = if NumberOfRows > 0 then #"Kept First Rows" else #"Removed Other Columns"
				
				in
				    ParameterFilter

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

