table 'Invoice Date'
	lineageTag: 156241f2-4352-4c45-8246-fabc3ca2a817

	column 'Invoice Date'
		dataType: dateTime
		formatString: Short Date
		sourceProviderType: datetime2
		lineageTag: 63b0502b-6c5d-4fc4-af59-0dc6dabb9b3d
		summarizeBy: none
		sourceColumn: Invoice Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Day # of Year'
		dataType: int64
		sourceProviderType: decimal(38, 0)
		displayFolder: Calendar Dates
		lineageTag: d661859e-8abe-46d0-a8b3-7bda490e20e2
		summarizeBy: none
		sourceColumn: Day # of Year

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Season
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		displayFolder: Calendar Dates
		lineageTag: 5bf79643-44f8-44f3-841e-b0eb1fd6370f
		summarizeBy: none
		sourceColumn: Season

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Relative Week'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: Calendar Dates
		lineageTag: a4aae12c-b1f0-4f68-a450-1684004db6df
		summarizeBy: none
		sourceColumn: Relative Week

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Relative Month'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: Calendar Dates
		lineageTag: 99f258e7-73b4-421b-b9fc-67c79dc1394f
		summarizeBy: none
		sourceColumn: Relative Month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Relative Year'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: Calendar Dates
		lineageTag: b1ffa986-6147-4e30-9e0f-663fe6e254bb
		summarizeBy: none
		sourceColumn: Relative Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Day of Week'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: Calendar Dates
		lineageTag: 58ffadb4-6790-4e7b-b73c-d49298c233a2
		summarizeBy: none
		sourceColumn: Day of Week

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Day # of Week'
		dataType: int64
		sourceProviderType: decimal(38, 0)
		displayFolder: Calendar Dates
		lineageTag: efe5f95b-3cc5-4bd4-bd5a-9b4ad2f44e6e
		summarizeBy: none
		sourceColumn: Day # of Week

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Day # of Month'
		dataType: int64
		sourceProviderType: decimal(38, 0)
		displayFolder: Calendar Dates
		lineageTag: c5dedfbf-1b9b-4830-b713-ed1f44b0aabe
		summarizeBy: none
		sourceColumn: Day # of Month

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Year
		dataType: int64
		sourceProviderType: decimal(38, 0)
		displayFolder: Calendar Dates
		lineageTag: 3a7779ab-9c3b-49b6-8a9c-daef638f5ad6
		summarizeBy: none
		sourceColumn: Year

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Year-Week
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: Calendar Dates
		lineageTag: 5a471f7b-e4af-46ee-8ed6-b5f60d6206a5
		summarizeBy: none
		sourceColumn: Year-Week

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Half
		dataType: string
		sourceProviderType: nvarchar(2)
		displayFolder: Calendar Dates
		lineageTag: 4bd6b191-0153-48b5-9ad3-e70a5d7675b3
		summarizeBy: none
		sourceColumn: Half

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Year Half'
		dataType: string
		sourceProviderType: nvarchar(9)
		displayFolder: Calendar Dates
		lineageTag: e245ef38-b66c-4174-99c3-25aa6c9e2adb
		summarizeBy: none
		sourceColumn: Year Half

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		sourceProviderType: nvarchar(2)
		displayFolder: Calendar Dates
		lineageTag: 921e3e81-372c-446a-8b04-c2260e07e79c
		summarizeBy: none
		sourceColumn: Quarter

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '- Is UK Bank Holiday?'
		dataType: string
		sourceProviderType: nvarchar(3)
		displayFolder: Calendar Dates
		lineageTag: 85282b9a-9c7e-42d8-978d-c87111615166
		summarizeBy: none
		sourceColumn: - Is UK Bank Holiday?

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '- Is Black Friday?'
		dataType: string
		sourceProviderType: nvarchar(3)
		displayFolder: Calendar Dates
		lineageTag: 8c6f3b94-98c0-4e91-a655-8df5d7aeb63d
		summarizeBy: none
		sourceColumn: - Is Black Friday?

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '- Is Leap Year?'
		dataType: string
		sourceProviderType: nvarchar(3)
		displayFolder: Calendar Dates
		lineageTag: 7763bda2-8461-4a22-a34d-4229cadadef7
		summarizeBy: none
		sourceColumn: - Is Leap Year?

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '- Is End Of Month?'
		dataType: string
		sourceProviderType: nvarchar(3)
		displayFolder: Calendar Dates
		lineageTag: 08432326-e1f2-467d-bdec-b0f7ec90fb07
		summarizeBy: none
		sourceColumn: - Is End Of Month?

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '- Is End Of Period?'
		dataType: string
		displayFolder: Calendar Dates
		lineageTag: e7b2593a-0a26-4736-b97d-9373c1b4270d
		summarizeBy: none
		sourceColumn: - Is End Of Period?

		annotation SummarizationSetBy = Automatic

	column '- Is End Of Quarter?'
		dataType: string
		displayFolder: Calendar Dates
		lineageTag: cdd4a576-13cf-47d2-979b-586206eb4b2e
		summarizeBy: none
		sourceColumn: - Is End Of Quarter?

		annotation SummarizationSetBy = Automatic

	column '- Is Yesterday?'
		dataType: string
		sourceProviderType: nvarchar(3)
		displayFolder: Calendar Dates
		lineageTag: 805d32f0-cc75-47ef-83bd-cf118e5db43f
		summarizeBy: none
		sourceColumn: - Is Yesterday?

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '- Is Week?'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: Calendar Dates
		lineageTag: b0c6a574-b38c-48fa-8c47-c4a8671d44b4
		summarizeBy: none
		sourceColumn: - Is Week?

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '- Is Month?'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: Calendar Dates
		lineageTag: e102ef1b-3ab0-40d5-953a-879048bea3aa
		summarizeBy: none
		sourceColumn: - Is Month?

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Calendar Month Long Name'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: Calendar Dates
		lineageTag: 4fdbcaee-ae68-4226-9c60-e25c285355c7
		summarizeBy: none
		sourceColumn: Calendar Month Long Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Calendar Year Month'
		dataType: int64
		isHidden
		sourceProviderType: decimal(38, 0)
		displayFolder: Calendar Dates
		lineageTag: 4f68b887-6d86-44fd-b6ce-4b5572b7af31
		summarizeBy: none
		sourceColumn: Calendar Year Month

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fiscal Year'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: Fiscal Dates
		lineageTag: aa1b6bdb-00d9-4484-ba92-4c40f212aad8
		summarizeBy: none
		sourceColumn: Fiscal Year

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Quarter Number'
		dataType: int64
		sourceProviderType: decimal(38, 0)
		displayFolder: Fiscal Dates
		lineageTag: eac44992-2ba5-437e-803d-bd5a3225332f
		summarizeBy: none
		sourceColumn: Fiscal Quarter Number

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fiscal Period Short Name'
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		displayFolder: Fiscal Dates
		lineageTag: 86ade6f8-3979-40c4-b0f5-172b9f832822
		summarizeBy: none
		sourceColumn: Fiscal Period Short Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Period Number'
		dataType: int64
		sourceProviderType: decimal(38, 0)
		displayFolder: Fiscal Dates
		lineageTag: 30b10efa-33e8-414b-a224-79b190e8b307
		summarizeBy: none
		sourceColumn: Fiscal Period Number

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fiscal Year-Period'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: Fiscal Dates
		lineageTag: f499b770-e3d1-423b-84b6-7ea1b895c124
		summarizeBy: none
		sourceColumn: Fiscal Year-Period

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Week Number'
		dataType: int64
		sourceProviderType: decimal(38, 0)
		displayFolder: Fiscal Dates
		lineageTag: 0dae07e1-68e3-4eba-8cb7-d2a460ee1247
		summarizeBy: none
		sourceColumn: Fiscal Week Number

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fiscal Year Number'
		dataType: int64
		sourceProviderType: decimal(38, 0)
		displayFolder: Fiscal Dates
		lineageTag: 358f0811-6814-4346-a8cc-da939c6f142c
		summarizeBy: none
		sourceColumn: Fiscal Year Number

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Relative Fiscal Week'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: Fiscal Dates
		lineageTag: 90a29930-63f3-474d-9d5f-0a00a7132929
		summarizeBy: none
		sourceColumn: Relative Fiscal Week

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Relative Fiscal Period'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: Fiscal Dates
		lineageTag: b025f8b8-2aad-4e31-be8d-3718a7460185
		summarizeBy: none
		sourceColumn: Relative Fiscal Period

		annotation SummarizationSetBy = Automatic

	column 'Relative Fiscal Year'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: Fiscal Dates
		lineageTag: 661cd70f-3d37-4ddf-9152-eb8a1caebfd7
		summarizeBy: none
		sourceColumn: Relative Fiscal Year

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Day #'
		dataType: int64
		sourceProviderType: decimal(38, 0)
		displayFolder: Fiscal Dates
		lineageTag: 44e01e80-0963-402d-96e4-db453bb681ea
		summarizeBy: none
		sourceColumn: Fiscal Day #

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Week Number (544)'
		dataType: int64
		sourceProviderType: decimal(38, 0)
		displayFolder: 544 Dates
		lineageTag: c2dc5143-967d-460b-ba32-49bafe7f3a8e
		summarizeBy: none
		sourceColumn: Week Number (544)

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fiscal Period Number (544)'
		dataType: int64
		sourceProviderType: decimal(38, 0)
		displayFolder: 544 Dates
		lineageTag: 6e1918f5-beb9-4153-b47a-f8b1d75420fc
		summarizeBy: none
		sourceColumn: Fiscal Period Number (544)

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fiscal Quarter (544)'
		dataType: int64
		sourceProviderType: decimal(38, 0)
		displayFolder: 544 Dates
		lineageTag: b5d77e07-af62-4557-baea-58a32d008590
		summarizeBy: none
		sourceColumn: Fiscal Quarter (544)

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fiscal Half (544)'
		dataType: int64
		sourceProviderType: decimal(38, 0)
		displayFolder: 544 Dates
		lineageTag: a4c9989f-76be-4478-abbb-5cfc4db96811
		summarizeBy: none
		sourceColumn: Fiscal Half (544)

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fiscal Year (544)'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: 544 Dates
		lineageTag: bda4f847-0b53-4d06-8cfe-a464da451699
		summarizeBy: none
		sourceColumn: Fiscal Year (544)

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year Number (544)'
		dataType: int64
		sourceProviderType: decimal(38, 0)
		displayFolder: 544 Dates
		lineageTag: e899229b-466c-4ca9-99f0-9b90456dd386
		summarizeBy: none
		sourceColumn: Fiscal Year Number (544)

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fiscal Year-Week (544)'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: 544 Dates
		lineageTag: 269545b8-0cb4-4c3b-b48a-cc1d8bd82550
		summarizeBy: none
		sourceColumn: Fiscal Year-Week (544)

		annotation SummarizationSetBy = Automatic

	column 'Relative Fiscal Period (544)'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: 544 Dates
		lineageTag: b90c2847-8be7-4151-9edc-60f96921c39f
		summarizeBy: none
		sourceColumn: Relative Fiscal Period (544)

		annotation SummarizationSetBy = Automatic

	column 'Relative Fiscal Year (544)'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: 544 Dates
		lineageTag: 1a1600e9-d81f-473c-a743-1a2868fc9928
		summarizeBy: none
		sourceColumn: Relative Fiscal Year (544)

		annotation SummarizationSetBy = Automatic

	column 'Calendar Month Short Number' = ```
			SWITCH(MONTH('Invoice Date'[Invoice Date]), 
			1,"01",
			2,"02",
			3,"03",
			4,"04",
			5,"05",
			6,"06",
			7,"07",
			8,"08",
			9,"09",
			10,"10",
			11,"11",
			12,"12")
			```
		lineageTag: 90a4ca5e-d659-4d12-85ef-2e45e6f233ce
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Calendar Month Short Name' = ```
			SWITCH('Invoice Date'[Calendar Month Short Number], "01", "Jan", "02", "Feb", "03", "Mar", "04", "Apr"  
			              , "05", "May", "06", "Jun", "07", "Jul", "08", "Aug"  
			               , "09", "Sep", "10", "Oct", "11", "Nov", "12", "Dec") 
			```
		lineageTag: a63249cc-a4e1-4264-89c4-7483c287c884
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Calendar Day Number' = ```
			SWITCH('invoice Date'[Day # of Month], 
			1,"01",
			2,"02",
			3,"03",
			4,"04",
			5,"05",
			6,"06",
			7,"07",
			8,"08",
			9,"09",
			10,"10",
			11,"11",
			12,"12",
			13,"13",
			14,"14",
			15,"15",
			16,"16",
			17,"17",
			18,"18",
			19,"19",
			20,"20",
			21,"21",
			22,"22",
			23,"23",
			24,"24",
			25,"25",
			26,"26",
			27,"27",
			28,"28",
			29,"29",
			30,"30",
			31,"31"
			)
			```
		lineageTag: d2f37fc5-5e0a-4956-aa6a-5b2a0d10b402
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Period Name' = RIGHT([Fiscal Period Short Name], 3)
		displayFolder: Fiscal Dates
		lineageTag: 6487d51f-02c1-4198-8f8c-cd13e3a4deac
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Date Key'
		dataType: int64
		isHidden
		displayFolder: Calendar Dates
		lineageTag: b086bdd8-3268-4ee2-8ef9-2b9a4d8c611c
		summarizeBy: none
		sourceColumn: Date Key

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Month Year'
		dataType: string
		displayFolder: Calendar Dates
		lineageTag: 5c0a6933-2f92-47d2-8a77-7bf86b4abf8e
		summarizeBy: none
		sourceColumn: Month Year

		annotation SummarizationSetBy = Automatic

	column 'Reporting Year'
		dataType: int64
		displayFolder: Calendar Dates
		lineageTag: b081c85f-674c-41b6-a2a1-fc3f8c5a7cb7
		summarizeBy: none
		sourceColumn: Reporting Year

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fiscal Year-Week'
		dataType: string
		displayFolder: Fiscal Dates
		lineageTag: 9019ce66-ef70-42e7-bf80-417ce6b7d9ef
		summarizeBy: none
		sourceColumn: Fiscal Year-Week

		annotation SummarizationSetBy = Automatic

	partition 'Invoice Date' = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server, Datasource_Warehouse),
					PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    BFN_Datatable_View = BFN_PRESENTATION_Schema{[Name="SRC_BFN_VW_INVOICEDATE",Kind="View"]}[Data],
					#"Kept First Rows" = Table.FirstN(BFN_Datatable_View,NumberOfRows),
					ParameterFilter = if NumberOfRows > 0 then #"Kept First Rows" else BFN_Datatable_View,
				    #"Removed Columns" = Table.RemoveColumns(ParameterFilter,{"Purchase Season", "Calendar Month Number", "Calendar Week Number", "Season Long Name"})
				in
					#"Removed Columns"

	annotation PBI_ResultType = Table

