table Products
	lineageTag: a6017f92-f4a0-493e-ae26-312bf1005d2a

	column Product_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(32)
		displayFolder: zz_Keys
		lineageTag: 54ad62bb-3d9b-4cc0-a99f-fbdae52e648f
		summarizeBy: none
		sourceColumn: Product_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Code'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: ce358d11-17b8-4c9e-8e25-1a8b2cf41fe3
		summarizeBy: none
		sourceColumn: Product Code

		annotation SummarizationSetBy = Automatic

	column 'Short Code'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: dcc9b6da-3bef-413d-b89e-afc658a08e36
		summarizeBy: none
		sourceColumn: Short Code

		annotation SummarizationSetBy = Automatic

	column 'Launch To Retail'
		dataType: dateTime
		formatString: dd/MM/yy
		sourceProviderType: datetime2
		lineageTag: f5a03263-fcba-4789-af33-b44324302f1f
		summarizeBy: none
		sourceColumn: Launch To Retail

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Product URL Icon'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 55a88fb5-c413-4f66-98ca-ee8a0ba73f92
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: Product URL Icon

		annotation SummarizationSetBy = Automatic

	column 'Product URL Image'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 21099d7b-67cb-4073-b3ca-11dad4f14c14
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: Product URL Image

		annotation SummarizationSetBy = Automatic

	column 'Construction Desc'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 70cf02d8-3933-4fd7-b958-d110900d129f
		summarizeBy: none
		sourceColumn: Construction Desc

		annotation SummarizationSetBy = Automatic

	column Last
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 6a956c3a-0e18-4b58-84d7-7934f953528e
		summarizeBy: none
		sourceColumn: Last

		annotation SummarizationSetBy = Automatic

	column Sole
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: c2d1dcf8-85f9-4d45-821c-e5edb2f8d4cd
		summarizeBy: none
		sourceColumn: Sole

		annotation SummarizationSetBy = Automatic

	column 'Sourcing Category'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 716e5162-24e5-41f6-aa4b-1cbaf9d75f83
		summarizeBy: none
		sourceColumn: Sourcing Category

		annotation SummarizationSetBy = Automatic

	column Welted?
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 90c66800-4041-4091-b3bd-1297c71f96dc
		summarizeBy: none
		sourceColumn: Welted?

		annotation SummarizationSetBy = Automatic

	column 'Style Colour Material'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: d0273f40-ccd1-49e2-a0a8-2f599f52d665
		summarizeBy: none
		sourceColumn: Style Colour Material

		annotation SummarizationSetBy = Automatic

	column 'Product Sub-Type'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: bff48da1-da2f-4d51-a1cb-d2ab0e102c4a
		summarizeBy: none
		sourceColumn: Product Sub-Type

		annotation SummarizationSetBy = Automatic

	column 'Product General'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: e66593c3-3efd-492e-ba87-774cb0380339
		summarizeBy: none
		sourceColumn: Product General

		annotation SummarizationSetBy = Automatic

	column 'Product Major'
		dataType: string
		sourceProviderType: nvarchar(12)
		lineageTag: b781a20a-2a8f-4342-b537-d600d630c1ba
		summarizeBy: none
		sourceColumn: Product Major

		annotation SummarizationSetBy = Automatic

	column Collaboration
		dataType: string
		sourceProviderType: decimal(1, 0)
		lineageTag: 11eda440-b1a0-428c-8588-848d6d8a1091
		summarizeBy: none
		sourceColumn: Collaboration

		annotation SummarizationSetBy = Automatic

	column 'D2C Product Definition'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: a3930f1c-2d61-4fc9-83cb-f3db359d05f2
		summarizeBy: none
		sourceColumn: D2C Product Definition

		annotation SummarizationSetBy = Automatic

	column 'Current Selling Status'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: f72b9eaf-9040-40bb-a2ce-016615779ced
		summarizeBy: none
		sourceColumn: Current Selling Status

		annotation SummarizationSetBy = Automatic

	column 'Current Selling Status Sort'
		dataType: int64
		isHidden
		sourceProviderType: decimal(1, 0)
		displayFolder: zz_Misc
		lineageTag: f405cbd8-db0f-491c-9305-e388041ff05d
		summarizeBy: none
		sourceColumn: Current Selling Status Sort

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Product Age Group'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: d2d92349-d2d2-4754-93b9-190415042101
		summarizeBy: none
		sourceColumn: Product Age Group

		annotation SummarizationSetBy = Automatic

	column 'Product Segment Category'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 780aa9bc-bcf2-4a40-bedc-ae002aecadf2
		summarizeBy: none
		sourceColumn: Product Segment Category

		annotation SummarizationSetBy = Automatic

	column 'Tariff Code'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 6a2adac2-475b-450f-851d-78b7c061beb3
		summarizeBy: none
		sourceColumn: Tariff Code

		annotation SummarizationSetBy = Automatic

	column Colour
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 5b281705-730e-4d23-ab8e-3ef4b94c85d5
		summarizeBy: none
		sourceColumn: Colour

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: e6ba7a78-6352-4122-aab1-2342eaadad15
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column 'Launch Season'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: a91b876d-5057-403c-a5fc-2ca829532335
		summarizeBy: none
		sourceColumn: Launch Season

		annotation SummarizationSetBy = Automatic

	column Material
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 89133b9d-7518-4caf-9db6-35e77c37646c
		summarizeBy: none
		sourceColumn: Material

		annotation SummarizationSetBy = Automatic

	column 'Product Segment'
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		displayFolder: zz_Misc
		lineageTag: c3340884-0467-4853-a701-835d4313b9d5
		summarizeBy: none
		sourceColumn: Product Segment

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Collection'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 4ff4902c-37ca-4f66-b8a8-7152f58b1dab
		summarizeBy: none
		sourceColumn: Product Collection

		annotation SummarizationSetBy = Automatic

	column 'Product Type'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 36f785e8-b5bc-4b52-93c5-7564d35cab6c
		summarizeBy: none
		sourceColumn: Product Type

		annotation SummarizationSetBy = Automatic

	column 'Style Name'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 50db94ba-8f70-475c-9ad8-3c3dfb9cb914
		summarizeBy: none
		sourceColumn: Style Name

		annotation SummarizationSetBy = Automatic

	column 'Finance Category'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 4d43f427-5c2e-4b56-ac1f-6e985291f927
		summarizeBy: none
		sourceColumn: Finance Category

		annotation SummarizationSetBy = Automatic

	column 'Finance Sub Category'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: ecc506e9-7c01-4f69-b993-1c3448f79718
		summarizeBy: none
		sourceColumn: Finance Sub Category

		annotation SummarizationSetBy = Automatic

	column 'Item Model Group'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 1a6b72a6-b4d9-42a5-9e65-f7902faa0cc8
		summarizeBy: none
		sourceColumn: Item Model Group

		annotation SummarizationSetBy = Automatic

	column 'Product Search' = Products[Product Code] & ":" & Products[Style Colour Material]
		dataType: string
		lineageTag: 2ee8c5de-61d2-438b-861b-cb45021b16eb
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column 'Product Business Units' =
			IF (
			    Products[Product Segment] = "Kids" || Products[Product Segment] = "Girls" || Products[Product Segment] = "Boys", "Kids",
			    IF (
			        Products[Product Segment] = "Accessories" || Products[Product Segment] = "Clothing", "Clothing & Accessories",
			        IF (
			            Products[Product Segment] = "Light Industry" || Products[Product Segment] = "Heavy Industry" || Products[Product Segment] = "Service" || Products[Product Segment] = "Utility", "Work",
			            IF (
			                Products[Product Segment] = "Casual", "Casual",
			                IF (
			                    Products[Product Segment] = "Fusion", "Fusion",
			                    IF (
			                        Products[Product Segment] = "Originals" || Products[Product Segment] = "Made In England", "Originals",
			                        IF (
			                            Products[Product Segment] = "Shoecare & Laces", "Shoecare & Laces",
			                            IF (
			                                Products[Product Segment] = "Marketing", "Marketing",
			                                IF (
			                                    Products[Product Segment] = "Redundant" || Products[Product Segment] = "Redundant Leather", "Redundant", "Originals"
			                                )
			                            )
			                        )
			                    )
			                )
			            )
			        )
			    )
			)
		dataType: string
		lineageTag: 9a32030e-46b7-488a-9699-760648f4d0be
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column 'TBD vs Continuity/Carry Over' =
			IF (
			    'Products'[Current Selling Status] IN { "Continuity", "Carry Over" },
			    "Continuity/Carry Over",
			    'Products'[Current Selling Status]
			)
		dataType: string
		lineageTag: 11ea219b-4fbe-4ca9-8b44-d69e07979f71
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column Active/Obsolete = IF ( 'Products'[Current Selling Status] = "Obsolete", "Obselete", "Active" )
		dataType: string
		lineageTag: 8b3d6b35-e027-4c65-82f7-0c3ca5a55017
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column 'Launch Month' = FORMAT ( 'Products'[Launch To Retail], "mmmm" )
		dataType: string
		lineageTag: b848935e-a264-4525-a51f-d85e131d0972
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column 'Product Category'
		dataType: string
		lineageTag: 5aa729c2-b7fc-47d5-a3ed-11208d24c2db
		summarizeBy: none
		sourceColumn: Product Category

		annotation SummarizationSetBy = Automatic

	partition Products = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    TB_BFN_VW_DIM_PRODUCT_View = BFN_PRESENTATION_Schema{[Name="TB_BFN_VW_DIM_PRODUCT",Kind="View"]}[Data],
				    #"Filtered Rows"     = Table.SelectRows(TB_BFN_VW_DIM_PRODUCT_View, each ([Product_Key] <> 0)),
				    #"ReplaceValueFalse" = Table.ReplaceValue(#"Filtered Rows",     0, "No", Replacer.ReplaceValue,{"Collaboration"}),
				    #"ReplaceValueTrue"  = Table.ReplaceValue(#"ReplaceValueFalse", 1, "Yes",Replacer.ReplaceValue,{"Collaboration"})
				in
				    #"ReplaceValueTrue"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

