table 'Display Currency'
	lineageTag: e24ed233-7068-42bd-964f-92c5f03ee3f5

	column 'Currency Code'
		dataType: string
		lineageTag: b1356826-b60b-4c3c-bba9-eb587b292f6e
		summarizeBy: none
		sourceColumn: Currency Code

		annotation SummarizationSetBy = Automatic

	column 'Currency Name'
		dataType: string
		lineageTag: 4bf6fca6-11ae-41ac-b05e-f373240673c8
		summarizeBy: none
		sourceColumn: Currency Name

		annotation SummarizationSetBy = Automatic

	column 'Currency Symbol'
		dataType: string
		isHidden
		displayFolder: zz_Misc
		lineageTag: 8fb256c6-c227-4ecf-b503-e7b75e9e3b0d
		summarizeBy: none
		sourceColumn: Currency Symbol

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column XRMultiplier =
			IF (
			    'Display Currency'[Currency Code] = "GBP",
			    1,
			    LOOKUPVALUE (
			        'Exchange Rates'[RATE],
			        'Exchange Rates'[FROMCURRENCY], "GBP",
			        'Exchange Rates'[RATETYPENAME], "BUDGET",
			        'Exchange Rates'[TOCURRENCY], 'Display Currency'[Currency Code]
			    )
			)
		isHidden
		formatString: "£"#,0.###############;-"£"#,0.###############;"£"#,0.###############
		displayFolder: zz_Misc
		lineageTag: 08a355e3-492d-4b01-8ef0-c1ecdba1b6dc
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Display Currency-dec7c5ba-a960-4918-b062-01b98b84c207' = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server, Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    BFN_VW_D365DIMCURRENCY_View = BFN_PRESENTATION_Schema{[Name="BFN_VW_D365DIMCURRENCY",Kind="View"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(BFN_VW_D365DIMCURRENCY_View, each ([Currency Code] = "CAD" or [Currency Code] = "DKK" or [Currency Code] = "EUR" or [Currency Code] = "GBP" or [Currency Code] = "HKD" or [Currency Code] = "JPY" or [Currency Code] = "KRW" or [Currency Code] = "NOK" or [Currency Code] = "SEK" or [Currency Code] = "SGD" or [Currency Code] = "USD"))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

