table 'Sales Packing Slip'
	lineageTag: e93cf990-2294-4bcd-9b6d-dc5b3cb977d6

	column INVENTTRANSID
		dataType: string
		lineageTag: 2ce49d0e-1474-4804-b86b-30307855ff89
		summarizeBy: none
		sourceColumn: INVENTTRANSID

		annotation SummarizationSetBy = Automatic

	column 'Shipped Qty'
		dataType: int64
		formatString: " #,##0"
		lineageTag: 368dac2a-d8eb-4943-9efc-ca520fe0f6e5
		summarizeBy: none
		sourceColumn: Shipped Qty

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column INTERCOMPANYINVENTTRANSID
		dataType: string
		isHidden
		lineageTag: a988938c-da12-409f-831c-0a127860470c
		summarizeBy: none
		sourceColumn: INTERCOMPANYINVENTTRANSID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DATE_KEY
		dataType: string
		isHidden
		lineageTag: b51d0cf6-2e8b-483d-9853-e25ea574deab
		summarizeBy: none
		sourceColumn: DATE_KEY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Sales Packing Slip-d101cdab-89da-41d8-8665-4987784f2ef4' = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server, Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    BFN_VW_D365_FACT_SALES_PACKING_SLIP_View = BFN_PRESENTATION_Schema{[Name="BFN_VW_D365_FACT_SALES_PACKING_SLIP",Kind="View"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(BFN_VW_D365_FACT_SALES_PACKING_SLIP_View, each [INTERCOMPANYINVENTTRANSID] = "" or [INTERCOMPANYINVENTTRANSID] = null )
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

