table 'Account Details'
	lineageTag: db81367e-b092-46fc-8506-4f850c56df23

	column RetailStore_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(32)
		displayFolder: zz_Misc
		lineageTag: 767b16d6-9b99-4d19-898b-95e22021da2a
		summarizeBy: none
		sourceColumn: RetailStore_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column STOREID
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		displayFolder: zz_Misc
		lineageTag: 4e0f12fb-7e06-4030-8956-c583e24878ba
		summarizeBy: none
		sourceColumn: STOREID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Store Name'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: Store Attributes
		lineageTag: 201c8628-1bd2-4ab2-bfeb-8b45e4089f01
		summarizeBy: none
		sourceColumn: Store Name

		annotation SummarizationSetBy = Automatic

	column 'Store Number'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: Store Attributes
		lineageTag: 595e6ee1-ea55-4e06-95ab-0ca7cd778f27
		summarizeBy: none
		sourceColumn: Store Number

		annotation SummarizationSetBy = Automatic

	column 'Overall Store Grade'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: Store Attributes
		lineageTag: bbb49bd2-9a7e-40ba-87c7-7be1eb6c205e
		summarizeBy: none
		sourceColumn: Overall Store Grade

		annotation SummarizationSetBy = Automatic

	column 'Regional Channel'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: Store Attributes
		lineageTag: 4071c26c-8288-470b-bb54-61800d52e8ab
		summarizeBy: none
		sourceColumn: Regional Channel

		annotation SummarizationSetBy = Automatic

	column 'Store Location'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: Store Attributes
		lineageTag: 94f5669c-0b6e-4da0-a53d-17d8518dd6e5
		summarizeBy: none
		sourceColumn: Store Location

		annotation SummarizationSetBy = Automatic

	column 'Store Status'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: Store Attributes
		lineageTag: 94022bcf-bfa9-41b9-8a43-5e8749741c94
		summarizeBy: none
		sourceColumn: Store Status

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: Store Attributes
		lineageTag: a3565677-364b-42e5-b452-f906bb03da45
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: Store Attributes
		lineageTag: 907c97fe-54a8-496f-a48d-7df2f99f89e9
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: Store Attributes
		lineageTag: c8ffc499-36ed-4579-8692-40493ea67c25
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column 'Opening Date'
		dataType: dateTime
		formatString: Short Date
		sourceProviderType: date
		displayFolder: Store Attributes
		lineageTag: 0926c35c-38d2-42d3-b6c7-3203d083accb
		summarizeBy: none
		sourceColumn: Opening Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Closing Date'
		dataType: dateTime
		formatString: Short Date
		sourceProviderType: date
		displayFolder: Store Attributes
		lineageTag: 52cffeee-a5b7-4aae-ad61-cbbe3f023e79
		summarizeBy: none
		sourceColumn: Closing Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Gross Sq ft'
		dataType: double
		formatString: #,##0.00
		sourceProviderType: double
		displayFolder: Store Attributes
		lineageTag: e9c3b8cf-a6ed-4602-b2a0-00cd50d8c812
		summarizeBy: none
		sourceColumn: Gross Sq ft

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Gross Sqm'
		dataType: double
		formatString: #,##0.00
		sourceProviderType: double
		displayFolder: Store Attributes
		lineageTag: 77a34a3b-cbf6-4b2f-bfbc-85bc7ec00a8b
		summarizeBy: none
		sourceColumn: Gross Sqm

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Linear Ft'
		dataType: double
		formatString: #,##0.00
		sourceProviderType: double
		displayFolder: Store Attributes
		lineageTag: 8a68129c-bcd3-4f44-9e57-b6e66f414254
		summarizeBy: none
		sourceColumn: Linear Ft

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column Latitude
		dataType: double
		formatString: #,##0.00
		sourceProviderType: double
		displayFolder: Store Attributes
		lineageTag: 8f5f55f7-f2b7-4f3f-bac9-3b7a6bacd2c5
		summarizeBy: none
		sourceColumn: Latitude

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column Longtitude
		dataType: double
		formatString: #,##0.00
		sourceProviderType: double
		displayFolder: Store Attributes
		lineageTag: e432df1b-4293-4f6f-9240-6ddf3dd79ae9
		summarizeBy: none
		sourceColumn: Longtitude

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Footwear SKU Capacity'
		dataType: int64
		displayFolder: Store Attributes
		lineageTag: e15ffc4f-f449-4586-8e9b-5d29aa9ff092
		summarizeBy: none
		sourceColumn: Footwear SKU Capacity

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Price Profile'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: Store Attributes
		lineageTag: 6b3a743a-e71e-4ba7-84a4-8bf6e19f525c
		summarizeBy: none
		sourceColumn: Price Profile

		annotation SummarizationSetBy = Automatic

	column 'Regional Manager'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: Store Attributes
		lineageTag: 52ffd704-eacb-482f-b5bf-7bd805df76d0
		summarizeBy: none
		sourceColumn: Regional Manager

		annotation SummarizationSetBy = Automatic

	column 'Tourist Level'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: Store Attributes
		lineageTag: bc996b96-9e7b-4a39-a26e-cbfc65fce83f
		summarizeBy: none
		sourceColumn: Tourist Level

		annotation SummarizationSetBy = Automatic

	column 'Store Image'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: Store Attributes
		lineageTag: 26f63b4d-55b9-49a9-b025-5be4c359d0ca
		summarizeBy: none
		sourceColumn: Store Image

		annotation SummarizationSetBy = Automatic

	column COMPANYID
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		displayFolder: zz_Misc
		lineageTag: 80e991dd-fbb3-4bc9-b186-b8a58ef6b02f
		summarizeBy: none
		sourceColumn: COMPANYID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Cost Centre'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: Store Attributes
		lineageTag: 2b378eab-b2da-4bc1-b5cc-355afdcee55f
		summarizeBy: none
		sourceColumn: Cost Centre

		annotation SummarizationSetBy = Automatic

	column WHtoStore_Key = 'Account Details'[COMPANYID] & ":" & 'Account Details'[STOREID]
		dataType: string
		displayFolder: zz_Misc
		lineageTag: 71fb94ea-aa22-4522-89c8-7f4c535dcaf8
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column 'Store Maturity (current) Sort' =
			VAR fyear =
			    IF ( MONTH ( TODAY () ) < 4, YEAR ( TODAY () ) - 1, YEAR ( TODAY () ) )
			VAR BTFY =
			    DATE ( fyear, 4, 1 )
			VAR fyear1 =
			    IF ( MONTH ( TODAY () ) < 4, YEAR ( TODAY () ) - 2, YEAR ( TODAY () ) - 1 )
			VAR BLFY =
			    DATE ( fyear1, 4, 1 )
			RETURN
			    SWITCH (
			        TRUE (),
			        AND (
			            'Account Details'[Closing Date] <= [Yesterday],
			            NOT ( ISBLANK ( 'Account Details'[Closing Date] ) )
			        ), 7,
			        'Account Details'[Closing Date] > [Yesterday], 6,
			        AND (
			            DATEDIFF (
			                'Account Details'[Opening Date],
			                'Account Details'[Closing Date],
			                MONTH
			            ) < 24,
			            NOT ( ISBLANK ( 'Account Details'[Closing Date] ) )
			        ), 4,
			        ISBLANK ( 'Account Details'[Opening Date] ), 3,
			        'Account Details'[Opening Date] < BLFY, 1,
			        'Account Details'[Opening Date] < BTFY, 2,
			        'Account Details'[Opening Date] > BTFY, 3,
			        5
			    )
		dataType: int64
		isHidden
		displayFolder: zz_Misc
		lineageTag: 7e58b844-3e51-4e9a-bdb1-8b42488b56da
		summarizeBy: none
		isDataTypeInferred

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Store Maturity (current)' =
			VAR fyear =
			    IF ( MONTH ( TODAY () ) < 4, YEAR ( TODAY () ) - 1, YEAR ( TODAY () ) )
			VAR BTFY =
			    DATE ( fyear, 4, 1 )
			VAR fyear1 =
			    IF ( MONTH ( TODAY () ) < 4, YEAR ( TODAY () ) - 2, YEAR ( TODAY () ) - 1 )
			VAR BLFY =
			    DATE ( fyear1, 4, 1 )
			RETURN
			    SWITCH (
			        TRUE (),
			        AND (
			            'Account Details'[Closing Date] <= [Yesterday],
			            NOT ( ISBLANK ( 'Account Details'[Closing Date] ) )
			        ), "Closed",
			        'Account Details'[Closing Date] > [Yesterday], "Closing",
			        AND (
			            DATEDIFF (
			                'Account Details'[Opening Date],
			                'Account Details'[Closing Date],
			                MONTH
			            ) < 24,
			            NOT ( ISBLANK ( 'Account Details'[Closing Date] ) )
			        ), "Popup",
			        ISBLANK ( 'Account Details'[Opening Date] ), "New",
			        'Account Details'[Opening Date] < BLFY, "LFL",
			        'Account Details'[Opening Date] < BTFY, "Maturing",
			        'Account Details'[Opening Date] > BTFY, "New",
			        "Other"
			    )
		dataType: string
		displayFolder: Store Attributes
		lineageTag: b19223fa-88ee-4758-b6d8-db9bd7a599cc
		summarizeBy: none
		isDataTypeInferred
		sortByColumn: 'Store Maturity (current) Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition 'Account Details' = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    TB_BFN_VW_D365DIMRETAILSTORE_View = BFN_PRESENTATION_Schema{[Name="TB_BFN_VW_D365DIMRETAILSTORE",Kind="View"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(TB_BFN_VW_D365DIMRETAILSTORE_View,{{"Footwear SKU Capacity", Int64.Type}}),
					#"Removed Duplicates" = Table.Distinct(#"Changed Type", {"RetailStore_Key"}),
				    #"Kept First Rows" = Table.FirstN(#"Removed Duplicates",NumberOfRows),
				    ParameterFilter = if NumberOfRows > 0 then #"Kept First Rows" else #"Removed Duplicates"
				in
				    ParameterFilter

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

