table 'Adjustments Sales'
	isHidden
	lineageTag: 4ef7ef53-0654-4a21-ac8a-6c43284503fc

	column 'Amount at Constant Rate'
		dataType: decimal
		isHidden
		sourceProviderType: decimal(38, 4)
		displayFolder: zz_Value
		lineageTag: ca169b54-8beb-4c49-a273-d6a04d538156
		summarizeBy: none
		sourceColumn: Amount at Constant Rate

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AccountingDate_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		displayFolder: zz_Keys
		lineageTag: 2d0cff8c-f934-473b-aae0-c6d59f4584a6
		summarizeBy: none
		sourceColumn: AccountingDate_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Company_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(32)
		displayFolder: zz_Keys
		lineageTag: 48c350f2-ac66-4ccd-ae78-61d9ffc3775d
		summarizeBy: none
		sourceColumn: Company_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Channel_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(32)
		displayFolder: zz_Keys
		lineageTag: 7b1a06fb-ec8f-4175-917f-4a0b2cf8bcc5
		summarizeBy: none
		sourceColumn: Channel_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Adjustments Sales' = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    TB_BFN_VW_D365FACTASE_SALES_View = BFN_PRESENTATION_Schema{[Name="TB_BFN_VW_D365FACTASE_SALES",Kind="View"]}[Data],
				    #"Filtered Rows1"   = Table.SelectRows(TB_BFN_VW_D365FACTASE_SALES_View, each [TransactionTypeDesc] <> "Sales" and [MAINACCOUNTID] >= "40001" and [MAINACCOUNTID] <= "49999"),
				    #"Selected Columns" = Table.SelectColumns(#"Filtered Rows1",{"AccountingDate_Key", "Channel_Key", "Company_Key", "Amount at Constant Rate"}),
				    #"Kept First Rows" = Table.FirstN(#"Selected Columns",NumberOfRows),
				    ParameterFilter = if NumberOfRows > 0 then #"Kept First Rows" else #"Selected Columns"
				in
				    ParameterFilter

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

