table 'Purchase Orders'
	isHidden
	lineageTag: 7bd32425-1d0f-4d97-8c89-787b735be9e3

	column CONFIRMEDDELIVERYDATE
		dataType: dateTime
		isHidden
		formatString: Short Date
		sourceProviderType: date
		lineageTag: 7327967a-4d14-4fe7-bca8-4883d4c1e445
		summarizeBy: none
		sourceColumn: CONFIRMEDDELIVERYDATE

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column SO_PO_ID
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: 3054c4cb-5915-4ddf-9620-70f16daf1978
		summarizeBy: none
		sourceColumn: SO_PO_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Purchase Orders' = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    TB_BFN_VW_D365FACTPURCHASEORDER_PURCHASEORDERLINE_View = BFN_PRESENTATION_Schema{[Name="TB_BFN_VW_D365FACTPURCHASEORDER_PURCHASEORDERLINE",Kind="View"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(TB_BFN_VW_D365FACTPURCHASEORDER_PURCHASEORDERLINE_View, each ([SO_PO_ID] <> null))
				in
				    #"Filtered Rows"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

