table 'Selling Status - Order Entry'
	lineageTag: 61eecfcb-3dc0-4d72-b424-62892b498ab6

	column SELLINGSTATUS
		dataType: int64
		isHidden
		sourceProviderType: nvarchar(16777216)
		displayFolder: zz_Misc
		lineageTag: ea93ad16-1a4a-4c48-927d-389b9489703d
		summarizeBy: none
		sourceColumn: SELLINGSTATUS

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Selling Status - Order Entry'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: a42f1040-d458-4db6-a5dd-21813d3df8b3
		summarizeBy: none
		sourceColumn: Selling Status - Order Entry

		annotation SummarizationSetBy = Automatic

	column 'Selling Status Sort'
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: decimal(1, 0)
		displayFolder: zz_Misc
		lineageTag: 0b59c9e0-7a3f-46db-a03d-7291d2e47742
		summarizeBy: none
		sourceColumn: Selling Status Sort

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column 'TBD vs Continuity/Carry Over - Order Entry' =
			IF (
			    'Selling Status - Order Entry'[Selling Status - Order Entry]
			        IN { "Continuity", "Carry Over" },
			    "Continuity/Carry Over",
			    'Selling Status - Order Entry'[Selling Status - Order Entry]
			)
		dataType: string
		lineageTag: bebff6ad-01b6-4e61-b27f-a1cc9ee5958f
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	partition 'Selling Status - Order Entry' = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    TB_BFN_VW_DIM_PRODUCT_SELLING_STATUS_ORDER_ENTRY_View = BFN_PRESENTATION_Schema{[Name="TB_BFN_VW_DIM_PRODUCT_SELLING_STATUS_ORDER_ENTRY",Kind="View"]}[Data],
				    #"Removed Duplicates" = Table.Distinct(TB_BFN_VW_DIM_PRODUCT_SELLING_STATUS_ORDER_ENTRY_View, {"SELLINGSTATUS"}),
				    #"Removed Blank Rows" = Table.SelectRows(#"Removed Duplicates", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
				in
				    #"Removed Blank Rows"

	annotation PBI_ResultType = Table

