table Warehouse
	lineageTag: 15b6e244-ce58-4188-ae43-2622644e7632

	column Warehouse_Key
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 0546bc84-b490-4251-bb83-a6418abffb3b
		summarizeBy: none
		sourceColumn: Warehouse_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Warehouse ID'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: f6c8a9c9-f5d3-4513-88cd-f47d7666eb33
		summarizeBy: none
		sourceColumn: Warehouse ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PARENTSTOREID
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 19c40436-4bf0-4e8f-b1b7-fc9651a26cbb
		summarizeBy: none
		sourceColumn: PARENTSTOREID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Company ID'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: d57e12d3-7fc8-406e-ac36-6c5dd3d5357e
		summarizeBy: none
		sourceColumn: Company ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Warehouse Channel'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: cf3f3815-43b1-4308-9749-f16a89e14f02
		summarizeBy: none
		sourceColumn: Warehouse Channel

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FinancialChannel
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 6173a534-c6c6-4c58-a827-500b253ca9fe
		summarizeBy: none
		sourceColumn: FinancialChannel

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column WHtoStore_Key = Warehouse[Company ID] & ":" & Warehouse[PARENTSTOREID]
		dataType: string
		lineageTag: 6a010875-e362-460c-9c79-1850eb972df0
		summarizeBy: none
		isDataTypeInferred

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column WAREHOUSENAME
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: 38c5bd7e-7dec-47c0-998c-4a2d80e67c59
		summarizeBy: none
		sourceColumn: WAREHOUSENAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Warehouse = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    TB_BFN_VW_D365DIMWAREHOUSE_View = BFN_PRESENTATION_Schema{[Name="TB_BFN_VW_D365DIMWAREHOUSE",Kind="View"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(TB_BFN_VW_D365DIMWAREHOUSE_View,{"Warehouse_Key", "WAREHOUSENAME", "ISRETAILSTOREWAREHOUSE", "OPERATIONALSITEID", "Company ID", "Warehouse ID", "PARENTSTOREID", "Warehouse Channel", "FinancialChannel"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Removed Other Columns",{"ISRETAILSTOREWAREHOUSE", "OPERATIONALSITEID"})
				in
				    #"Removed Columns"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

