table PRODUCTS
	lineageTag: 40ba39d2-c078-429e-9f0b-7ddb55334504

	column Product_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(32)
		lineageTag: d3c32e8d-9af9-4dcf-92cc-3f5cb46c257c
		summarizeBy: none
		sourceColumn: Product_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Code'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: a872395e-e2a8-409e-bd82-26b7a6c11e24
		summarizeBy: none
		sourceColumn: Product Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Last
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 49acece4-6452-4d32-aa59-f1b1c54f3530
		summarizeBy: none
		sourceColumn: Last

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Sub Type'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 7ad63a42-3ac4-4be5-a072-41919124a015
		summarizeBy: none
		sourceColumn: Product Sub Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Segment'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 2efd7e74-58f6-4d5c-b8a3-7962d1f1f899
		summarizeBy: none
		sourceColumn: Product Segment

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: d08eeb26-9e40-43fa-8204-57c21658b331
		summarizeBy: none
		sourceColumn: Product Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Colour
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 421c30f5-a716-4b09-b5a7-e51adaae2e37
		summarizeBy: none
		sourceColumn: Colour

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: bbee8586-df3a-4f1b-8b72-b55dae3e8433
		summarizeBy: none
		sourceColumn: Gender

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Launch Season'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 9f19219f-68db-4f5e-9038-e5326bec2ae5
		summarizeBy: none
		sourceColumn: Launch Season

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Material
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: e6ba1426-dc72-4397-bb1f-4d62ba3d4f86
		summarizeBy: none
		sourceColumn: Material

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Style Name'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 0111cb42-0b47-42f5-97ab-df1b9e0c3d9c
		summarizeBy: none
		sourceColumn: Style Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Collection'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 056d5b50-71b7-480b-a0cd-5cb8ab48d9eb
		summarizeBy: none
		sourceColumn: Product Collection

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Type'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 162fb121-dece-47f5-8f19-e9a139688408
		summarizeBy: none
		sourceColumn: Product Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Category'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: b5b3ff5e-05cc-4509-95ef-cf08df8fcff5
		summarizeBy: none
		sourceColumn: Product Category

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Sub Category'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 5c250906-f8c2-4bab-bcad-f14e7586f01f
		summarizeBy: none
		sourceColumn: Product Sub Category

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Welt Type'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 1d92e25b-c158-4eff-82d0-056f2237b063
		summarizeBy: none
		sourceColumn: Welt Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Silhouette
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: d616df76-d784-43c9-8e01-b02816d460c7
		summarizeBy: none
		sourceColumn: Silhouette

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Collaboration
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: a2f3c4fb-d9b8-4f85-8764-9598e64a44be
		summarizeBy: none
		sourceColumn: Collaboration

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Family'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: f79670e7-a931-49bd-91d9-17d23d08e38f
		summarizeBy: none
		sourceColumn: Product Family

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Analysis' = BLANK ()
		dataType: int64
		lineageTag: 8b312825-dcf6-4685-993b-b1205139e6de
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Launch Category' = ```
			BLANK () 
			```
		dataType: int64
		lineageTag: 4adda914-686b-4060-978a-7a39ce9e1ef1
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition PRODUCTS-c6aa5255-09f7-48bc-8edb-d0bb5db5d096 = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    PRODUCT_BFN_VW_DIM_PRODUCT_View = BFN_PRESENTATION_Schema{[Name="PRODUCT_BFN_VW_DIM_PRODUCT",Kind="View"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(PRODUCT_BFN_VW_DIM_PRODUCT_View,{"Product_Key", "Product Code", "Product Sub Type", "Product Segment", "Last", "Product Category", "Product Sub Category", "Product Type", "Gender", "Product Collection", "Product Name",  "Style Name", "Colour", "Material", "Launch Season", "Welt Type", "Collaboration", "Silhouette", "Product Family"})
				in
				    #"Removed Other Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

