table Products
	lineageTag: d3c847e0-792e-41fd-abb5-928b35524b6f

	column Product_Key
		dataType: string
		isHidden
		displayFolder: zz_Keys
		lineageTag: ee8d07da-54df-4922-b130-e592ff1fede0
		summarizeBy: none
		sourceColumn: Product_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Code'
		dataType: string
		lineageTag: 93d3640b-2248-4a36-ae8b-ea42aeab686e
		summarizeBy: none
		sourceColumn: Product Code

		annotation SummarizationSetBy = Automatic

	column 'Short Code'
		dataType: string
		lineageTag: 578796c1-bd0e-4097-97cf-6a24f2f01af0
		summarizeBy: none
		sourceColumn: Short Code

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: dc971bbc-f2ca-4ee3-9f14-4daacf317132
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column 'Launch To Retail'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 1a0bb168-7e6d-4741-8cfb-f8e600afca28
		summarizeBy: none
		sourceColumn: Launch To Retail

		annotation SummarizationSetBy = Automatic

	column 'Tariff Code'
		dataType: string
		lineageTag: f92ba8a7-8bd2-42a5-bfaf-7bc29666397d
		summarizeBy: none
		sourceColumn: Tariff Code

		annotation SummarizationSetBy = Automatic

	column 'Launch Season'
		dataType: string
		lineageTag: c94b2c22-c68a-45e0-8339-2bb49015c749
		summarizeBy: none
		sourceColumn: Launch Season

		annotation SummarizationSetBy = Automatic

	column 'Product URL Icon'
		dataType: string
		lineageTag: a96b9402-635f-414f-b46d-caa16f71bc2e
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: Product URL Icon

		annotation SummarizationSetBy = Automatic

	column 'Product URL Image'
		dataType: string
		lineageTag: b7e1dfa4-471b-49da-9bbb-811a151fb0d7
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: Product URL Image

		annotation SummarizationSetBy = Automatic

	column 'Construction Desc'
		dataType: string
		lineageTag: 553aabe5-a97e-445f-97c0-de861b2af727
		summarizeBy: none
		sourceColumn: Construction Desc

		annotation SummarizationSetBy = Automatic

	column 'Style Name'
		dataType: string
		lineageTag: e51cf78a-2bf2-4441-b60f-d0cdd3bbc34a
		summarizeBy: none
		sourceColumn: Style Name

		annotation SummarizationSetBy = Automatic

	column Last
		dataType: string
		lineageTag: fb83cf32-990c-42b5-b561-e9b1b9efbf89
		summarizeBy: none
		sourceColumn: Last

		annotation SummarizationSetBy = Automatic

	column Sole
		dataType: string
		lineageTag: e446d708-0ca8-4b8d-af2d-6223fcf01dc5
		summarizeBy: none
		sourceColumn: Sole

		annotation SummarizationSetBy = Automatic

	column 'Sourcing Category'
		dataType: string
		lineageTag: a1282047-0f49-4356-a04d-a36a03504908
		summarizeBy: none
		sourceColumn: Sourcing Category

		annotation SummarizationSetBy = Automatic

	column 'Product Type'
		dataType: string
		lineageTag: db3083de-9f7f-4ad4-bf38-d68ac5501590
		summarizeBy: none
		sourceColumn: Product Type

		annotation SummarizationSetBy = Automatic

	column Welted?
		dataType: string
		lineageTag: b39e703a-db19-47b0-aede-d129f79cc1f0
		summarizeBy: none
		sourceColumn: Welted?

		annotation SummarizationSetBy = Automatic

	column 'Style Colour Material'
		dataType: string
		lineageTag: 7e74f720-36ad-4573-8700-cad43e6e9599
		summarizeBy: none
		sourceColumn: Style Colour Material

		annotation SummarizationSetBy = Automatic

	column 'Product Collection'
		dataType: string
		lineageTag: 1cd90a84-0d91-4b02-8edd-3a8291191249
		summarizeBy: none
		sourceColumn: Product Collection

		annotation SummarizationSetBy = Automatic

	column 'Company ID'
		dataType: string
		isHidden
		displayFolder: zz_Misc
		lineageTag: 45d23a8c-f774-4716-877a-cade4c47a47e
		summarizeBy: none
		sourceColumn: Company ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Sub-Type'
		dataType: string
		lineageTag: 064cc112-6eea-4b0d-af1d-e7363f35778c
		summarizeBy: none
		sourceColumn: Product Sub-Type

		annotation SummarizationSetBy = Automatic

	column 'Product Segment'
		dataType: string
		isHidden
		displayFolder: zz_Misc
		lineageTag: 9735366f-1db4-49f0-b0d5-e14a5fce299c
		summarizeBy: none
		sourceColumn: Product Segment

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Colour
		dataType: string
		lineageTag: 19b05828-f740-490a-a0f2-92c204648ab4
		summarizeBy: none
		sourceColumn: Colour

		annotation SummarizationSetBy = Automatic

	column Material
		dataType: string
		lineageTag: 377e51ae-6d91-4f71-a203-3cf714ad4ad2
		summarizeBy: none
		sourceColumn: Material

		annotation SummarizationSetBy = Automatic

	column 'Product General'
		dataType: string
		lineageTag: e64a81a1-e3f8-4f7f-9218-5e24eb637671
		summarizeBy: none
		sourceColumn: Product General

		annotation SummarizationSetBy = Automatic

	column 'Current Selling Status'
		dataType: string
		lineageTag: 8ba6160d-2a42-41d7-9a5c-d956a2166e3f
		summarizeBy: none
		sourceColumn: Current Selling Status

		annotation SummarizationSetBy = Automatic

	column Collaboration
		dataType: string
		lineageTag: 68d109d1-75cc-4388-8816-b3d7d790793c
		summarizeBy: none
		sourceColumn: Collaboration

		annotation SummarizationSetBy = Automatic

	column 'Product Major'
		dataType: string
		lineageTag: e28286b4-a717-41ba-956c-5529e3e6c174
		summarizeBy: none
		sourceColumn: Product Major

		annotation SummarizationSetBy = Automatic

	column 'Default Vendor'
		dataType: string
		lineageTag: 8ccd9860-2c96-4cf7-a0b1-6a5348c07f3a
		summarizeBy: none
		sourceColumn: Default Vendor

		annotation SummarizationSetBy = Automatic

	column 'Default Vendor Country'
		dataType: string
		lineageTag: 4a457098-2e10-48b1-80e1-d68b6afe724e
		summarizeBy: none
		sourceColumn: Default Vendor Country

		annotation SummarizationSetBy = Automatic

	column 'Current Product Class'
		dataType: string
		lineageTag: 14b05195-7f8a-419d-a774-646abd67fda5
		summarizeBy: none
		sourceColumn: Current Product Class

		annotation SummarizationSetBy = Automatic

	column 'Current Product Class Sort'
		dataType: int64
		isHidden
		displayFolder: zz_Misc
		lineageTag: d08afddf-a5ca-43a0-88cd-7e03e864cbf4
		summarizeBy: none
		sourceColumn: Current Product Class Sort

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Current Selling Status Sort'
		dataType: double
		isHidden
		displayFolder: zz_Misc
		lineageTag: 3cd0582d-c2ec-46fb-bbc8-872c90d5ab91
		summarizeBy: none
		sourceColumn: Current Selling Status Sort

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Product Age Group'
		dataType: string
		lineageTag: 9fc9ec48-380e-47a0-a076-b65624b3de10
		summarizeBy: none
		sourceColumn: Product Age Group

		annotation SummarizationSetBy = Automatic

	column 'Product Segment Category'
		dataType: string
		lineageTag: ebcb727a-42ee-4fa9-b49c-865bbd2e1d46
		summarizeBy: none
		sourceColumn: Product Segment Category

		annotation SummarizationSetBy = Automatic

	column 'Finance Category'
		dataType: string
		lineageTag: a1754c45-709b-44d0-aeaf-576081356e3d
		summarizeBy: none
		sourceColumn: Finance Category

		annotation SummarizationSetBy = Automatic

	column 'Finance Sub Category'
		dataType: string
		lineageTag: aebccb22-9335-4978-9ac1-d8f29249a390
		summarizeBy: none
		sourceColumn: Finance Sub Category

		annotation SummarizationSetBy = Automatic

	column 'Item Model Group'
		dataType: string
		lineageTag: 1d81cc82-68a7-4529-82cc-ce8f2b16a2c4
		summarizeBy: none
		sourceColumn: Item Model Group

		annotation SummarizationSetBy = Automatic

	column 'Product Search' = Products[Product Code] & ":" & Products[Style Colour Material]
		dataType: string
		lineageTag: 0a8c2b14-1070-43e2-85b9-85d14f32e2e3
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column Company_ProductCode = Products[Company ID] & "_" & Products[Product Code]
		dataType: string
		displayFolder: zz_Misc
		lineageTag: a8e8d072-04a2-44aa-9c80-fd03516095ee
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column 'Product Business Units' =
			IF (
			Products[Product Segment] = "Kids" || Products[Product Segment] = "Girls" || Products[Product Segment] = "Boys", "Kids",
			IF (
			Products[Product Segment] = "Accessories" || Products[Product Segment] = "Clothing", "Clothing & Accessories",
			IF (
			Products[Product Segment] = "Light Industry" || Products[Product Segment] = "Heavy Industry" || Products[Product Segment] = "Service" || Products[Product Segment] = "Utility", "Work",
			IF (
			Products[Product Segment] = "Casual", "Casual",
			IF (
			Products[Product Segment] = "Fusion", "Fusion",
			IF (
			Products[Product Segment] = "Originals" || Products[Product Segment] = "Made In England", "Originals",
			IF (
			Products[Product Segment] = "Shoecare & Laces", "Shoecare & Laces",
			IF (
			Products[Product Segment] = "Marketing", "Marketing",
			IF (
			Products[Product Segment] = "Redundant" || Products[Product Segment] = "Redundant Leather", "Redundant", "Originals"
			)
			)
			)
			)
			)
			)
			)
			)
			)
		dataType: string
		lineageTag: 51afd004-04ce-488c-962d-e9a147362e9f
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column 'TBD vs Continuity/Carry Over' =
			IF (
			                  'Products'[Current Selling Status] IN { "Continuity", "Carry Over" },
			                  "Continuity/Carry Over",
			                  'Products'[Current Selling Status]
			              )
		dataType: string
		lineageTag: e14218be-7d3b-4c0e-9b62-e327c14388c2
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column Active/Obsolete = IF ( 'Products'[Current Selling Status] = "Obsolete", "Obselete", "Active" )
		dataType: string
		lineageTag: 34eaedc7-5552-4180-8488-31ccc0ce2207
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column 'Launch Month' = FORMAT ( 'Products'[Launch To Retail], "mmmm" )
		dataType: string
		lineageTag: a66f4dc0-6fe8-4b00-8ced-25dbc92b8eb9
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column 'Product Category' = Products[Product Segment]
		dataType: string
		lineageTag: 8ca01187-bb5d-4697-986f-46e21386f9e7
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	partition Products-136a9a2b-8129-4b36-9fdd-1cae1bf8ac90 = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server, Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    BFN_VW_DIM_PRODUCT_View = BFN_PRESENTATION_Schema{[Name="BFN_VW_DIM_PRODUCT",Kind="View"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(BFN_VW_DIM_PRODUCT_View, each [Product Code] <> "0" and [Product Code] <> "AC617001" and [Product Code] <> null and [Product Code] <> """"""),
				    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows",{{"Collaboration", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","0","No",Replacer.ReplaceText,{"Collaboration"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","1","Yes",Replacer.ReplaceText,{"Collaboration"})
				in
				    #"Replaced Value1"

	annotation PBI_ResultType = Table

