table Pick
	isHidden
	lineageTag: e1270baf-d144-4128-af9f-a622eaf8d42e

	column HandlingStatusDesc
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: 289fa63d-fd6d-45ba-909d-a8434b9935dd
		summarizeBy: none
		sourceColumn: HandlingStatusDesc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column INVENTTRANSID
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: 34b75510-1040-4fef-8639-944af2403097
		summarizeBy: none
		sourceColumn: INVENTTRANSID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Pick Qty'
		dataType: int64
		isHidden
		formatString: #,##0
		sourceProviderType: decimal(38, 0)
		lineageTag: c1bf7fdc-e69c-463b-977d-76eb426fcec8
		summarizeBy: none
		sourceColumn: Pick Qty

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column Product_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(32)
		lineageTag: 12371845-2ffc-429f-b3c1-76ea05491b9b
		summarizeBy: none
		sourceColumn: Product_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Size_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(32)
		lineageTag: a3ce2181-59a2-446f-bbc5-d62d9dd862f5
		summarizeBy: none
		sourceColumn: Size_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Company_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(32)
		lineageTag: 148a67a0-405c-4078-ae82-302639f1ac87
		summarizeBy: none
		sourceColumn: Company_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SELLINGSTATUS
		dataType: int64
		isHidden
		sourceProviderType: decimal(38, 5)
		lineageTag: 082329cb-7780-4257-a713-378453521fd3
		summarizeBy: none
		sourceColumn: SELLINGSTATUS

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column INVENT_LOCATION_ID_WMS
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: d56a1b10-6cf8-4b6b-a437-d4037e827355
		summarizeBy: none
		sourceColumn: INVENT_LOCATION_ID_WMS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Pick-fc143b14-33ac-4dd0-a949-b5fc82710a40 = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    D2C_BFN_FACT_D365PICKING_LIST_View = BFN_PRESENTATION_Schema{[Name="D2C_BFN_FACT_D365PICKING_LIST",Kind="View"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(D2C_BFN_FACT_D365PICKING_LIST_View, each List.Contains({"UKD2C01", "UKRET01", "UKRET02", "UKRET03", "NLRET01", "NLRET02", "UKRET03", "NLD2C01", "USRET01", "USD2C01", "USD2CNJ01", "USRETNJ01", "UKD2CRG01", "USRETRG01", "UKRETRG02", "HKD2C01", "HKRET01", "CAD2CBC01", "CARETBC01"}, [INVENT_LOCATION_ID_WMS])),
				    #"Kept First Rows" = Table.FirstN(#"Filtered Rows",NumberOfRows),
				    ParameterFilter = if NumberOfRows > 0 then #"Kept First Rows" else #"Filtered Rows"
				in
				    ParameterFilter

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

