table Products
	lineageTag: b246e1a6-680f-492e-8f4f-808dc836e1ab

	column Product_Key
		dataType: string
		isHidden
		sourceProviderType: nvarchar(32)
		displayFolder: zz_Misc
		lineageTag: 5a9853e4-c7c1-4a57-af6b-57e52ad7fbbd
		summarizeBy: none
		sourceColumn: Product_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Code'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 321c5798-2f93-4a67-a9a3-12b1d452939e
		summarizeBy: none
		sourceColumn: Product Code

		annotation SummarizationSetBy = Automatic

	column 'Short Code'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 00abaa9f-6c26-46e5-889a-0c51e3b2d6f4
		summarizeBy: none
		sourceColumn: Short Code

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 69829081-36eb-4f5e-bb07-6ddc759d5003
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column 'Launch To Retail'
		dataType: dateTime
		formatString: dd/MM/yy
		sourceProviderType: datetime2
		lineageTag: ee52ed69-8493-444d-84e1-962d6813f384
		summarizeBy: none
		sourceColumn: Launch To Retail

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Tariff Code'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 2c9191ad-f10b-4316-adc0-e9d89caeb6cf
		summarizeBy: none
		sourceColumn: Tariff Code

		annotation SummarizationSetBy = Automatic

	column 'Launch Season'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 99379c74-47ee-461b-a55e-5237a8550f52
		summarizeBy: none
		sourceColumn: Launch Season

		annotation SummarizationSetBy = Automatic

	column 'Product URL Icon'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 4473a088-f4d6-47b1-93d2-564abbe1aa7f
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: Product URL Icon

		annotation SummarizationSetBy = Automatic

	column 'Product URL Image'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 7c568c44-c2ff-4d60-a04d-689c2f6a4d44
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: Product URL Image

		annotation SummarizationSetBy = Automatic

	column 'Style Name'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 91a5c3bd-7ea3-4077-9448-29380e02cad8
		summarizeBy: none
		sourceColumn: Style Name

		annotation SummarizationSetBy = Automatic

	column Last
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 3ab73aca-403a-4f38-a0b2-5775223de7e0
		summarizeBy: none
		sourceColumn: Last

		annotation SummarizationSetBy = Automatic

	column Sole
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 47a4d60c-c164-40c1-8678-a997a203238a
		summarizeBy: none
		sourceColumn: Sole

		annotation SummarizationSetBy = Automatic

	column 'Sourcing Category'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: a5cbb30e-d328-4d33-8f51-58b9372a6a08
		summarizeBy: none
		sourceColumn: Sourcing Category

		annotation SummarizationSetBy = Automatic

	column 'Product Type'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 97167f56-8d03-4e0e-a67f-f81f45c7fd8b
		summarizeBy: none
		sourceColumn: Product Type

		annotation SummarizationSetBy = Automatic

	column Welted?
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: eb9f79d7-109c-4388-8e05-5ddcdbd9e8f7
		summarizeBy: none
		sourceColumn: Welted?

		annotation SummarizationSetBy = Automatic

	column 'Style Colour Material'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 4c3d5a66-bc0f-4fe4-8568-995c98496928
		summarizeBy: none
		sourceColumn: Style Colour Material

		annotation SummarizationSetBy = Automatic

	column 'Product Collection'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: d8aa55ae-8f47-4499-a74f-c6acdde372cf
		summarizeBy: none
		sourceColumn: Product Collection

		annotation SummarizationSetBy = Automatic

	column 'Company ID'
		dataType: double
		lineageTag: b7f5b1e8-216d-47fb-81cf-e757d903ac46
		summarizeBy: count
		sourceColumn: Company ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Product Sub-Type'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 07f6fe15-e99c-4b2c-ab20-b3ca4a6d3a5c
		summarizeBy: none
		sourceColumn: Product Sub-Type

		annotation SummarizationSetBy = Automatic

	column ProductSegment
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		displayFolder: zz_Misc
		lineageTag: b909243c-1483-4e31-b8ce-34677ed5c116
		summarizeBy: none
		sourceColumn: ProductSegment

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Colour
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 4f2e6b29-21b8-4c1d-b6b0-17d025b4508a
		summarizeBy: none
		sourceColumn: Colour

		annotation SummarizationSetBy = Automatic

	column Material
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 29028f1e-ba0f-4753-a670-1e551a78c759
		summarizeBy: none
		sourceColumn: Material

		annotation SummarizationSetBy = Automatic

	column 'Product General'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 72122023-ff7b-4e84-88b6-78688227a82e
		summarizeBy: none
		sourceColumn: Product General

		annotation SummarizationSetBy = Automatic

	column 'Current Selling Status'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 7898ba7a-632f-4fc7-8653-ae1826869650
		summarizeBy: none
		sourceColumn: Current Selling Status
		sortByColumn: 'Current Selling Status Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Product Major'
		dataType: string
		sourceProviderType: nvarchar(12)
		lineageTag: 130f63d4-c9e1-4610-9eff-69470ac20aac
		summarizeBy: none
		sourceColumn: Product Major

		annotation SummarizationSetBy = Automatic

	column Collaboration
		dataType: string
		lineageTag: b8a83824-0666-4f2e-963b-1d6005cd3751
		summarizeBy: none
		sourceColumn: Collaboration

		annotation SummarizationSetBy = Automatic

	column 'D2C Product Definition'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 48830165-7872-467e-a4fb-0af44bbbfa36
		summarizeBy: none
		sourceColumn: D2C Product Definition

		annotation SummarizationSetBy = Automatic

	column 'Current Product Class'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 701a456a-32bf-44fb-8613-347b9609373d
		summarizeBy: none
		sourceColumn: Current Product Class
		sortByColumn: 'Current Product Class Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Current Product Class Sort'
		dataType: int64
		isHidden
		sourceProviderType: decimal(2, 0)
		displayFolder: zz_Misc
		lineageTag: 0182dc7d-3ffb-42f8-9189-453c1f9aa303
		summarizeBy: none
		sourceColumn: Current Product Class Sort

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Current Selling Status Sort'
		dataType: int64
		isHidden
		sourceProviderType: decimal(1, 0)
		displayFolder: zz_Misc
		lineageTag: cd511682-e632-44ef-a5b3-8656936e671d
		summarizeBy: none
		sourceColumn: Current Selling Status Sort

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Product Age Group'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 2a08f684-3e38-4812-b213-01d54daab914
		summarizeBy: none
		sourceColumn: Product Age Group

		annotation SummarizationSetBy = Automatic

	column 'Current Selling Price'
		dataType: double
		formatString: #,##0.00
		sourceProviderType: decimal(32, 6)
		displayFolder: 1. Prices
		lineageTag: 423452df-96df-467d-b6ed-bc5a745a4bbf
		summarizeBy: none
		sourceColumn: Current Selling Price

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Current Selling Price Currency'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: 1. Prices
		lineageTag: 9f17e8bb-a5b1-40a1-88dc-a61cbb95f43a
		summarizeBy: none
		sourceColumn: Current Selling Price Currency

		annotation SummarizationSetBy = Automatic

	column 'Discounted Price Product?'
		dataType: string
		sourceProviderType: bit
		displayFolder: 1. Prices
		lineageTag: 62658567-9f50-41ee-aff1-c25e1aab904b
		summarizeBy: none
		sourceColumn: Discounted Price Product?

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Full Selling Price'
		dataType: double
		formatString: #,##0.00
		sourceProviderType: decimal(32, 6)
		displayFolder: 1. Prices
		lineageTag: 3d62d438-0cee-42b4-a6d3-307e0d825a45
		summarizeBy: none
		sourceColumn: Full Selling Price

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Full Selling Price Currency'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: 1. Prices
		lineageTag: f125563d-80bf-4360-9ccc-2946037fdf16
		summarizeBy: none
		sourceColumn: Full Selling Price Currency

		annotation SummarizationSetBy = Automatic

	column 'Current Product Class Code'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 082c5969-64b3-439a-bbd3-5e701b7ed10a
		summarizeBy: none
		sourceColumn: Current Product Class Code

		annotation SummarizationSetBy = Automatic

	column 'VAT Application'
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		displayFolder: zz_Misc
		lineageTag: f4be0691-df3b-49b8-b487-cdf444dec59e
		summarizeBy: none
		sourceColumn: VAT Application

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Segment Category'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: b6c7954f-c967-4874-9f8b-28a09044ae6f
		summarizeBy: none
		sourceColumn: Product Segment Category

		annotation SummarizationSetBy = Automatic

	column 'Latest Season'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 404dc747-8160-4b0b-9491-d02be82edebc
		summarizeBy: none
		sourceColumn: Latest Season

		annotation SummarizationSetBy = Automatic

	column 'D2C Product Story'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: Merchandising
		lineageTag: 08f94507-870e-4097-b456-bd2cbf517d8d
		summarizeBy: none
		sourceColumn: D2C Product Story

		annotation SummarizationSetBy = Automatic

	column 'IPS D2C Class'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		displayFolder: Merchandising
		lineageTag: 28e000d8-c417-409c-8382-dd2b3a21bb82
		summarizeBy: none
		sourceColumn: IPS D2C Class

		annotation SummarizationSetBy = Automatic

	column 'eCom Product Category'
		dataType: string
		sourceProviderType: nvarchar(15)
		lineageTag: 8f57daea-1d5a-4b76-8244-23fa385e1477
		summarizeBy: none
		sourceColumn: eCom Product Category

		annotation SummarizationSetBy = Automatic

	column 'Finance Category'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: f3a24d8f-da40-4136-9a8e-463afd181a8b
		summarizeBy: none
		sourceColumn: Finance Category

		annotation SummarizationSetBy = Automatic

	column 'Finance Sub Category'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: fcf25b90-4ad1-4eb7-a0d9-c90bf5c2ab7a
		summarizeBy: none
		sourceColumn: Finance Sub Category

		annotation SummarizationSetBy = Automatic

	column 'Item Model Group'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 78475165-c10c-487f-96e4-65f7c8b94ab1
		summarizeBy: none
		sourceColumn: Item Model Group

		annotation SummarizationSetBy = Automatic

	column 'Current Selling Price (excl. VAT)' =
			IF (
			    Products[VAT Application] = "20.0%",
			    Products[Current Selling Price] / 1.2,
			    Products[Current Selling Price]
			)
		dataType: double
		formatString: #,##0.00
		displayFolder: 1. Prices
		lineageTag: ff1af4a8-237c-4af8-ba45-8cab8e432c2b
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Product Search' = Products[Product Code] & ":" & Products[Style Colour Material]
		dataType: string
		lineageTag: 9b3d2bc4-6ecb-44f8-ba2f-0db96d49a49d
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column 'Product Business Units' =
			IF (
			    Products[ProductSegment] IN { "Kids", "Girls", "Boys" }, "Kids",
			    IF (
			        Products[ProductSegment] IN { "Accessories", "Clothing" }, "Clothing & Accessories",
			        IF (
			            Products[ProductSegment] IN { "Light Industry", "Heavy Industry", "Service", "Utility" }, "Work",
			            IF (
			                Products[ProductSegment] = "Casual", "Casual",
			                IF (
			                    Products[ProductSegment] = "Fusion", "Fusion",
			                    IF (
			                        Products[ProductSegment] IN { "Originals", "Made In England" }, "Originals",
			                        IF (
			                            Products[ProductSegment] = "Shoecare & Laces", "Shoecare & Laces",
			                            IF (
			                                Products[ProductSegment] = "Marketing", "Marketing",
			                                IF (
			                                    Products[ProductSegment] IN { "Redundant", "Redundant Leather" }, "Redundant",
			                                    "Originals"
			                                )
			                            )
			                        )
			                    )
			                )
			            )
			        )
			    )
			)
		dataType: string
		lineageTag: ed6dbd7d-be9b-445f-a414-43c99c060ec7
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column 'TBD vs Continuity/Carry Over' =
			IF (
			    'Products'[Current Selling Status] IN { "Continuity", "Carry Over" },
			    "Continuity/Carry Over",
			    'Products'[Current Selling Status]
			)
		dataType: string
		lineageTag: e1b6dad0-ea89-4a04-b45b-357ff0dc7b23
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column Active/Obsolete = IF ( 'Products'[Current Selling Status] = "Obsolete", "Obselete", "Active" )
		dataType: string
		lineageTag: d9c046ba-0a09-47da-8da7-17bbe48bf7e6
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column 'Launch Month' = FORMAT ( 'Products'[Launch To Retail], "mmmm" )
		dataType: string
		lineageTag: 868b5cfc-a597-4e4f-a413-461a81f9eecf
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column Company_ProductCode = Products[Company ID] & "_" & Products[Product Code]
		dataType: string
		isHidden
		displayFolder: zz_Misc
		lineageTag: 0c21ff89-e517-4449-ad3e-05de55f2f873
		summarizeBy: none
		isDataTypeInferred

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Category'
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 9ff8da4b-7a74-42b8-96bf-7bee9cf98602
		summarizeBy: none
		sourceColumn: Product Category

		annotation SummarizationSetBy = Automatic

	partition Products-8fef37b7-3432-44c8-9a59-d827a55442d4 = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    D2C_BFN_VW_DIM_PRODUCT_View = BFN_PRESENTATION_Schema{[Name="D2C_BFN_VW_DIM_PRODUCT",Kind="View"]}[Data],
				    #"Filtered Rows"     = Table.SelectRows(D2C_BFN_VW_DIM_PRODUCT_View, each ([Product_Key] <> 0)),
				    #"ReplaceValueFalse" = Table.ReplaceValue(#"Filtered Rows",     0, "No", Replacer.ReplaceValue,{"Collaboration"}),
				    #"ReplaceValueTrue"  = Table.ReplaceValue(#"ReplaceValueFalse", 1, "Yes",Replacer.ReplaceValue,{"Collaboration"})
				in
				    #"ReplaceValueTrue"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

