table 'Exchange Rates'
	isHidden
	lineageTag: d8b97269-976a-4ece-8671-842bc4c534e3

	column FROMCURRENCY
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: 83409fbf-d282-40da-8dde-04e0510f67d0
		summarizeBy: none
		sourceColumn: FROMCURRENCY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TOCURRENCY
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: 7976afa2-3b21-40ca-9ccc-03cc6858275c
		summarizeBy: none
		sourceColumn: TOCURRENCY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RATETYPENAME
		dataType: string
		isHidden
		sourceProviderType: nvarchar(16777216)
		lineageTag: 8f86fc77-f47a-4127-b34a-ccc287094181
		summarizeBy: none
		sourceColumn: RATETYPENAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RATE
		dataType: double
		isHidden
		sourceProviderType: decimal(16, 6)
		lineageTag: 5b6d0353-1490-41ec-8d3e-c98d08870435
		summarizeBy: sum
		sourceColumn: RATE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DATE
		dataType: dateTime
		isHidden
		formatString: Long Date
		sourceProviderType: date
		lineageTag: 2d8bac0c-5764-439d-8b6f-0151942ca6bc
		summarizeBy: none
		sourceColumn: DATE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'Exchange Rates-ef1d3727-018c-4c89-8a34-b3f1dc583fe2' = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(Datasource_Server,Datasource_Warehouse),
				    PRESENTATION_Database = Source{[Name=Datasource_Database,Kind="Database"]}[Data],
				    BFN_PRESENTATION_Schema = PRESENTATION_Database{[Name=Datasource_Schema,Kind="Schema"]}[Data],
				    D2C_BFN_VW_D365FACTCURRENCYEXCHANGERATE2_View = BFN_PRESENTATION_Schema{[Name="D2C_BFN_VW_D365FACTCURRENCYEXCHANGERATE2",Kind="View"]}[Data],
				    #"Changed Type"   = Table.TransformColumnTypes(D2C_BFN_VW_D365FACTCURRENCYEXCHANGERATE2_View,{{"DATE", type date}}),
				    #"Filtered Rows"  = Table.SelectRows(#"Changed Type", each [RATETYPENAME] = "BUDGET"),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each [DATE] = DateTime.Date(DateTime.LocalNow()))
				in
				    #"Filtered Rows1"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

